### ISSUE TITLE
@WeaklyLinked doesn't work for return types?

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#1004]
In UIScreen.java we have: 

```Java
@WeaklyLinked
@Method(selector = "displayLinkWithTarget:selector:")
public native CADisplayLink createDisplayLink(NSObject target, Selector sel);
```

That's the only method in the CocoaTouch bindings that uses `CADisplayLink`. It shouldn't get compiled/linked because of the `@WeaklyLinked` annotation in conservative mode but the RoboVM console still says it's compiled.

**Comment by ntherning** [comment]
The reason is that the `@WeaklyLinked` annotation isn't copied to the generated `@Bridge`/`@Callback` methods so those are not stripped even if the `createDisplayLink()` is stripped. We need to copy `@ WeaklyLinked`/`@StronglyLinked` in the `ObjCMemberPlugin` to the generated methods.
