### ISSUE TITLE
When creating ipa actool doesn't output files into the app bundle root

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#1011]
It outputs to the install dir which is not the app bundle in the case of creating an ipa.

**Comment by deadpixelsociety** [comment]
This is fixed when creating using the 'createIPA' gradle task. However the plugin-based Build -> Create IPA still dumps the assets into the root folder and not the .app bundle.

**Comment by BlueRiverInteractive** [comment]
The gradle task and the plugins share the same code for creating IPA from the compiler, so it either works or fails for both. Please make sure to use the latest snapshot versions of the plugins and it should work.

**Comment by deadpixelsociety** [comment]
I downloaded the latest snapshot from download.robovm.org earlier. I'll try clearing everything out and giving it another shot.
