### ISSUE TITLE
iPhone6 plus: UIScreen.getMainScreen().getBounds() returns wrong size?

### ISSUE THREAD

**Issue by rotter** [robovm/robovm#1014]
Hey.

I was trying to cook up some way to detect if the device is an iPhone 6+, and trying to do it using screen size I noticed it's returning the wrong screen size.

Expected size for iPhone6+: 736 x 414
Size I got when running: 568 x 320

Seems to be the issue discussed here, but the solution there doesnt apply (it's for people who use Xcode), and also the person was having the problem on the simulator (Im testing on a real device):

http://stackoverflow.com/questions/26083358/having-issue-with-detect-iphone-6-plus-on-simulator

Some possibly relevant LibGDX/RoboVM debugging stuff on my console when I launch the app:

[debug] IOSApplication: iOS version: 8.3
[debug] IOSApplication: Running in 64-bit mode
[debug] IOSApplication: scale: 2.6086957
[debug] IOSApplication: Unscaled View: Portrait 320x568
[debug] IOSApplication: View: Portrait 834x1481
[debug] IOSGraphics: 834.0x1481.0, 2.6086957
[debug] IOSGraphics: Display: ppi=401, density=2.50625

Im using LibGDX 1.6.2 and RoboVM 1.3.0.

**Comment by BlueRiverInteractive** [comment]
This is not a RoboVM issue. Please post on the mailing list groups.google.com/forum/#!forum/robovm

My guess is that the necessary launch image for iPhones 6+ isn't provided. You could try to create a new ios single view application which has all launch images and check the reported size.

**Comment by rotter** [comment]
Im no iOS pro, so I indeed didnt have the iPhone 6+ launch image, but adding one didnt cause any change. Same resolution is being reported.

I understand this might not be a RoboVM issue, but I failed to see this as clearly as you. Can you provide a link or any kind of info that points to that instead of just closing the issue and saying "not RoboVM"? Something along the lines "I have tested and on my app it displays the right resolution for iPhone 6 plus", or "Creating a blank LibGDX/RoboVM project will detect properly iPhone 6's screen", or "There is a discussion on <this> link that explains exactly that", ...

From my research it seems that adding a launch image for iPhone 6 and iPhone 6 plus is not enough, it seems you need to provide a launch file (small xib screen) for those devices. See this link: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LaunchImages.html

Especially this part:
"IMPORTANT
You use a launch XIB or storyboard file to indicate that your app runs on iPhone 6 Plus or iPhone 6."

But again, I dont know much of iOS/Xcode.

**Comment by rotter** [comment]
For completion of information: on that same link on the bottom it says you CAN add a launch image for iPhone6/6p instead of a launch file, so Im lost here. Adding one (with the exact dimensions as stated) didnt work, as I mentioned already.

One possibility is that the small xib file is needed by iOS, and XCode generates that file when compiling when you dont provide one (but provides the image)? If this is true then RoboVM would need to do the same process?

Another very relevant information I forgot to add: the 6 plus launch image is NOT being used/displayed on my project. It simply ignores the image and uses another one (didnt check which).

And, going back to my previous comment: this, of course, can be a problem with my specific project. If someone can say "I have tested on my device/simulator and it is showing the correct iPhone6+ resolution or launch image" then we're set here.

**Comment by BlueRiverInteractive** [comment]
Hi! Sorry, I really closed out this issue too early! 

I tried it out myself and you really only need to add the correct missing launch images. 
With the correct launch image I get `{{0, 0}, {414, 736}}`, without I get `{{0, 0}, {320, 568}}`.

Unfortunately, the current RoboVM templates are lacking these launch images (or are not correctly named). I will fix this asap.

You will need a Images.xcassets folder with a LaunchImage.launchImage folder in your resources folder. You can then open this folder in Xcode and just drag-and-drop your launch images for each required size. Once I've fixed the templates, you can just replace the predefined launch images and you're ready to go.

Again, sorry for the inconvenience :/

**Comment by rotter** [comment]
Hey!

Thanks for the info, but I failed to grasp how to fix it. I dont know anything of Xcode, so I feel I should wait for that template fix. Please let me know when that gets changed/fixed and I will try to apply here!

Thanks again.

**Comment by rotter** [comment]
It worked now here! 

 [debug] IOSApplication: iOS version: 8.3
 [debug] IOSApplication: Running in 64-bit mode
 [debug] IOSApplication: scale: 2.6086957
 [debug] IOSApplication: Unscaled View: Portrait 414x736   <---------
 [debug] IOSApplication: View: Portrait 1080x1920
 [debug] IOSGraphics: 1080.0x1920.0, 2.6086957
 [debug] IOSGraphics: Display: ppi=401, density=2.50625

I think everything is correct, because the only thing I had to do was create a new LibGDX project and get the filenames from there. My project was old, so the iPhone 6 files didnt exist yet, so I just named them randomly when I created (I didnt know I had to follow a exact name scheme).

For future reference, these are the correct filenames:

Default-375w-667h@2x.png
Default-414w-736h@3x.png
Default-568h@2x.png
Default.png
Default@2x.png
Default@2x~ipad.png
Default~ipad.png


Thanks again, and indeed it wasnt a RoboVM bug. But I believe there should be some warnings when copying the launch image files, saying something like "LAUNCH IMAGE NOT FOUND: Default-414w-736h@3x.png , IGNORING"

Best

**Comment by BlueRiverInteractive** [comment]
It's great to hear it's working now! :)
 BTW I just updated the RoboVM templates with the new iPhone 6 and 6+ sizes, so you can also use these as a reference (it's a bit easier to work with the Images.xcassets folders because you do not have to add something to your Info.plist.xml).

**Comment by tomfisher** [comment]
Did you guys update the templates for Eclipse? It seems that the bound template still lacks the launch image.
