### ISSUE TITLE
Breakpoints never get hit

### ISSUE THREAD

**Issue by AgrarPirat** [robovm/robovm#1026]
Dear RoboVM team,

I've never been able to get debugging working with RoboVM. The problem is that breakpoints never get hit. Neither on an iOS device, nor on the simulator. 
My development environment looks like this:
OSX 10.10.3 - running on a case sensitive file system.
Android Studio 1.3 preview 5
RoboVM 1.4  (but also happened with previous versions)
RoboVM plugin 1.4
libGDX 1.6.2
iPad 3 running iOS 8.1.2

When starting Android Studio, I grant permission to to accept incoming network connections, but it doesn't seem to have any effect. Same is true if the firewall is disabled.
Do you have any ideas what could be wrong here?

**Comment by badlogic** [comment]
There's a bug in RoboVM 1.4 where breakpoints you set after launch will not
get hit. The next nightly build (1.4.1) will have a fix for that.

Despite this, breakpoints set before program launch should get hit. Here
are a few diagnostics you can try.

1. there is a folder called robovm-build, which contains logs for each
debug launch. Please post these.
2. add the following programs args to your run configuration:
-rvm:log=debug. This will log all kinds of debug info to the console
window. Please post these as well.

**Comment by AgrarPirat** [comment]
Please excuse the delay, a cold knocked me out.
I've added the -rvm:log=debug switch to the run configuration, placed a breakpoint in the ctor and render method of the first screen that gets active and started a debug launch, but neither of the two breakpoints got hit.
The robovm-build folder contained only four files while the app was running:
```
ios/robovm-build/xcode/.ib/ios.xcodeproj/project.xcworkspace/contents.xcworkspacedata
ios/robovm-build/xcode/.ib/ios.xcodeproj/project.pbxproj
ios/robovm-build/xcode/.ib/ios.xcodeproj/robovm.plist
ios/robovm-build/xcode/.ib/Prefix.pch
```

Is any of those files of interest to you? 
During the debug launch, the robovm console printed the following:

```
9:38:08 PM: Executing external task 'launchIOSDevice -rvm:log=debug'...
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:ios:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: /Users/.../.../IOsLocalNotifications.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning

:ios:processResources UP-TO-DATE
:ios:classes
:ios:jar
:ios:assemble
:ios:compileTestJava UP-TO-DATE
:ios:processTestResources UP-TO-DATE
:ios:testClasses UP-TO-DATE
:ios:test UP-TO-DATE
:ios:check UP-TO-DATE
:ios:build
:ios:launchIOSDevice
Root pattern com.badlogic.gdx.physics.bullet.** matches no classes
2015-06-26 21:38:41.865 IOSLauncher[8695:1586324] [debug] IOSApplication: iOS version: 8.3
2015-06-26 21:38:41.867 IOSLauncher[8695:1586324] [debug] IOSApplication: Running in 32-bit mode
2015-06-26 21:38:41.881 IOSLauncher[8695:1586324] [debug] IOSApplication: scale: 2.0
2015-06-26 21:38:41.897 IOSLauncher[8695:1586324] [debug] IOSApplication: Unscaled View: Portrait 320x480
2015-06-26 21:38:41.898 IOSLauncher[8695:1586324] [debug] IOSApplication: View: Portrait 640x960
2015-06-26 21:38:41.899 IOSLauncher[8695:1586324] [debug] IOSGraphics: 640.0x960.0, 2.0
2015-06-26 21:38:42.008 IOSLauncher[8695:1586324] [debug] IOSGraphics: Display: ppi=326, density=2.0375
2015-06-26 21:38:42.183 IOSLauncher[8695:1586324] [debug] IOSApplication: created
2015-06-26 21:38:42.213 IOSLauncher[8695:1586324] [debug] IOSPreferences: NSDictionary file written
2015-06-26 21:38:42.905 IOSLauncher[8695:1586324] [debug] IOSApplication: resumed
```

I'm aware of the deprecation warning, but that shouldn't be the problem here. The event log of Android Studio contains the following:
```
9:40:24 PM Gradle build finished with 1 warnings(s) in 2m 15s 469ms
9:40:27 PM Error running iOS Device: Unable to open debugger port (127.0.0.1:63707): java.net.SocketException "Socket closed"
9:41:15 PM Executing tasks: [launchIOSDevice]
```
Any ideas what to try next are welcome. Thank you,
Michael.

**Comment by badlogic** [comment]
Oh, your are launching via Gradle? For debugging in IDEA/Studio you need
the RoboVM IDEA plugin. Give that a try :)

**Comment by AgrarPirat** [comment]
Wow you're quick! Thank you very much!
I was just about to format the content of ```project.pbxproj```. Well, it seems like I can skip that.
RoboVM IDEA plugin 1.4.0 is installed. Ahm... please excuse the question, but where do I have to click to launch the app through the RoboVM IDEA plugin?

**Comment by badlogic** [comment]
See http://docs.robovm.com, there's a getting started video for the IDEA
plugin :)

**Comment by AgrarPirat** [comment]
Thank you!
