### ISSUE TITLE
Test dynamic framework signing and resource copying/processing

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#1030]

**Comment by alexitelman** [comment]
Hi guys,

Is this done or are there more issues?
Can I try?

**Comment by badlogic** [comment]
Should be done, give the latest nightly a try!

**Comment by alexitelman** [comment]
Seems to work with your sample, but not with our code. Here's the RoboVM console output:

[INFO] Stopping all Interface Builder integrator daemons
[INFO] Stopping all Interface Builder integrator daemons
[DEBUG] Loading default RoboVM config properties file: /Users/admin/muvix/audioPlayer-ios/robovm.properties
[DEBUG] Loading default RoboVM config file: /Users/admin/muvix/audioPlayer-ios/robovm.xml
[INFO] Building executable in /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7
[INFO] Installation of app in /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7
[INFO] classpath entry: /Users/admin/muvix/build/classes/production/muvix
[INFO] classpath entry: /Users/admin/muvix/audioPlayer/build/intermediates/classes/debug
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/org.joda/joda-convert/1.7/57c2432e54dc40f871f55295c676b22672713602/joda-convert-1.7.jar
[INFO] classpath entry: /Users/admin/muvix/common/java/build/resources/main
[INFO] classpath entry: /Users/admin/muvix/service/applicationServices/build/classes/main
[INFO] classpath entry: /Users/admin/muvix/screen/screenServer/build/intermediates/classes/debug
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.1.2/2d23694879c2c12f125dac5076bdfd5d771cc4cb/logback-core-1.1.2.jar
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.4/4216af16d38465bbab0f3dff8efa14204f7a399a/commons-codec-1.4.jar
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/com.rabbitmq/amqp-client/3.4.2/e3c6ec521a1906ed5403bf64c7903762ea2d0984/amqp-client-3.4.2.jar
[INFO] classpath entry: /Users/admin/muvix/build/classes/production/tests
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/18.0/cce0823396aa693798f8882e64213b1772032b09/guava-18.0.jar
[INFO] classpath entry: /Users/admin/muvix/systemtests/systemtestsfeatures/build/classes/main
[INFO] classpath entry: /Users/admin/muvix/service/domain/build/classes/main
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.0.2/211ffb697056079e6693316b2c9bb91e348ae9c4/jackson-annotations-2.0.2.jar
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/xmlpull/xmlpull/1.1.3.1/2b8e230d2ab644e4ecaa94db7cdedbc40c805dfa/xmlpull-1.1.3.1.jar
[INFO] classpath entry: /Users/admin/muvix/common/android/build/intermediates/classes/debug
[INFO] classpath entry: /Users/admin/muvix/build/classes/production/screen
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.2/b316e9737eea25e9ddd6d88eaeee76878045c6b2/logback-classic-1.1.2.jar
[INFO] classpath entry: /Users/admin/muvix/tests/mockscreen/build/classes/main
[INFO] classpath entry: /Users/admin/muvix/build/classes/production/service
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/3.0.0/5871fb60dc68d67da54a663c3fd636a10a532948/jsr305-3.0.0.jar
[INFO] classpath entry: /Users/admin/muvix/tests/GenericAndroidDriver/build/intermediates/classes/debug
[INFO] classpath entry: /Users/admin/muvix/common/java/build/classes/main
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-math3/3.4.1/3ac44a8664228384bc68437264cf7c4cf112f579/commons-math3-3.4.1.jar
[INFO] classpath entry: /Users/admin/muvix/service/dataAccess/build/classes/main
[INFO] classpath entry: /Users/admin/muvix/build/classes/production/contrib
[INFO] classpath entry: /Users/admin/muvix/audioPlayer-ios/build/resources/main
[INFO] classpath entry: /Users/admin/muvix/common/audioClient/build/resources/main
[INFO] classpath entry: /Users/admin/muvix/service/controller/build/classes/main
[INFO] classpath entry: /Users/admin/muvix/service/technicalServices/build/classes/main
[INFO] classpath entry: /Users/admin/muvix/systemtests/systemtestsframework/build/classes/main
[INFO] classpath entry: /Users/admin/muvix/build/classes/production/common
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.3.4/c9478f1871de4c9cf723e5d497a14c7ad274a50b/jackson-databind-2.3.4.jar
[INFO] classpath entry: /Users/admin/muvix/service/contract/build/resources/main
[INFO] classpath entry: /Users/admin/muvix/contrib/jsonrpc4j/build/classes/main
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.3.4/801fecfb8baf0ba5296e2d2ea0664f72b0761b9a/jackson-core-2.3.4.jar
[INFO] classpath entry: /Users/admin/muvix/service/contract/build/classes/main
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.0.2/9ba85dcbe273e1e3265c8d599569a71f1b81b75b/jackson-core-2.0.2.jar
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.9/872ec63b41181e29ad5a3723f1417356e2d2c0f2/slf4j-api-1.7.9.jar
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.0.2/396dee63d12d9ebc29b65bbc8cb4881525fa1da2/jackson-databind-2.0.2.jar
[INFO] classpath entry: /Users/admin/muvix/queueservices/build/classes/main
[INFO] classpath entry: /Users/admin/muvix/build/classes/production/systemtests
[INFO] classpath entry: /Users/admin/muvix/screen/screenLib/build/classes/main
[INFO] classpath entry: /Users/admin/muvix/contrib/exoplayer/build/intermediates/classes/debug
[INFO] classpath entry: /Users/admin/muvix/service/webadmin/build/classes/main
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.4/e9b3863fd9c8a273ceed4a7fae10f40bb10a2328/httpcore-4.4.jar
[INFO] classpath entry: /Users/admin/muvix/contrib/exoplayerlib/build/intermediates/classes/debug
[INFO] classpath entry: /Users/admin/muvix/queueservices/build/resources/main
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.3.0/f5e853a20b60758922453d56f9ae1e64af5cb3da/jackson-annotations-2.3.0.jar
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/org.ocpsoft.prettytime/prettytime/3.2.7.Final/4b216ebcf284752a40e11c39c2ea62bc45528c33/prettytime-3.2.7.Final.jar
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-collections4/4.0/da217367fd25e88df52ba79e47658d4cf928b0d1/commons-collections4-4.0.jar
[INFO] classpath entry: /Users/admin/muvix/common/audioClient/build/classes/main
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/joda-time/joda-time/2.7/5599707a3eaad13e889f691b3af78c8c03842195/joda-time-2.7.jar
[INFO] classpath entry: /Users/admin/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore-nio/4.4/b50d3f8d9c30133d6f1d8b5a90ea952c2c5b2c9d/httpcore-nio-4.4.jar
[INFO] classpath entry: /Users/admin/muvix/contrib/jsonrpc4j/build/resources/main
[INFO] classpath entry: /Users/admin/muvix/audioPlayer-ios/build/classes/main
[INFO] classpath entry: /Users/admin/muvix/screen/screenLib/build/resources/main
[INFO] Using SDK boot classpath
[INFO] Cleaning output dir /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7
[WARNING] Classpath entry /Users/admin/muvix/build/classes/production/muvix does not exist
[WARNING] Classpath entry /Users/admin/muvix/build/classes/production/tests does not exist
[WARNING] Classpath entry /Users/admin/muvix/systemtests/systemtestsfeatures/build/classes/main does not exist
[WARNING] Classpath entry /Users/admin/muvix/build/classes/production/screen does not exist
[WARNING] Classpath entry /Users/admin/muvix/build/classes/production/service does not exist
[WARNING] Classpath entry /Users/admin/muvix/build/classes/production/contrib does not exist
[WARNING] Classpath entry /Users/admin/muvix/build/classes/production/common does not exist
[WARNING] Classpath entry /Users/admin/muvix/build/classes/production/systemtests does not exist
[WARNING] Classpath entry /Users/admin/muvix/service/webadmin/build/classes/main does not exist
[DEBUG] Compiling classes using 8 threads
[DEBUG] Compiled 0 classes in 7.67 seconds
[INFO] Linking 5388 classes (ios thumbv7 release)
[DEBUG] 56429 methods out of 56429 included in the executable
[DEBUG] Building executable /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main
[DEBUG] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main -arch armv7 -Wl,-filelist,/Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/objects0 -L /Users/admin/.robovm-sdks/robovm-1.4.1-SNAPSHOT/lib/vm/ios/thumbv7 -ObjC -exported_symbols_list /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Users/admin/muvix/audioPlayer-ios/frameworks -miphoneos-version-min=8.0 -stdlib=libstdc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk -lrobovm-bc -force_load /Users/admin/.robovm-sdks/robovm-1.4.1-SNAPSHOT/lib/vm/ios/thumbv7/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -liconv -lsqlite3 -framework Foundation -framework AudioToolbox -framework AVFoundation -framework QuartzCore -framework CoreGraphics -framework AudioPlayer -framework MobileCoreServices -framework UIKit -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks
[DEBUG] Linked 5388 classes in 4.54 seconds
[INFO] Build done
[INFO] Launching executable
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/boot/robovm-rt.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/boot/robovm-rt-sources.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes0.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/joda-convert-1.7.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes2.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes3.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/logback-core-1.1.2.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/commons-codec-1.4.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/amqp-client-3.4.2.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/guava-18.0.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes8.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/jackson-annotations-2.0.2.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/xmlpull-1.1.3.1.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes11.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/logback-classic-1.1.2.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes13.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/jsr305-3.0.0.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes15.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes16.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/commons-math3-3.4.1.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes18.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes19.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes20.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes21.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/jackson-databind-2.3.4.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes23.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/jackson-core-2.3.4.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes25.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/jackson-core-2.0.2.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/slf4j-api-1.7.9.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/jackson-databind-2.0.2.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes29.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes30.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes31.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/httpcore-4.4.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes33.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/jackson-annotations-2.3.0.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/prettytime-3.2.7.Final.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/commons-collections4-4.0.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes37.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/joda-time-2.7.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/httpcore-nio-4.4.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/classes40.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/robovm-cacerts-full.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/robovm-cocoatouch-sources.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/robovm-cocoatouch.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/robovm-objc-sources.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/robovm-objc.jar
[DEBUG] Creating stripped archive file /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/lib/boot/robovm-cacerts-full.jar
[DEBUG] Copying resource /Users/admin/muvix/audioPlayer-ios/resources/PlugIns/MuvixToday.appex/_CodeSignature/CodeResources to /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/PlugIns/MuvixToday.appex/_CodeSignature
[DEBUG] Copying resource /Users/admin/muvix/audioPlayer-ios/resources/PlugIns/MuvixToday.appex/embedded.mobileprovision to /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/PlugIns/MuvixToday.appex
[DEBUG] Copying resource /Users/admin/muvix/audioPlayer-ios/resources/PlugIns/MuvixToday.appex/Info.plist to /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/PlugIns/MuvixToday.appex
[DEBUG] Copying resource /Users/admin/muvix/audioPlayer-ios/resources/PlugIns/MuvixToday.appex/MainInterface.storyboardc/Info.plist to /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/PlugIns/MuvixToday.appex/MainInterface.storyboardc
[DEBUG] Copying resource /Users/admin/muvix/audioPlayer-ios/resources/PlugIns/MuvixToday.appex/MainInterface.storyboardc/M4Y-Lb-cyx-view-S3S-Oj-5AN.nib to /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/PlugIns/MuvixToday.appex/MainInterface.storyboardc
[DEBUG] Copying resource /Users/admin/muvix/audioPlayer-ios/resources/PlugIns/MuvixToday.appex/MainInterface.storyboardc/UIViewController-M4Y-Lb-cyx.nib to /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/PlugIns/MuvixToday.appex/MainInterface.storyboardc
[DEBUG] Copying resource /Users/admin/muvix/audioPlayer-ios/resources/PlugIns/MuvixToday.appex/MuvixToday to /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/PlugIns/MuvixToday.appex
[DEBUG] Copying resource /Users/admin/muvix/audioPlayer-ios/resources/PlugIns/README.txt to /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/PlugIns
[DEBUG] Copying framework AudioPlayer from /Users/admin/muvix/audioPlayer-ios/frameworks/AudioPlayer.framework to /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app
[DEBUG] Copying resource /Users/admin/muvix/audioPlayer-ios/frameworks/AudioPlayer.framework/Assets.car to /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/Frameworks/AudioPlayer.framework
[DEBUG] Copying resource /Users/admin/muvix/audioPlayer-ios/frameworks/AudioPlayer.framework/AudioPlayer to /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/Frameworks/AudioPlayer.framework
[ERROR] Couldn't start application
org.apache.commons.exec.ExecuteException: Command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/Frameworks/AudioPlayer.framework/AudioPlayer -remove i386 -remove x86_64 -output /Users/admin/muvix/audioPlayer-ios/robovm-build/tmp/ios-device/ios/thumbv7/Main.app/Frameworks/AudioPlayer.framework/AudioPlayer.tmp' failed (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.lipoRemoveArchs(ToolchainUtil.java:298)
	at org.robovm.compiler.target.AbstractTarget$2.processFile(AbstractTarget.java:294)
	at org.robovm.compiler.config.Resource.walk(Resource.java:447)
	at org.robovm.compiler.config.Resource.walk(Resource.java:454)
	at org.robovm.compiler.config.Resource.walk(Resource.java:415)
	at org.robovm.compiler.target.AbstractTarget.copyDynamicFrameworks(AbstractTarget.java:275)
	at org.robovm.compiler.target.AbstractTarget.doInstall(AbstractTarget.java:377)
	at org.robovm.compiler.target.ios.IOSTarget.prepareLaunch(IOSTarget.java:384)
	at org.robovm.compiler.target.ios.IOSTarget.doLaunch(IOSTarget.java:525)
	at org.robovm.compiler.target.AbstractTarget.launch(AbstractTarget.java:404)
	at org.robovm.compiler.AppCompiler.launchAsync(AppCompiler.java:795)
	at org.robovm.idea.running.RoboVmRunProfileState.executeRun(RoboVmRunProfileState.java:67)
	at org.robovm.idea.running.RoboVmRunProfileState.startProcess(RoboVmRunProfileState.java:111)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
	at org.robovm.idea.running.RoboVmRunner.doExecute(RoboVmRunner.java:79)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.RunProfileStarter.execute(RunProfileStarter.java:39)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:219)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:146)
	at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:186)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by alexitelman** [comment]
I guess it has something to do with your build script, which we are not using in our code.
What we are doing is regular build in the xcode UI and then copy the product .framework to the robovm project.
I tried doing the same for your sample and I got the same error.
I guess some step is missing in the regular xcode build process?
Can I add it in the UI or do I have to do it in a script?
Thanks.

**Comment by badlogic** [comment]
The script of the sample compiles for all CPU architectures so the
framework works on both the simulator and devices. Xcode only compiles for
either the sim or the device. The RoboVM build fails because it assumes a
fat binary from which it tries to remove the simulator slices when
compiling for the device (and app store submission, because Apple would
reject an app with frameworks containing code for the simulator). The
simulator slices aren't there in your case, because you compile for the
device via Xcode.

I'll fix this up so we detect of there are simulator slices to be removed.
I'll let you know when this is done (an hour from now).

**Comment by alexitelman** [comment]
Cool, I assumed it was something like that.

**Comment by alexitelman** [comment]
Can I have a new build in the nightlies please?

**Comment by badlogic** [comment]
I just triggered one :) Should be ready in 20-30 minutes from now. Let me know if this works for you.

**Comment by badlogic** [comment]
Great success?

**Comment by alexitelman** [comment]
UBER SUCCESS!

You are the BEST!
Thank you so much for all your effort and help and passion.

**Comment by badlogic** [comment]
Great, consider supporting our efforts :)

**Comment by alexitelman** [comment]
I think the code signing of the frameworks also needs to be done in the IPA creation code.
See issue #1062
