### ISSUE TITLE
Dynamic frameworks not working on real devices - need to sign the dylibs

### ISSUE THREAD

**Issue by alexitelman** [robovm/robovm#1034]
Following issue #451 - when trying to use a dynamic framework on a real device this error occurs in the RoboVM console:

[ERROR] Couldn't start application
org.robovm.libimobiledevice.LibIMobileDeviceException: ApplicationVerificationFailed
	at org.robovm.libimobiledevice.util.AppLauncher$1.error(AppLauncher.java:1001)
	at org.robovm.libimobiledevice.Callbacks.callInstproxyCallback(Callbacks.java:64)

**Comment by ntherning** [comment]
@badlogic already created an issue for this problem, see #1030.

**Comment by alexitelman** [comment]
Strange because he asked me to open a new issue, in the #451 conversation
