### ISSUE TITLE
Hidden symbol warnings shouldn't be logged if we have specified them to be unhidden

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#1036]
These currently pollute the console with 100+ warnings like:
```
[ WARN] ld: warning: cannot export hidden symbol _kGAIVersionField from /Users/xxxx
```

It makes sense to remember the user to specify them in `<unhideSymbols>` but once we unhide them that warning should be gone.

**Comment by ntherning** [comment]
Do you have an <exportedSymbols> section that matches those hidden symbols
as well? That would explain why you see the warning.

**Comment by BlueRiverInteractive** [comment]
Oh I'm dumb. So we don't need the <exportedSymbols> if we have them under <unhideSymbols> ?

**Comment by BlueRiverInteractive** [comment]
I should just RTF Docs :p    Nevermind, issue "fixed"!
