### ISSUE TITLE
New XCode Build Process Without Developer License

### ISSUE THREAD

**Issue by erasmospunk** [robovm/robovm#1038]
[James Peters wrote](https://groups.google.com/forum/#!topic/robovm/-uOCjsGMo2o):

>With the XCode 7 Beta it is now possible to build and run applications on a device without a developer license. 
>
>I'm just wondering if or when it will be possible to do so. 
>
>I currently get this error, which was expected.

>java.lang.IllegalArgumentException: No provisioning profile found matching signing identity 'iPhone Developer: james...@gmail.com (********)' and app bundle ID 'jameslfc19.testapp'

**Comment by erasmospunk** [comment]
:+1:

**Comment by ntherning** [comment]
This already works but it involves creating an Xcode project with the same bundle identifier as the ID of your RoboVM app. We will document the process. See robovm/robovm-docs#91 for the docs issue.
