### ISSUE TITLE
Xcode 7 support

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#1041]

**Comment by badlogic** [comment]
After another OS X update this doesn't work again.

**Comment by badlogic** [comment]
Needed to delete the runtimes in `/Library/Developer/CoreSimulator/Profiles/Runtimes`.

**Comment by tobium** [comment]
same error with 1.5.1-SNAPSHOT: "java.lang.UnsatisfiedLinkError: Library 'objc' not found"

**Comment by badlogic** [comment]
Can you provide more info?

**Comment by tobium** [comment]
I tried to create simple JavaFX app with javafxports gradle plugin (patched by ntherning to use robovm 1.5.1-SNAPSHOT) with Xcode 7. RoboVM compiles and installs the app on my iPhone 5S with iOS9 (beta), but after start it crashs with the following exception: 

17:35:10.623 [DEBUG] [org.gradle.api.Task] [100%] Install complete
17:35:13.254 [DEBUG] [org.gradle.api.Task] Debug server port: 56449
17:35:13.257 [DEBUG] [org.gradle.api.Task] Remote app path: /private/var/mobile/Containers/Bundle/Application/120C42C1-824B-4AC5-B884-4833CB9AD20C/MyApp.app
17:35:13.257 [DEBUG] [org.gradle.api.Task] Launching app...
17:35:13.257 [DEBUG] [org.gradle.api.Task] App Path: /private/var/mobile/Containers/Bundle/Application/120C42C1-824B-4AC5-B884-4833CB9AD20C/MyApp.app
17:35:14.601 [QUIET] [system.out] java.lang.UnsatisfiedLinkError: Library 'objc' not found
17:35:14.602 [QUIET] [system.out] 	at org.robovm.rt.bro.Runtime.getHandle(Runtime.java)
17:35:14.602 [QUIET] [system.out] 	at org.robovm.rt.bro.Runtime.loadLibrary(Runtime.java)
17:35:14.602 [QUIET] [system.out] 	at org.robovm.rt.bro.Bro.bind(Bro.java)
17:35:14.602 [QUIET] [system.out] 	at org.robovm.objc.ObjCRuntime.<clinit>(ObjCRuntime.java)
17:35:14.602 [QUIET] [system.out] 	at org.robovm.objc.ObjCObject.<clinit>(ObjCObject.java)

**Comment by badlogic** [comment]
Could you create and run a non-JavaFX RoboVM app on your iOS 9 device? This
way we can rule out issues with your development tool setups.

**Comment by tobium** [comment]
Yo, I tried "BatteryStatus" but with same result:

09:52:49.275 [INFO] [org.gradle.api.Task] [100%] Install complete
09:52:53.902 [INFO] [org.gradle.api.Task] Looking up developer disk image for iOS version 9.0 (13A4305g) in /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport
09:52:53.919 [INFO] [org.gradle.api.Task] Copying developer disk image /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/9.0 (13A4305g)/DeveloperDiskImage.dmg to device
09:52:54.637 [INFO] [org.gradle.api.Task] Mounting developer disk image
09:52:55.105 [INFO] [org.gradle.api.Task] Debug server port: 49331
09:52:55.108 [INFO] [org.gradle.api.Task] Remote app path: /private/var/mobile/Containers/Bundle/Application/28155513-9570-46B8-A224-672C29E4D3F1/BatteryStatus.app
09:52:55.109 [INFO] [org.gradle.api.Task] Launching app...
09:52:55.109 [INFO] [org.gradle.api.Task] App Path: /private/var/mobile/Containers/Bundle/Application/28155513-9570-46B8-A224-672C29E4D3F1/BatteryStatus.app
09:52:55.941 [QUIET] [system.out] java.lang.UnsatisfiedLinkError: Library 'objc' not found
09:52:55.942 [QUIET] [system.out] 	at org.robovm.rt.bro.Runtime.getHandle(Runtime.java)
09:52:55.942 [QUIET] [system.out] 	at org.robovm.rt.bro.Runtime.loadLibrary(Runtime.java)
09:52:55.942 [QUIET] [system.out] 	at org.robovm.rt.bro.Bro.bind(Bro.java)
09:52:55.942 [QUIET] [system.out] 	at org.robovm.objc.ObjCRuntime.<clinit>(ObjCRuntime.java)
09:52:55.942 [QUIET] [system.out] 	at org.robovm.objc.ObjCObject.<clinit>(ObjCObject.java)
09:52:55.944 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':BatteryStatus:launchIOSDevice'
09:52:55.944 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :BatteryStatus:launchIOSDevice (Thread[Daemon worker Thread 3,5,main]) completed. Took 35.746 secs.
09:52:55.944 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 3,5,main]] finished, busy: 35.746 secs, idle: 0.001 secs
09:52:55.944 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskGraphExecuter] Timing: Executing the DAG took 35.748 secs

**Comment by badlogic** [comment]
I can reproduce the issue, working on it. If all goes well, it should be
fixed EOD. Thanks for reporting!
