### ISSUE TITLE
hi, there is bug of UIActionSheet

### ISSUE THREAD

**Issue by tianqiujie** [robovm/robovm#1050]
UIActionSheet mActionSheet = new UIActionSheet("分享到", new MyUIActionSheetDelegate() , "取消", "", "微信好友", "微信朋友圈");	mActionSheet.showIn(UIApplication.getSharedApplication().getKeyWindow().getRootViewController().getView());

//errors
java.lang.ClassCastException: com.mygdx.game.IOSLauncher$7 cannot be cast to org.robovm.objc.ObjCObject
	at org.robovm.objc.ObjCObject$Marshaler.protocolToNative(ObjCObject.java)
	at org.robovm.apple.uikit.UIActionSheet.$m$initWithTitle$delegate$cancelButtonTitle$destructiveButtonTitle$otherButtonTitles$(Native Method)
	at org.robovm.apple.uikit.UIActionSheet.init(UIActionSheet.java)
	at org.robovm.apple.uikit.UIActionSheet.<init>(UIActionSheet.java)
	at com.mygdx.game.IOSLauncher.share(IOSLauncher.java)

test in iOS 7.1

**Comment by BlueRiverInteractive** [comment]
Your `MyUIActionSheetDelegate` must extend from NSObject. You can also use `UIActionSheetDelegateAdapter` instead, if you want.

**Comment by tianqiujie** [comment]
UIActionSheet mActionSheet = new UIActionSheet("分享到", new UIActionSheetDelegateAdapter(){
				@Override
				@NotImplemented("actionSheet:clickedButtonAtIndex:")
				public void clicked(UIActionSheet actionSheet,
						@MachineSizedSInt long buttonIndex) {
					
					LOG.V("buttonIndex = " + buttonIndex);
					if (buttonIndex == 0) {
						shareToPy();
					}else if(buttonIndex == 1){
						shareToCircle();
					}
					
					super.clicked(actionSheet, buttonIndex);
				}
			}, "取消", null, "微信好友", "微信朋友圈");
			
			mActionSheet.showIn(UIApplication.getSharedApplication().getKeyWindow().getRootViewController().getView());


OK, now I use the UIActionSheetDelegateAdapter, but the method named "clicked" is not called.

**Comment by BlueRiverInteractive** [comment]
Try to remove the `@NotImplemented("actionSheet:clickedButtonAtIndex:")` annotation.

**Comment by tianqiujie** [comment]
OK, I got the problem, just change the @NotImplemented to @Mechod, it can work now. And Does any XXXDelegate has a adapter named XXXDelegateAdapter in cocoatouch?

**Comment by BlueRiverInteractive** [comment]
Great! Yes, normally all delegates have a adapter class.

**Comment by tianqiujie** [comment]
OK, thank you very much
