### ISSUE TITLE
CocoaPods dependency in framework is not loaded

### ISSUE THREAD

**Issue by alexitelman** [robovm/robovm#1051]
Hi Robovm guys,

I ran into a little snag, I tried to add a dependency to my swift framework using CocoaPods, but it can't seem to find it when I run the app with Robovm.
I saw that in my framework it links against a framework called Pods_MyFramework, and not directly against the dependency..
So I tried adding Pods_MyFramework to the robovm xml but it didn't help.

The error I'm getting is the same as before when it couldn't find my framework, only about the dependency framework:

Library not loaded: @rpath/MyDependency.framework/MyDependency
Referenced from: <...MyFramework>
Reason: image not found

**Comment by badlogic** [comment]
Please provide a sample project for us to dissect.

**Comment by alexitelman** [comment]
Framework with CocoaPods:
https://drive.google.com/file/d/0BwxZsZfwfINWRm1TZ3NWamxHUmM/view

Robovm App with this framework:
https://drive.google.com/file/d/0BwxZsZfwfINWZFZNOFNZVzZnZk0/view

to build it:

cd to FrameworkWithPods
run pod install
open FrameworkWithPods.xcworkspace (not project)
build it
copy product FrameworkWithPods.framework to AppWithFrameworkWithPods/frameworks
build AppWithFrameworkWithPods (IntelliJ)

when I run the app I get this error in the console: (simulator)

dyld: Library not loaded: @rpath/SDWebImage.framework/SDWebImage
  Referenced from: /Users/admin/Library/Developer/CoreSimulator/Devices/26A2E1E9-0087-4E25-89D8-15FC9B0BDB6C/data/Containers/Bundle/Application/888D6CD6-D141-4563-8A76-B10BD85821F6/Main.app/Frameworks/FrameworkWithPods.framework/FrameworkWithPods
  Reason: image not found

**Comment by alexitelman** [comment]
Found the solution after writing this sample :-)
Basically I found the missing SDWebImage.framework in the Pods project products and copied it to the robovm project manually, then I added a build phase for this:

In the previously mentioned CocoaPods xcode workspace:
1. Select the "Pods" project on the left
2. Select the Pods-FrameworkWithPods-SDWebImage target
3. Go to Build Phases tab on the right
4. Click the little '+' button on the top and select 'New Copy Files Phase'
5. Fill these details in it:
    Destination: Absolute Path
    Path: $(PROJECT_DIR)/../../AppWithFrameworkWithPods/frameworks
6. In the bottom list click the little '+' sign at the bottom and select SDWebImage.framework under Products

Build Xcode, Build Robovm, Enjoy :-)

**Comment by badlogic** [comment]
Cool! We have some plans for cocopods, but nothing concrete yet. We
currently can't follow the dependency graph of a pod, so your somewhat
manual method has to do for now i'm afraid.

Let us know when you're done building your product, would love to feature
it in our app gallery!
