### ISSUE TITLE
"IllegalArgumentException: Type Mismatch" in Icmp when compiling EclipseLink

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#1061]
The exception:
```
java.lang.IllegalArgumentException: Type mismatch
	at org.robovm.compiler.llvm.Icmp.<init>(Icmp.java:35)
	at org.robovm.compiler.MethodCompiler.if_(MethodCompiler.java:1243)
	at org.robovm.compiler.MethodCompiler.doCompile(MethodCompiler.java:415)
	at org.robovm.compiler.AbstractMethodCompiler.compile(AbstractMethodCompiler.java:77)
	at org.robovm.compiler.ClassCompiler.compileMethod(ClassCompiler.java:1395)
	at org.robovm.compiler.ClassCompiler.method(ClassCompiler.java:1429)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:756)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:292)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:305)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:388)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:448)
	at org.robovm.eclipse.internal.AppCompilerThread.doCompile(AppCompilerThread.java:60)
	at org.robovm.eclipse.internal.AppCompilerThread.run(AppCompilerThread.java:66)
```

The exception is thrown when compiling line 240 of [org.eclipse.persistence.eis.EISAccessor.basicExecuteCall()](http://grepcode.com/file/repo1.maven.org/maven2/org.eclipse.persistence/eclipselink/2.6.0/org/eclipse/persistence/eis/EISAccessor.java#240)

This is due to a Jimple `IfStmt` with a condition which compares a `Local` with a `NullType` to a constant with an `IntType`:

```
        null_type n0, n1, n2, n3;
...
     label59:
        if n2 != 0 goto label62;
/*240*/
```

Here's the complete Jimple for the `basicExecuteCall()` method: https://gist.github.com/ntherning/02ddb13568803b9b9ece.

To me it looks like `z11` corresponds to the `transactionCommitted` variable and that this one should be referenced by the `IfStmt` rather than `n2` which seems to correspond to the `Record input` local variable. Locking at the local variable table `transactionCommitted` and `input` share the same local variable slot so this could be what confuses Soot.

**Comment by badlogic** [comment]
DIsabling web merging produces the same error. Here's the Jimple without merging webs: https://gist.github.com/badlogic/2a4a29b90b2f53741540

The original bytecode is correct obviously, that leaves us with the bytecode -> jimple conversiong going wrong.

**Comment by badlogic** [comment]
In fact, the jimple produced with and without web merging is exactly the same.

**Comment by badlogic** [comment]
The Jimple before any optimizations are applied ((PackManager.v().getPack("jb").apply(jb);`): https://gist.github.com/badlogic/57623af6dc04bd3da4d5

Relevant lines:
```
235: $stack0 = 1
235: l8 = $stack0
236: $stack0 = l0
236: virtualinvoke $stack0.<org.eclipse.persistence.eis.EISAccessor: void decrementCallCount()>()
237: $stack0 = 1
237: l9 = $stack0
238: goto [?= $stack0 = l5]
238: $stack0 := @caughtexception
238: l10 = $stack0
240: $stack0 = l8
240: if $stack0 != 0 goto $stack0 = l9
```
l8 (`transactionCommitted`)is assigned properly in line 235 and also used in line 240 for the conditional.

After the LocalSplitter is applied in `JimpleBodyPack` without merging of webs we get: https://gist.github.com/badlogic/0ce6771933344588a589

Relevant lines:
```
235: $stack0#107 = 1
235: l8#6 = $stack0#107
236: $stack0#108 = l0
236: virtualinvoke $stack0#108.<org.eclipse.persistence.eis.EISAccessor: void decrementCallCount()>()
237: $stack0#109 = 1
237: l9#5 = $stack0#109
238: goto [?= $stack0#120 = l5#2]
238: $stack0#110 := @caughtexception
238: l10#3 = $stack0#110
240: $stack0#111 = l8
240: if $stack0#111 != 0 goto $stack0#115 = l9
```

Now line 240 uses `l8` for the conditional, but it should actually use `l8#6` instead (``transactionCommitted`), which is assigned in line 235.

It appears that the constructed webs are incorrect.

**Comment by badlogic** [comment]
Starting from the non-splitted version of the method: https://gist.github.com/badlogic/16a587e6c3045fbddf76

Then following the local splitter when creating webs for `l8`. Set a breakpoint in `LocalSplitter:109`, using the conditional `body.getMethod().getName().contains("basicExecuteCall") && lo.toString().equals("l8")`. This allows you to trace all web creations of l8. The first couple of webs are all correct.

For the usage of `l8` for `transactionCommitted` the uses list is empty! Here's the Java code:

```
227        boolean transactionCommitted = false;
228        boolean countDecremented = false;
229        // This is in separate try block to ensure that the real exception is not masked by the close exception.
230        try {
231            interaction.close();
232            if (autoCommit) {
233                commitTransaction(session);
234            }
235            transactionCommitted = true;
236            decrementCallCount();
237            countDecremented = true;
238        } catch (ResourceException exception) {
239            try {
240                if (!transactionCommitted) {
241                    if (autoCommit) {
242                        commitTransaction(session);
243                    }                
244                }
245            } catch (Exception ignore) {
246                // Ignore error to avoid masking real exception.
247            }
248            try {
249                if (!countDecremented) {
250                    decrementCallCount();
251                }
252            } catch (Exception ignore) {
253                // Ignore error to avoid masking real exception.
254            }
255            throw EISException.resourceException(exception, this, session);
256        }
257
```

`transactionCommited` is initialized in line 227:

```
227: $stack0 = 0
227: l8 = $stack0
```

It is then reassigned but not used with the try block in line 235:

```
235: $stack0 = 1
235: l8 = $stack0
```

When the `LocalSplitter` gets the uses of `l8` it is returned an empty list, which is kinda correct as its not used in the try block of the code. However, it is used in the catch block of the code, which doesn't seem to be taken into account.

**Comment by badlogic** [comment]
`SimpleLocalUses` can't find any definitions for the use of `l8` for line 240. It uses a `LocalDefs` instance which is supposed to calculate the possible definitions for every use. That fails to calculate the definition of the use of `l8` appearently.

**Comment by badlogic** [comment]
Live locals info per unit as generated in `SmartLocalDefs:76`: https://gist.github.com/badlogic/04bf5b0a112035ee6e15

Relevant info for lines 227-240:
```
227: $stack0 = 0, [l7, l0, l3, l4, l5, $stack0]
227: l8 = $stack0, [l7, l0, l3, l4, l5]
228: $stack0 = 0, [l7, l0, l3, l4, l5, $stack0]
228: l9 = $stack0, [l7, l0, l3, l4, l5]
231: $stack0 = l4, [l7, l0, l3, l5, $stack0]
231: interfaceinvoke $stack0.<javax.resource.cci.Interaction: void close()>(), [l7, l0, l3, l5]
232: $stack0 = l7, [l0, l3, l5, $stack0]
232: if $stack0 == 0 goto $stack0 = 1, [l0, l3, l5]
233: $stack0 = l0, [l0, l3, l5, $stack0]
233: $stack1 = l3, [l0, $stack1, l5, $stack0]
233: virtualinvoke $stack0.<org.eclipse.persistence.eis.EISAccessor: void commitTransaction(org.eclipse.persistence.internal.sessions.AbstractSession)>($stack1), [l0, l5]
235: $stack0 = 1, [l0, l5, $stack0]
235: l8 = $stack0, [l0, l5]
236: $stack0 = l0, [l5, $stack0]
236: virtualinvoke $stack0.<org.eclipse.persistence.eis.EISAccessor: void decrementCallCount()>(), [l5]
237: $stack0 = 1, [l5, $stack0]
237: l9 = $stack0, [l5]
238: goto [?= $stack0 = l5], [l5]
238: $stack0 := @caughtexception, [l7, l8, l9, l0, l3, $stack0]
238: l10 = $stack0, [l7, l10, l8, l9, l0, l3]
240: $stack0 = l8, [l7, l10, l9, l0, l3, $stack0]
240: if $stack0 != 0 goto $stack0 = l9, [l7, l10, l9, l0, l3]
```

That looks OKish, except for l8 never being live inside the try block.

**Comment by badlogic** [comment]
`LocalDefsAnalysis` results as generated in `SmartLocalDefs:88`: https://gist.github.com/badlogic/faaa7fc0669fbddd0245

For every "after" live local of a unit, `LocalDefsAnalysis` returns the possible units that defined these live locals based on the DU chain and control flow. `SmartLocalDefs` then proceeds to store only those defines for the unit that are in this analysis result. These results are what's being returned by `SmartLocalDefs#getDefsOfAt()` in line 121 in `SimpleLocalUses:21`. 

`LocalSplitter` and subsequent transformation passes think there's no definition for `l8`/`transactionCommited` in line 240 of the original source code being compiled, because `LocalDefsAnalysis` is incorrectly.

All of this is really just the effect of `l8` not being a live local to any statement within the try block because it's only defined there, but never used.

**Comment by badlogic** [comment]
Tried to boil it down unsuccessfully, `LocalDefsAnalysis` successfully reconstructs the defs of `transactionCommited`/`l4`

```
public Object basicExecuteCall(Call call, AbstractRecord translationRow, AbstractSession session) throws Exception {
    	{
    		Object o = null;
    		System.out.println(o);
    	}

        boolean transactionCommitted = false;
        boolean countDecremented = false;
        // This is in separate try block to ensure that the real exception is not masked by the close exception.
        try {
        	excp();
            transactionCommitted = true;
            excp();
            countDecremented = true;
        } catch (Exception exception) {
            try {
                if (!transactionCommitted) { 
                    System.out.println(session);
                }
            } catch (Exception ignore) {
                // Ignore error to avoid masking real exception.
            }            
        } 
        return null;
    }
    
    public void excp() throws Exception {
    	throw new Exception();
    }
```

```
57: l0 := @this: com.biss.robovm.el.test.Main
57: l1 := @parameter0: org.eclipse.persistence.queries.Call
57: l2 := @parameter1: org.eclipse.persistence.internal.sessions.AbstractRecord
57: l3 := @parameter2: org.eclipse.persistence.internal.sessions.AbstractSession
57: $stack0 = null
57: l4 = $stack0
58: $stack0 = <java.lang.System: java.io.PrintStream out>
58: $stack1 = l4
58: virtualinvoke $stack0.<java.io.PrintStream: void println(java.lang.Object)>($stack1)
61: $stack0 = 0
61: l4 = $stack0
62: $stack0 = 0
62: l5 = $stack0
65: $stack0 = l0
65: virtualinvoke $stack0.<com.biss.robovm.el.test.Main: void excp()>()
66: $stack0 = 1
66: l4 = $stack0
67: $stack0 = l0
67: virtualinvoke $stack0.<com.biss.robovm.el.test.Main: void excp()>()
68: $stack0 = 1
68: l5 = $stack0
69: goto [?= $stack0 = null]
69: $stack0 := @caughtexception
69: l6 = $stack0
71: $stack0 = l4
71: if $stack0 != 0 goto $stack0 = null
72: $stack0 = <java.lang.System: java.io.PrintStream out>
72: $stack1 = l3
72: virtualinvoke $stack0.<java.io.PrintStream: void println(java.lang.Object)>($stack1)
74: goto [?= $stack0 = null]
74: $stack0 := @caughtexception
74: l7 = $stack0
78: $stack0 = null
78: return $stack0
```

**Comment by badlogic** [comment]
Turns out it was an issue with dependencies not being present on the classpath. Watch out for phantom class log info in the compile log. That indicates you don't have all the necessary bits on the classpath.
