### ISSUE TITLE
Unrecognized bytecode instruction: 168

### ISSUE THREAD

**Issue by yujinfu** [robovm/robovm#1069]
Hi,
 I use javax.mail-1.5.4.jar in robovm ,but it told me that "Unrecognized bytecode instruction: 168 " when compling com.sun.mail.imap.IMAPFolder class 
I don't know how to solve this problem, anybody meet such problem? please help me thanks very much.

**Comment by yujinfu** [comment]
Hi ,
I have solved this problem, I download the source code , unzip and then regenerate the jar file by myself , and then add into the robovm project build path
and it work .

I don't know what't the diffrence between the jar I download from https://java.net/projects/javamail/pages/Home and that one I extract the source code
and then export .
Niklas, could you please tell me? or anybody knows the deep quesion ,please help me ,thanks very much.

**Comment by ntherning** [comment]
There's already an issue for the "Unrecognized bytecode instruction: 168" problem: #471

The reason why it works when you recompile the JAR file from source is that newer Java compilers don't generate class files containing the JSR byte code instruction (which has the number 168). The original JAR file was compiled with an old compiler which still used JSRs. The JSR bytecode is deprecated.

**Comment by yujinfu** [comment]
thanks very much
