### ISSUE TITLE
Dynamic framework not loaded on iOS 7 with RoboVM

### ISSUE THREAD

**Issue by alexitelman** [robovm/robovm#1071]
It's loaded successfully on iOS 8 with RoboVM and on iOS 7 with Xcode, but not in iOS 7 with RoboVM,
This is the error I'm getting:

```
java.lang.ExceptionInInitializerError
	at com.mycompany.myapp.MyViewController.clicked(MyViewController.java)
	at com.mycompany.myapp.MyViewController.$cb$clicked(MyViewController.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
	at com.mycompany.myapp.Main.main(Main.java)
Caused by: org.robovm.objc.ObjCClassNotFoundException: MyFramework.MyClass
	at org.robovm.objc.ObjCClass.getByType(ObjCClass.java)
	at com.mycompany.myapp.MyClass.<clinit>(MyClass.java)
	... 5 more
```

Here's a sample project to reproduce it:
https://drive.google.com/file/d/0BwxZsZfwfINWLUMzSHNfSTBMUVE/view?usp=sharing

TestIos7 is an Xcode project that has two targets: MyFramework framework and TestIos7 app which has this framework embedded.
robovm-ios7-test is a robovm project which also uses the same MyFramework framework.
From the xcode project it works, but from the robovm project it crashes with the above error when clicking the button.
With iOS 8 both work well.

**Comment by badlogic** [comment]
MyFramework.MyClass

Can you remove MyFramework from the CustomClass annotation and try again?
It's still weird the dyn framework works at all on iOS 7, it shouldn't.

**Comment by alexitelman** [comment]
I guess you mean NativeClass annotation.
I tried that, it didn't help:

```
java.lang.ExceptionInInitializerError
	at com.mycompany.myapp.MyViewController.clicked(MyViewController.java)
	at com.mycompany.myapp.MyViewController.$cb$clicked(MyViewController.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
	at com.mycompany.myapp.Main.main(Main.java)
Caused by: org.robovm.objc.ObjCClassNotFoundException: MyClass
	at org.robovm.objc.ObjCClass.getByType(ObjCClass.java)
	at com.mycompany.myapp.MyClass.<clinit>(MyClass.java)
	... 5 more
```

**Comment by badlogic** [comment]
Right, my heads currently somewhere else.

Ay, the framework isn't loaded by dyld then, which is why i said dynamic
libs don't worl on iOS 7. Not sure how you made it work with Xcode. All
sources on the web i saw say that you can't submit iOS 7 plus dyn libs to
the app store.

**Comment by alexitelman** [comment]
Well you can see the xcode project that I attached

**Comment by badlogic** [comment]
Right. Here's the official stance of Apple concerning iOS 7 plus embedded
frameworks:
http://stackoverflow.com/questions/29682272/embedded-frameworks-ios-8/29982816#29982816

You may be able to make it work during development, but you won't be able
to submit to the app store.

**Comment by alexitelman** [comment]
I know this is their official stance, but de-facto it just works. You can
see in the same thread you sent that people succeeded.
And I also uploaded our app and it didn't get rejected..

**Comment by badlogic** [comment]
I understand that. But we already have our hands full supporting the
official way of soing things. Adding support for officially unsupported
things is something we can't afford at the moment.

If people rely on such unsupported features in their apps, and Apple breaks
them down the road, we'll be the ones who have to take the blame.

**Comment by alexitelman** [comment]
Maybe we can come up with a way that robovm can statically embed our
framework in the executable?
Again, if it's a matter of priority maybe we can find some solution for
that financially?

**Comment by badlogic** [comment]
You can't statically embed a dynamic framework, such as the Swift runtime
libraries, in an executable.

As for support for dynamic frameworks on iOS 7 in RoboVM, i'll consult with
the other folks. I'd suggest we focus on fixing dynamic libraries for iOS
8+ first.

After that we can still evaluate the feasibility of dynamic frameworks on
iOS 7. Just to manage expectations, it's unlikely we are going to support
that for the reason outlined in my previous message.

**Comment by alexitelman** [comment]
I'm finishing-up the fix for 8+ now.. so you can start evaluating 7 already :-)

**Comment by badlogic** [comment]
I'm sorry, that's not how it works :) We'll have to wait for Niklas to
return from his vaccation first. :)

**Comment by alexitelman** [comment]
When is that?

**Comment by alexitelman** [comment]
I propose we investigate the following line of thought:

An app written in Xcode for iOS 7 can contain Swift code.
So the swift binary products can be embedded in the executable.
What if we look for a way to embed of swift binary products in the app created by robovm? Similarily to the process you are doing with java I guess. 

This way we avoid the need for a dynamic framework which is not supported in iOS 7.

Does that make sense?

**Comment by alexitelman** [comment]
Hey, can you point me to where are you linking against the swift core libs during the build process?
I'm trying a use an .a file (static lib) produced from swift code instead of a dynamic lib, but it fails because it can't find the swift libs:
```
[DEBUG] Building executable /Users/admin/Desktop/robovm-ios7-test/robovm-build/tmp/ios-simulator/ios/x86_64/Main
[DEBUG] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/admin/Desktop/robovm-ios7-test/robovm-build/tmp/ios-simulator/ios/x86_64/Main -arch x86_64 -Wl,-filelist,/Users/admin/Desktop/robovm-ios7-test/robovm-build/tmp/ios-simulator/ios/x86_64/objects0 -L /Users/admin/.robovm-sdks/robovm-1.5.1-SNAPSHOT/lib/vm/ios/x86_64 -ObjC -exported_symbols_list /Users/admin/Desktop/robovm-ios7-test/robovm-build/tmp/ios-simulator/ios/x86_64/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -fPIC -mios-simulator-version-min=7.0 -stdlib=libstdc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -lrobovm-bc -force_load /Users/admin/.robovm-sdks/robovm-1.5.1-SNAPSHOT/lib/vm/ios/x86_64/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -liconv -lsqlite3 -framework Foundation -force_load /Users/admin/Desktop/robovm-ios7-test/libs/libswiftMyFramework.a -framework MobileCoreServices -framework UIKit -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks
[ERROR] ld: library not found for -lswiftCoreImage for architecture x86_64
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app
org.apache.commons.exec.ExecuteException: Command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/admin/Desktop/robovm-ios7-test/robovm-build/tmp/ios-simulator/ios/x86_64/Main -arch x86_64 -Wl,-filelist,/Users/admin/Desktop/robovm-ios7-test/robovm-build/tmp/ios-simulator/ios/x86_64/objects0 -L /Users/admin/.robovm-sdks/robovm-1.5.1-SNAPSHOT/lib/vm/ios/x86_64 -ObjC -exported_symbols_list /Users/admin/Desktop/robovm-ios7-test/robovm-build/tmp/ios-simulator/ios/x86_64/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -fPIC -mios-simulator-version-min=7.0 -stdlib=libstdc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -lrobovm-bc -force_load /Users/admin/.robovm-sdks/robovm-1.5.1-SNAPSHOT/lib/vm/ios/x86_64/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -liconv -lsqlite3 -framework Foundation -force_load /Users/admin/Desktop/robovm-ios7-test/libs/libswiftMyFramework.a -framework MobileCoreServices -framework UIKit -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks' failed (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:371)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:229)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:332)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:223)
	at org.robovm.compiler.Linker.link(Linker.java:424)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:461)
	at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
```
Where do you link agains them in the case of a framework?

**Comment by alexitelman** [comment]
Currently trying this way:
1. Create a static lib from our swift code using this Ruby script:
https://github.com/SnapKit/SnapKit/issues/12
2. Add the lib under the <libs> in robovm.xml
3. In the robovm compiler add linking to the swift libs during linkage like what xcode does, like this:
In AbstractTarget.java in build(...) add: 
        ccArgs.add("-L");
        ccArgs.add(getSwiftDir().getAbsolutePath());
getSwiftDir is extracted from the copySwiftLibs method.

Will let you know if it works.

**Comment by alexitelman** [comment]
And also need to make sure that the swift libs are copied into the app even if there are no custom dynamic frameworks...

**Comment by alexitelman** [comment]
Seams to be working on a simulator. Will test on a real device on Sunday.

**Comment by alexitelman** [comment]
Doesn't work on a real device yet, don't merge the pull request yet.
