### ISSUE TITLE
I want to build a simple bynary helloworld to run without jvm

### ISSUE THREAD

**Issue by lipangit** [robovm/robovm#1076]
but package the source code can not use bin/robovm

Official Website just tell us how to build ios in java .
see blow

![c76979f1-e27e-469d-a9d0-aedd9264cf92](https://cloud.githubusercontent.com/assets/2038071/8774229/721e05c8-2f0e-11e5-8a53-50ef28ffd7e5.png)

**Comment by ntherning** [comment]
You need to check out the [robovm-dist](https://github.com/robovm/robovm-dist) repo as well on the same level as the [robovm](https://github.com/robovm/robovm) repo and build it:

```
git clone git@github.com:robovm/robovm.git
mvn -f robovm/pom.xml clean install
git clone git@github.com:robovm/robovm-dist.git
mvn -f robovm-dist/pom.xml clean install
```

You should now be able to run the `robovm/bin/robovm` script.

However, if you're not going to hack on the RoboVM source code I recommend you use our prebuilt packages instead: http://robovm.com.

Please use the Google Group for further discussions of this topic: https://groups.google.com/group/robovm.
