### ISSUE TITLE
org.robovm.apple.coregraphics.CGGradientDrawingOptions should include Both enum

### ISSUE THREAD

**Issue by mseddon** [robovm/robovm#1077]
It is perfectly valid to invoke `CGContextDrawLinearGradient` with a bit mask `(kCGGradientDrawsAfterEndLocation | kCGGradientDrawsBeforeStartLocation)`, but the bindings do not support this, which makes things fairly awkward for me currently.

**Comment by mseddon** [comment]
Sheepishly closed since I see I can fix this currently with the Bits superclass :)

**Comment by ntherning** [comment]
For reference this is the way to do this with our bindings:

```java
  ctx.drawLinearGradient(gradient, startPoint, endPoint, CGGradientDrawingOptions.with(
      CGGradientDrawingOptions.AfterEndLocation, CGGradientDrawingOptions.BeforeStartLocation));
```
