### ISSUE TITLE
Default method handling in Java8Test incorrect

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#1083]
A couple of tests have been disabled in Java8Test due to incorrect default method handling. Search for `RoboVM Note` in `Java8Test`

**Comment by ntherning** [comment]
IIUC method resolution when there are multiple default method implementations of a particular method in the interface hierarchy of a class is undefined. See [JVMS 5.4.3.3](http://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.3.3). Still we should try to figure out how the RI does it and make sure we do it the same way. The trick is to get the itables for a class in the correct order. This happens in `ClassCompiler.collectInterfaces()`. We currently visit the interfaces depth-first. Judging from the `Java8Test` tests it could be that the RI does it breadth-first.

**Comment by ntherning** [comment]
Hmmm, `ClassCompiler.collectInterfaces()` is passed a `HashSet` which it adds the interfaces to. That makes the order in which `ClassCompiler.collectInterfaces()` visits the interfaces irrelevant since `HashSet` doesn't preserve the insertion order. :-)

**Comment by ntherning** [comment]
Figured out that `ClassCompiler.collectInterfaces()` has nothing to do with this issue but rather the method resolution in `TrampolineCompiler.resolveMethod(SootClass clazz, String name, String desc)`. If I change the while at the end to look in the interfaces of a class breadth-first two of the tests are fixed. The `testSuperThisRefsInDefenderMethod`test still fails with

```
There was 1 failure:
1) testSuperThisRefsInDefenderMethod(org.robovm.rt.lambdas.Java8Test)
org.junit.ComparisonFailure: expected:<...un() in i: foo() in [j].
> but was:<...un() in i: foo() in [i].
>
	at org.junit.Assert.assertEquals(Assert.java:115)
```
