### ISSUE TITLE
Gradle 2.5 RoboVM 1.5.0 project error

### ISSUE THREAD

**Issue by n3o59hf** [robovm/robovm#1090]
Creating LibGDX project (tried iOS only project) and changing  gradle/wrapper/gradle-wrapper.properties distribution URL to point to 2.5 release results in failed build.

Could be reproduced with minimal project too: https://dl.dropboxusercontent.com/u/9603723/ios_test.tar.gz
(to reproduce, use `./gradlew tasks` and change `gradle/wrapper/gradle-wrapper.properties` line
`distributionUrl=http\://services.gradle.org/distributions/gradle-2.4-all.zip`
to
`distributionUrl=http\://services.gradle.org/distributions/gradle-2.5-all.zip`
)

OS:
Ubuntu 15.04 3.19.0-23-generic x86_64

Java:
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

```
elviss@dragon:~/tmp/my-gdx-game-ios-test2$ ./gradlew tasks
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/elviss/tmp/my-gdx-game-ios-test2/build.gradle' line: 34

* What went wrong:
A problem occurred evaluating root project 'my-gdx-game-ios-test2'.
> Failed to apply plugin [id 'robovm']
   > Could not generate a proxy class for class org.robovm.gradle.tasks.IPhoneSimulatorTask.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.266 secs
```

Log with debug and stacktrace here: http://pastebin.com/raw.php?i=ZENushCr

**Comment by badlogic** [comment]
This has been fixed in the latest nightly. Thanks for reporting!
