### ISSUE TITLE
JavaScriptCore bindings?

### ISSUE THREAD

**Issue by emanuelpalm** [robovm/robovm#1094]
Any word on when one could expect to be able to use JavaScriptCore conveniently via RoboVM?

Looking at the list [here](https://github.com/robovm/robovm/wiki/CocoaTouch-bindings-status), it seems that there aren't many CocoaTouch bindnings missing. Could it be expected in 1.6.0, or 1.7.0?

Thanks!

**Comment by badlogic** [comment]
We have it on our radar but can't give an ETA at the moment. It won't make
the 1.6 release this week. For 1.7 our focus is on iOS 9 bindings, it may
make it in.

**Comment by emanuelpalm** [comment]
Alright! Thanks alot.
