### ISSUE TITLE
Changing code in an unused scala method changes an unrelated method.

### ISSUE THREAD

**Issue by mseddon** [robovm/robovm#1095]
This appears to be a potentially serious issue relating to incorrect code generation in robovm, or incorrect optimization lower down at the llvm level.

I have two scala methods:

Method 1:
```scala
def drawImage(image: Image, dx: Float, dy: Float): Unit
```

and

Method 2:
```scala
def drawImage(image: Image, sx: Float, sy: Float, sWidth: Float, sHeight: Float, dx: Float, dy: Float, dWidth: Float, dHeight: Float): Unit
```

Method 1 is never called in my code, but Method 2 is.  When I change Method 1's code, the behaviour of Method 2 is affected.

When Method 1 is 'correctly' implemented with some translate/scale operations, I get the first image (a button with a white highlight on the bottom left
- the transformation in Method 2 is not being applied.

![without-comments](https://cloud.githubusercontent.com/assets/4021991/9025914/464cbbc6-3911-11e5-9d14-8f518d3f3c82.png)

When Method 1 has it's transformation commented out, I get the second image- a button with the white highlighting on the top left- the transformation is correctly being applied.

![with-comments](https://cloud.githubusercontent.com/assets/4021991/9025916/53692786-3911-11e5-819d-011b8246c5b8.PNG)

I have a test case online. To reproduce, you must first install sbt (http://www.scala-sbt.org/index.html), check out https://github.com/roboscala/sbt-robovm (commit c7d493a774).

First, install `sbt-robovm`.  Clone and within the directory, type `sbt publishLocal`

Next, `git clone git@github.com:mseddon/robovm-issue.git`.  The top two commits demonstrate the problem.

https://github.com/mseddon/robovm-issue/commit/5b991d1fe5799c471b9b72917fa780bd5063d435

Simply checkout either revision and run with:

```sbt ios/simulator```

While there is a Prelude.log (which just defers onto Foundation.log) statement in the function which was changed, it is never emitted, demonstrating this code was not (and actually cannot) be hit, the behaviour of the drawImage called com/example/Canvas.scala is being affected.

I apologise for the non-trivial example project, (This example was initially spread out over several projects already, so it's taken a while to get it to this stage).

**Comment by badlogic** [comment]
Thanks for the excellent issue description. We'll look into it asap.

**Comment by mseddon** [comment]
No problem- I have also diffed the md5 sums of the classfiles and disassembled them, but I can't find much of interest.  Will continue studying to ensure it's not happening upstream at scalac's end, but I don't think so.  If I find any more results will post here, if you need anything just ask! :)

**Comment by mseddon** [comment]
I have got the example down far smaller <200 loc.  As seen here:

https://github.com/mseddon/robovm-issue/tree/minimize-example

I notice that actually I *was* calling the drawImage routine but for some reason it was being muffled, in ImageImpl line 21.  This is a basic initialization for the image gfx context, which marks the image as changed..  However, subsequent calls to the second drawImage method request .peer, which reloaded the image and *flips* it. (doh).  Buried under a lot of code I foolishly blamed robovm :)

I am confused why that log wasn't being emitted but perhaps it was being lost during app startup.

It is probably worth verifying this, but I think actually I found it.  Closing issue! (horay!)

**Comment by badlogic** [comment]
Great! Btw, there will be an (unofficial) update to stb-robovm soonish by
@ajhager, make sure to give that a try when it's released!

**Comment by mseddon** [comment]
Excellent news! Guys, this stuff is rocking my world, and I hope to be releasing some early preview of neat stuff built on this in the next month or so on github. Thanks again, and sorry for causing a panic :)

**Comment by badlogic** [comment]
We never panic :)
