### ISSUE TITLE
java.lang.NullPointerException at AudioBufferList.getBuffer

### ISSUE THREAD

**Issue by yujinfu** [robovm/robovm#1098]
Hi,
I use AudioUnit to do audio sample , I set audioUnit's render callback ,
and after callback invoke , I want to get data from AudioBufferList, no mather I use 
audioBufferList.getBuffer(0).getDataAsShortArray() or copy to a new AudioBufferList, it always 
tell me the exception below and my app crash. 
Is that a bug in Struct<T> class, I saw Struct<T> class's _sizeOf() method always return 0??? so if I use copy or some other operation  that call _sizeOf() first will always copy zero length.

please help me ,thanks very much.

java.lang.NullPointerException
	    	at org.robovm.rt.bro.ptr.Ptr.getValue(Ptr.java)
	    	at org.robovm.apple.coreaudio.AudioBufferList.getBuffer(AudioBufferList.java)
	    	at com.isaigu.soft.intelligentcar.voice.offline.IOSVoiceRecognizer$AudioTask$1.onRender(IOSVoiceRecognizer.java)
	    	at org.robovm.apple.audiounit.AudioUnit.cbRender(AudioUnit.java)
	    Unhandled exception (probably in a @Callback method called from native code): java/lang/NullPointerException

**Comment by ntherning** [comment]
Please post a minimal test app which reproduces this issue and we'll try to look into it.

**Comment by mpr90** [comment]
I have run across the same issue as I was porting a [simple tone generator app](http://www.cocoawithlove.com/2010/10/ios-tone-generator-introduction-to.html) from Objective C to Java/RoboVM. I have put a simple test app in [GitHub](https://github.com/mpr90/robovm-test/tree/master/audiounit-tonegenerator) that reproduces the problem. I am using RoboVM 1.8.0.201509162239.

When the app is run, there is a button to click that is supposed to start audio playback of a simple tone. However, clicking the button produces the following error:
```
java.lang.NullPointerException
	at org.robovm.rt.bro.ptr.Ptr.getValue(Ptr.java)
	at org.robovm.rt.bro.ptr.Ptr.get(Ptr.java)
	at org.robovm.apple.coreaudio.AudioBufferList.getBuffer(AudioBufferList.java)
	at MyViewController$1.onRender(MyViewController.java)
	at org.robovm.apple.audiounit.AudioUnit.cbRender(AudioUnit.java)
Unhandled exception (probably in a @Callback method called from native code): java/lang/NullPointerException
```

**Comment by ntherning** [comment]
Ok, I have looked into this and found the bug in our bindings. With the patch below the test app works as intended (at least if it's supposed to give a very annoying tone :-) ).

Dom, please update the bindings to look something like what we have in the diff below.

``` diff
diff --git a/cocoatouch/src/main/java/org/robovm/apple/coreaudio/AudioBufferList.java b/cocoatouch/src/main/java/org/robovm/apple/coreaudio/AudioBufferList.java
index edca24c..d94803d 100644
--- a/cocoatouch/src/main/java/org/robovm/apple/coreaudio/AudioBufferList.java
+++ b/cocoatouch/src/main/java/org/robovm/apple/coreaudio/AudioBufferList.java
@@ -56,7 +56,7 @@ import org.robovm.apple.corefoundation.*;
         if (index >= getBufferCount()) {
             throw new ArrayIndexOutOfBoundsException(index);
         }
-        return getBuffers0().next(index).get();
+        return getBuffers0().next(index);
     }
     public AudioBufferList setBuffer(int index, AudioBuffer buffer) {
         return setBuffer(index, buffer.getHandle());
@@ -65,28 +65,22 @@ import org.robovm.apple.corefoundation.*;
         if (index >= getBufferCount()) {
             throw new ArrayIndexOutOfBoundsException(index);
         }
-        getBuffers0().next(index).set(handle);
+        getBuffers0().next(index).update(Struct.toStruct(AudioBuffer.class, handle));
         return this;
     }
     public AudioBuffer[] getBuffers() {
-        int count = getBufferCount();
-        AudioBuffer[] array = new AudioBuffer[count];
-        AudioBuffer.AudioBufferPtr ptr = getBuffers0();
-        for (int i = 0; i < count; i++) {
-            array[i] = ptr.next(i).get();
-        }
-        return array;
+        return getBuffers0().toArray(getBufferCount());
     }
     public AudioBufferList setBuffers(AudioBuffer[] buffers) {
         this.setNumberBuffers(buffers.length);
-        getBuffers0().set(buffers);
+        getBuffers0().update(buffers);
         return this;
     }
     /*<members>*/
     @StructMember(0) protected native int getNumberBuffers();
     @StructMember(0) protected native AudioBufferList setNumberBuffers(int numberBuffers);
-    @StructMember(1) protected native AudioBuffer.AudioBufferPtr getBuffers0();
-    @StructMember(1) protected native AudioBufferList setBuffers0(AudioBuffer.AudioBufferPtr buffers0);
+    @StructMember(1) protected native @Array(1) AudioBuffer getBuffers0();
+    @StructMember(1) protected native AudioBufferList setBuffers0(@Array(1) AudioBuffer buffers0);
     /*</members>*/
     /*<methods>*//*</methods>*/
 }
```

**Comment by ntherning** [comment]
This has now been fixed. Try the next nightly build if you wanna try it out before we release 1.10. http://docs.robovm.com/advanced-topics/nightlies.html
