### ISSUE TITLE
NIO http issue

### ISSUE THREAD

**Issue by dukeboard** [robovm/robovm#111]
Hello,

I face an issue on OSX 10.8 with a compiled version of RoboVM (0.2.0).
I use an http url to download a file. The compiled version don't throw any error but the file is corrupted. I use NIO code to download the file.

ReadableByteChannel rbc = Channels.newChannel(url.openStream());
                FileOutputStream fos = new FileOutputStream(runtimeFile);
                fos.getChannel().transferFrom(rbc, 0, 1 << 24);
                fos.close();

As a workaround I use the old IO version which work fine.

InputStream in = url.openStream();
                FileOutputStream fos = new FileOutputStream(runtimeFile);
                byte data[] = new byte[1024];
                int count;
                while ((count = in.read(data, 0, 1024)) != -1) {
                    fos.write(data, 0, count);
                }
                in.close();
                fos.close();

**Comment by ntherning** [comment]
Hi, this issue is very old and we haven't heard of anyone else having similar issues. Please retry your code with the latest version of RoboVM and create a new issue if the problem still occurs.
