### ISSUE TITLE
ClassLoader.getResource() may return null when it shouldn't

### ISSUE THREAD

**Issue by aalmiray** [robovm/robovm#1114]
Related to the application used for testing in #1106 and #1107. Invoking `classLoader.getResource(value)` where `value` is a fully qualified classname available in the classpath (verified it works on the desktop version) results in a `null` value instead of the URL pointing to the resource. Sample code follows, it should be reproducible with a trivial testcase

        LOG.error("" + getClass().getClassLoader().getResource("java/util/regex/Matcher.class"));
        LOG.error("" + getClass().getClassLoader().loadClass("java.util.regex.Matcher"));

results on desktop:

    jar:file:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/rt.jar!/java/util/regex/Matcher.class
    class java.util.regex.Matcher

results on iOS simulator:

    null
    class java.util.regex.Matcher

Is it possible to locate class resources via URL inside RoboVM? If so, what would be the way to make it happen?

**Comment by aalmiray** [comment]
Possibly related to https://github.com/robovm/robovm/issues/169

**Comment by badlogic** [comment]
RoboVM does not package .class files with the native executable, meaning
they won't be available in the classpath. What's the use case?

**Comment by aalmiray** [comment]
Current use case is to avoid a class loading miss if the class is not available in the classpath. I can workaround this problem but I'm afraid the behavior will be missed anyway. If this is a restriction by design of RoboVM them we're good, it's just a matter of documenting behavior and let developers know. If it isn't then I'd appreciate if the behavior can be fulfilled.

**Comment by aalmiray** [comment]
For completeness sake, this is the code that's affected  https://github.com/griffon/griffon/blob/development/subprojects/griffon-core/src/main/java/org/codehaus/griffon/runtime/util/DefaultCompositeResourceBundleBuilder.java#L76-L93 basically line 78

    URL resource = getResourceAsURL(fileName, CLASS_SUFFIX);

**Comment by badlogic** [comment]
It's a soft restriction as including the full classpath in the app bundle
would bloat it. As such we will likely not 'fix' it but document it as you
suggested. As an aside: it would be a lot slower to check for the existance
of the .class file than to check if loading the class fails. A RoboVM app
has a static list of classes embedded in the executable binary, class
loading lookups are as fast as they can be.

**Comment by aalmiray** [comment]
Thanks. I'll add a check to the code if running on iOS, that way I can skip the URL check.

**Comment by ntherning** [comment]
I opened a new issue in the robovm-docs repo for documenting this: robovm/robovm-docs#84. Closing this issue in favor of that one.
