### ISSUE TITLE
IntelliJ IDEA runs gradle build on every letter change in the source

### ISSUE THREAD

**Issue by alexitelman** [robovm/robovm#1119]
After upgrading Robovm intellij plugin to 1.6 intellij started to run gradle build after every letter I type in the source. 
This is very annoying and slows down development.
If I disable the robovm plugin it stops doing this.

Tested on MacBook Pro..

**Comment by badlogic** [comment]
I'll add a setting to disable this in the IDEA preferences.

**Comment by badlogic** [comment]
Added a simple setting accessible in the preferences of IntelliJ IDEA:

![http://sht.tl/gIEYCI](http://sht.tl/gIEYCI)

Should be available in the next snapshot build.
