### ISSUE TITLE
The RoboVM library builder has not been licensed for this machine

### ISSUE THREAD

**Issue by enricopersiani** [robovm/robovm#1138]
Last week I was able to compile the sample project MyJavaFrameork using the `mvn compile robovm:install` command as suggested in the README file. 

As of today, when I try to invoke the above command, the mojo execution terminates with the following error message:

`[ERROR] Failed to execute goal org.robovm:robovm-maven-plugin:1.6.0:install (default-cli) on project robovm-samples-dynamiclib: Execution default-cli of goal org.robovm:robovm-maven-plugin:1.6.0:install failed: The RoboVM library builder has not been licensed for this machine. Please see http://www.robovm.com/buy for licensing options. -> [Help 1]`

I tried to delete both my maven repository cache and the robovm cache, but I still get the above error.

**Comment by badlogic** [comment]
That's because your trial likely expired. To use the linrary builder you'll
need a license, as outlined in our blog post where we introduced the
feature.

**Comment by enricopersiani** [comment]
Sorry for have bothered you with this issue, I can assure you that I tried to find any such bit of information on your website. Can you please share a link to that blog post, so that I can study any other limitation not present on the licensing page, please?

**Comment by keywind** [comment]
My trial not expired and this happens always

**Comment by vergaramikel** [comment]
@keywind same to me.

**Comment by tomfisher** [comment]
@keywind same to me.

**Comment by ntherning** [comment]
Please contact support@robovm.com for licensing issues.
