### ISSUE TITLE
IntelliJ/RoboVM Studio keeps resetting the Java language level back to 1.6

### ISSUE THREAD

**Issue by NoahAndrews** [robovm/robovm#1140]
For me, this occurs in a Gradle-based cross-platform project (not libGDX). I'm using Retrolambda for the Android side, so I want all modules to have a language level of 1.8. 

I've tried fixing this by setting sourceCompatibility and targetCompatibility at the root level of each module's build.gradle file (below where the java plugin is applied), but that doesn't work. The only module where that does seem to work is the android module, but its compatibility levels are set in a different point in the module's build.gradle file, as follows.

```java
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
 ```

I'm not sure if this is a bug or just a misconfiguration, but I'm not the only one with this problem. http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=15477

**Comment by badlogic** [comment]
I've seen this behaviour as well, it appears to be a bug in the way IDEA handles the model described by a Gradle build file.

**Comment by badlogic** [comment]
This has been fixed and will be available in the 1.8 release. We now also apply RetroLambda to the `core` and `android` project of a cross-platform project by default. Thanks for reporting!

**Comment by NoahAndrews** [comment]
Awesome!!!! Is there/will be a 1.7.1 preview release?

**Comment by badlogic** [comment]
You can get a snapshot build from here in a few hours from now: http://download.robovm.org/nightlies/robovm-studio/robovm-studio-1.7.1-SNAPSHOT.dmg

**Comment by NoahAndrews** [comment]
This bug still isn't fixed for me in the 1.7.1 snapshot.

**Comment by BillMalkin** [comment]
I've just installed RoboVM 1.8 and have got this same problem. It's fine with android but the language level reverts to 6 for ios, core and my module.

**Comment by badlogic** [comment]
The release next week fixes it. IDEA doesn't seem to properly parse the
source/target language settings in the Gradle file. We force this setting
in the plugin.

**Comment by NoahAndrews** [comment]
Thank you! 
On Oct 18, 2015 1:18 PM, Mario Zechner <notifications@github.com> wrote:The release next week fixes it. IDEA doesn't seem to properly parse the
source/target language settings in the Gradle file. We force this setting
in the plugin.

**Comment by noblemaster** [comment]
I just updated my RoboVM plugin to the latest version 1.11.0 and had the same happen but with everything set to language level 1.8. All modules are set to language level 1.8 even those that don't have a gradle-build. For the rest I have source compatibility set to 1.7 which seems to have been completely ignored.

Can the RoboVM just use the project settings as default if the exact configuration cannot be determined?

**Comment by ItsHarper** [comment]
The latest version of Gradle claims to fix this problem!
https://docs.gradle.org/2.12/release-notes
