### ISSUE TITLE
Error creating project RoboVm Studio and Intellij idea

### ISSUE THREAD

**Issue by jymen** [robovm/robovm#1152]
when creating a new project I got a "Failed to find build tools version 23.0.0" message in both RoboVm studio and Intellij idea plugin ; Cleaning cache + cleaning $HOME/Library/preferences stuff does not fix the problem.
Installing last RoboVM studio nightly build does not fix the problem either.

![screen shot 2015-09-13 at 13 14 13](https://cloud.githubusercontent.com/assets/644653/9852292/c962715a-5afd-11e5-80cb-89de4e18b0b3.png)

**Comment by badlogic** [comment]
Sorry for this. The next nightly has this fixed! Thanks for reporting.
