### ISSUE TITLE
RoboVmStudio(EAP) Nightly does not identify the Android SDK on fresh install

### ISSUE THREAD

**Issue by jymen** [robovm/robovm#1154]
Hi , 
Using the nightly build and starting a fresh install when initially configuring environment the 'RoboVM android sdk setup panel' is displayed with a downloads sdk panel instead of showing the currently installed sdk location. 

To reproduce on MAC : 
1) move the $HOME/Library/preferences/RoboVmStudio1 directory to  trash 
2) Launch the RoboVmStudio EAP app and proceed with initial configuration

**Comment by badlogic** [comment]
That is on purpose, we are bundling our own Android SDK now, which will be
installed to ~/Library/RoboVM/android-sdk.

**Comment by jymen** [comment]
I Understand it's ok when installing either in Intellij/Idea or RoboVM but ... This may be confusing when installing the plugin in Android Studio which has already an Android SDK preset and as far as my test I correct I am requested to install a SDK as well ....

**Comment by obigu** [comment]
I agree the message is confusing. I confirm it happens with Android Studio with plugin as well, which is always meant to be used with an installed Android SDK.

**Comment by badlogic** [comment]
I'll change the install process to display a kind of warning, letting you chose your own SDK or reusing the one bundled with RoboVM. Thanks for reporting!

**Comment by badlogic** [comment]
This has been fixed. The default Android SDK in `~/Library/Android/sdk` will be used if available.
