### ISSUE TITLE
RoboVM Studio 1.8 wrong Android Gradle plugin version

### ISSUE THREAD

**Issue by n3o59hf** [robovm/robovm#1156]
Updated RoboVM studio from 1.7 to 1.8 and allowed it to download Android SDK and then created multi-platform project.
RoboVM Studio creates project using Gradle Wrapper version 2.6 but uses Android Gradle plugin version 1.1.1. From documentation (http://tools.android.com/tech-docs/new-build-system/version-compatibility ):
> Gradle plugin 1.0.0 - 1.1.3 works with Gradle 2.2.1 - 2.3.
> It does not work with Gradle 2.4+

Opening project with IntelliJ Idea results in Gradle error.

```
Error:Gradle 2.6 requires Android Gradle plugin 1.2.0 (or newer)  but project is using version 1.1.1.
Please use Android Gradle plugin 1.2.0 or newer.
```

**Comment by badlogic** [comment]
Thanks for reporting, this has already be fixed. You can give the EAP a try see http://download.robovm.org/files.html
