### ISSUE TITLE
NetworkInterface.isUp() always fail on 64-bit simulator

### ISSUE THREAD

**Issue by bubbleguuum** [robovm/robovm#1158]
Using robovm 1.8.0, Xcode 7, 64 bit simulator running iOS 9.
Any call to NetworkInterface.isUp() fails with SocketException, with all network interfaces:

Caused by: java.net.SocketException: Operation not supported on socket
	at java.net.NetworkInterface.getFlags(Native Method)
	at java.net.NetworkInterface.hasFlag(NetworkInterface.java:491)
	at java.net.NetworkInterface.isUp(NetworkInterface.java:453)

The 32-bit simulator works fine.

Might be related to #1137

**Comment by bubbleguuum** [comment]
It also fails on a real device compiling for arm64.

**Comment by voidstarfire** [comment]
Might be related too https://github.com/robovm/robovm/issues/1153

**Comment by bubbleguuum** [comment]
Still unfixed. Please consider looking into it as there seem to a number of issues with NetworkInterface compiled for arm64 while it works perfectly on 32-bit executables.

All NetworkInterface member functions that call NetworkInterface.getFlags() (supportsMulticast(), isLoopback(), ...)  fail with the same SocketException making this class unusuable on 64-bit.

**Comment by badlogic** [comment]
It looks like we need to find a replacement for `ioctl`. Android has since switches to reading files you find on Linux, can't do that on iOS.

**Comment by badlogic** [comment]
This should be fixed in the next snapshot build (ready in 3 hours from now).

**Comment by bubbleguuum** [comment]
Excellent! Thank you.
