### ISSUE TITLE
CFData never deallocated (async)

### ISSUE THREAD

**Issue by marcguilera** [robovm/robovm#1160]
Every time I use preferences.flush() on libGDX a CFData object is created on iOS. When I do that asynchronously this CFData object will never be deallocated which can lead to major memory leak overtime if an app flushes several times. 

I wrote this simple code on the onCreate() method in the ApplicationListener to reproduce it easily:

 	final Preferences prefs = new Gdx.app.getPreferences("prefs");
		for(int i=0;i<500;i++){
			HttpRequest req = new HttpRequest(HttpMethods.GET);
			req.setUrl("http://google.com");
			
			Gdx.net.sendHttpRequest(req, new HttpResponseListener(){

				@Override
				public void handleHttpResponse(HttpResponse httpResponse) {
					prefs.putString(Math.random()+"", "Lorem ipsum dolor sit amet, consectetur "
							+ "adipiscing elit, sed do eiusmod tempor incididunt ut labore et "
							+ "dolore magna aliqua. Ut enim ad minim veniam, quis nostrud "
							+ "exercitation ullamco laboris nisi ut aliquip ex ea commodo "
							+ "consequat. Duis aute irure dolor in reprehenderit in voluptate "
							+ "velit esse cillum dolore eu fugiat nulla pariatur. "
							+ "Excepteur sint occaecat cupidatat non proident, "
							+ "sunt in culpa qui officia deserunt mollit anim id est laborum.");
					prefs.flush();
				}

				@Override
				public void failed(Throwable t) {
				}

				@Override
				public void cancelled() {
				}
				
			});
			
		}
	}

For the record this only happens on async tasks, I've tried to just flush 500 times with a for on the main thread and the objects get created and deallocated after the loop. I'm running RoboVM 1.8 and GDX 1.7.0.

![screen shot 2015-09-21 at 3 39 38 pm](https://cloud.githubusercontent.com/assets/7732696/10023465/233a171e-6107-11e5-8e07-d5b498795826.png)

**Comment by jaman1020** [comment]
+1 I'm having this same issue, even with a fresh project

**Comment by ntherning** [comment]
My guess is that the reason for this is that there's no `NSAutoReleasePool` associated with that thread. My feeling is that the fix needs to go into the libGDX RoboVM backend somehow, rather than in RoboVM.

**Comment by BlueRiverInteractive** [comment]
I can confirm wrapping the `NSDictionary.write` inside an `NSAutoReleasePool` fixes the memory leak.

**Comment by badlogic** [comment]
Awesome, could you send a PR to libGDX?

**Comment by BlueRiverInteractive** [comment]
Sure!

**Comment by BlueRiverInteractive** [comment]
PR created: libgdx/libgdx#3869
