### ISSUE TITLE
Code signature verification failed: A signed resource has been added, modified, or deleted.

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#1165]
Installation of IPA fails on device with the following error in the console log:

```
Oct  1 12:29:00  installd[386] <Error>: 0x16e3eb000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 142: Failed to verify code signature of /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.Ap3V7g/extracted/Payload/App.app : 0xe8008017 (A signed resource has been added, modified, or deleted.)
Oct  1 12:29:00 e installd[386] <Error>: 0x16e3eb000 -[MIInstaller performInstallationWithError:]: Verification stage failed
```

**Comment by sicancode** [comment]
Hi - I had this exact same problem yesterday. Perhaps my experience will help.

It seems to happen whenever you reuse the robovm export location for IOSLauncher.ipa et al causes this error. Selecting a new fresh folder resolves this error... perhaps the export process should delete the assets explicitally or something is being cached somewhere.

I also found this problem when I was using illegal assets in the data directory of the ios folder. I had some temporarily files use to create the app assets ... I don't think it liked them at all.

Hopefully these will help you to solve this one.

**Comment by ntherning** [comment]
A user on the group suggested that the problem is that there's already an IPA or .app folder in the folder where we generate the IPA. I thought that we cleaned things up before. But maybe we don't.

**Comment by badlogic** [comment]
We appear to already delete the `.app` directory. Maybe delete files, due to files being in use?

**Comment by badlogic** [comment]
We never delete the IPA, we simply call zip on the IPA file:

```
 new Executor(Logger.NULL_LOGGER, "zip")
                .wd(tmpDir)
                .args("--symlinks", "--recurse-paths", ipaFile, ".")
                .exec();
```

To my understanding, this will simply add new files to the IPA, not delete and recreate it. Fixed by deleting the IPA if it exists.
