### ISSUE TITLE
Fail to start IOS emulator (any project with storyboards)

### ISSUE THREAD

**Issue by pelewin** [robovm/robovm#1170]
Hi, I cant's start any project that has storyboards:
Using last RoboVM IDE, JAVA 8, Gradle, MacOS El Capitan

22:41:24: Executing external task 'launchIPhoneSimulator'...
2015-10-12 22:44:06.823 ibtoold[2729:767516] -[IBUIViewControllerAutolayoutGuide shouldBeArchived]: unrecognized selector sent to instance 0x7fc125cbe680
:launchIPhoneSimulator FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launchIPhoneSimulator'.
> Failed to launch IOS Simulator

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 43.677 secs
Command '/Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --target-device iphone --target-device ipad --minimum-deployment-target 8.0 --output-partial-info-plist "/Users/dmitry/Documents/workspace RoboVM/RoboVMTest2/build/robovm.tmp/partial-plists/Main.storyboard_5269782981257488935.plist" --auto-activate-custom-fonts --output-format human-readable-text --compilation-directory "/Volumes/RoboVM RAM Disk/tmp/Users/dmitry/Documents/workspace RoboVM/RoboVMTest2/build/robovm.tmp/Main.app/Base.lproj" "/Users/dmitry/Documents/workspace RoboVM/RoboVMTest2/resources/Base.lproj/Main.storyboard"' failed (Exit value: 1)
22:44:09: External task execution finished 'launchIPhoneSimulator'.

**Comment by badlogic** [comment]
What version of Xcode are you using?

**Comment by pelewin** [comment]
It was 6 :)
Works good with the 7th.
Thank you.
