### ISSUE TITLE
CFBundleIdentifier

### ISSUE THREAD

**Issue by pelewin** [robovm/robovm#1171]
Hi,
If I try to launch an application on iphone with Info.plist.xml like this:
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
I'm getting an error
ERROR] Couldn't compile app
java.lang.IllegalArgumentException: No provisioning profile found matching signing identity 'iPhone Developer:' and app bundle ID '$(PRODUCT_BUNDLE_IDENTIFIER)'

If I pull my bundle id there everything works.
Shouldn't it be taken from robovm.properties?

**Comment by BlueRiverInteractive** [comment]
Your placeholder uses the wrong syntax. You have to use curly braces, like `${app.id}`.
