### ISSUE TITLE
IntelliJ is stuck on the 4-5 run and doesn't recover after restarting - Upgrade to Gradle 2.8

### ISSUE THREAD

**Issue by alexitelman** [robovm/robovm#1183]
After a few times of running the RoboVM project in IntelliJ, on the next run IntelliJ gets stuck and doesn't complete the run.
When killing it and restarting it gets stuck even earlier, on opening the project on the "Initializing Modules" stage.
What solves is it renaming the source folder, opening IntelliJ without selecting the project, disabling RoboVM plugin, restart IntelliJ, opening the project, enabling RoboVM plugin, restarting IntelliJ.

We are forced to do this every 4-5 runs, its very time consuming.
This started happening recently, since upgrading to 1.9 I think. Maybe 1.8.

Also, when running on a device and after that running on simulator (or vice versa) it also gets stuck.

**Comment by badlogic** [comment]
Are you using Gradle? If so, please disable the Gradle daemon and kill all
existing Java processes.

**Comment by alexitelman** [comment]
Right, this might work as well but its not a solution...

On Tuesday, 3 November 2015, Mario Zechner notifications@github.com wrote:

> Are you using Gradle? If so, please disable the Gradle daemon and kill all
> existing Java processes.
> On Nov 3, 2015 8:48 AM, "alexitelman" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > After a few times of running the RoboVM project in IntelliJ, on the next
> > run IntelliJ gets stuck and doesn't complete the run.
> > When killing it and restarting it gets stuck even earlier, on opening the
> > project on the "Initializing Modules" stage.
> > What solves is it renaming the source folder, opening IntelliJ without
> > selecting the project, disabling RoboVM plugin, restart IntelliJ, opening
> > the project, enabling RoboVM plugin, restarting IntelliJ.
> > 
> > We are forced to do this every 4-5 runs, its very time consuming.
> > This started happening recently, since upgrading to 1.9 I think. Maybe
> > 1.8.
> > 
> > Also, when running on a device and after that running on simulator (or
> > vice versa) it also gets stuck.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/robovm/robovm/issues/1183.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/robovm/robovm/issues/1183#issuecomment-153281743.

## 

With regards,
      Alex Itelman
      054-8855550
P\*   Think Green. Do you really need to print this document?*

**Comment by badlogic** [comment]
This is the best i can offer at the moment, as it's an issue with Gradle,
whom we are talking to.

**Comment by alexitelman** [comment]
Cool, that's all you had to say.
Please let us know when it's resolved.

On Tuesday, 3 November 2015, Mario Zechner notifications@github.com wrote:

> This is the best i can offer at the moment, as it's an issue with Gradle,
> whom we are talking to.
> On Nov 3, 2015 9:30 AM, "alexitelman" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Right, this might work as well but its not a solution...
> > 
> > On Tuesday, 3 November 2015, Mario Zechner <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > Are you using Gradle? If so, please disable the Gradle daemon and kill
> > > all
> > > existing Java processes.
> > > On Nov 3, 2015 8:48 AM, "alexitelman" <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > 
> > > > After a few times of running the RoboVM project in IntelliJ, on the
> > > > next
> > > > run IntelliJ gets stuck and doesn't complete the run.
> > > > When killing it and restarting it gets stuck even earlier, on opening
> > > > the
> > > > project on the "Initializing Modules" stage.
> > > > What solves is it renaming the source folder, opening IntelliJ
> > > > without
> > > > selecting the project, disabling RoboVM plugin, restart IntelliJ,
> > > > opening
> > > > the project, enabling RoboVM plugin, restarting IntelliJ.
> > > > 
> > > > We are forced to do this every 4-5 runs, its very time consuming.
> > > > This started happening recently, since upgrading to 1.9 I think.
> > > > Maybe
> > > > 1.8.
> > > > 
> > > > Also, when running on a device and after that running on simulator
> > > > (or
> > > > vice versa) it also gets stuck.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/robovm/robovm/issues/1183.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/robovm/robovm/issues/1183#issuecomment-153281743.
> > 
> > ## 
> > 
> > With regards,
> > Alex Itelman
> > 054-8855550
> > P\* Think Green. Do you really need to print this document?*
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/robovm/robovm/issues/1183#issuecomment-153286794.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/robovm/robovm/issues/1183#issuecomment-153288998.

## 

With regards,
      Alex Itelman
      054-8855550
P\*   Think Green. Do you really need to print this document?*

**Comment by alexitelman** [comment]
I tried the stop+kill - it doesn't help in the case it's stuck on the
"initializing modules", intellij keeps being stuck

On Tue, Nov 3, 2015 at 10:47 AM, Alex Itelman alex.itelman@gmail.com
wrote:

> Cool, that's all you had to say.
> Please let us know when it's resolved.
> 
> On Tuesday, 3 November 2015, Mario Zechner notifications@github.com
> wrote:
> 
> > This is the best i can offer at the moment, as it's an issue with Gradle,
> > whom we are talking to.
> > On Nov 3, 2015 9:30 AM, "alexitelman" notifications@github.com wrote:
> > 
> > > Right, this might work as well but its not a solution...
> > > 
> > > On Tuesday, 3 November 2015, Mario Zechner notifications@github.com
> > > wrote:
> > > 
> > > > Are you using Gradle? If so, please disable the Gradle daemon and kill
> > > > all
> > > > existing Java processes.
> > > > On Nov 3, 2015 8:48 AM, "alexitelman" <notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > > 
> > > > > After a few times of running the RoboVM project in IntelliJ, on the
> > > > > next
> > > > > run IntelliJ gets stuck and doesn't complete the run.
> > > > > When killing it and restarting it gets stuck even earlier, on
> > > > > opening
> > > > > the
> > > > > project on the "Initializing Modules" stage.
> > > > > What solves is it renaming the source folder, opening IntelliJ
> > > > > without
> > > > > selecting the project, disabling RoboVM plugin, restart IntelliJ,
> > > > > opening
> > > > > the project, enabling RoboVM plugin, restarting IntelliJ.
> > > > > 
> > > > > We are forced to do this every 4-5 runs, its very time consuming.
> > > > > This started happening recently, since upgrading to 1.9 I think.
> > > > > Maybe
> > > > > 1.8.
> > > > > 
> > > > > Also, when running on a device and after that running on simulator
> > > > > (or
> > > > > vice versa) it also gets stuck.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/robovm/robovm/issues/1183.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/robovm/robovm/issues/1183#issuecomment-153281743
> > > > .
> > > 
> > > ## 
> > > 
> > > With regards,
> > > Alex Itelman
> > > 054-8855550
> > > P\* Think Green. Do you really need to print this document?*
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/robovm/robovm/issues/1183#issuecomment-153286794.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/robovm/robovm/issues/1183#issuecomment-153288998.
> 
> ## 
> 
> With regards,
>       Alex Itelman
>       054-8855550
> P\*   Think Green. Do you really need to print this document?*

## 

With regards,
      Alex Itelman
      054-8855550
P\*   Think Green. Do you really need to print this document?*

**Comment by alexitelman** [comment]
We upgraded from Gradle 2.4 to 2.8 and so far it seems extremely better. Doesn't hang in situations where it constantly hanged before (like switching between a sim and device runs).
And also the build is extremely much faster!

**Comment by badlogic** [comment]
That's excellent news! We can simply upgrade our wrappers to 2.8 then.
Thanks for trying and reporting, i'll do some testing on my end as well.

**Comment by alexitelman** [comment]
The debugger issue got worse though.. Not only the debugger crashes, but the whole app crashes when running in debug mode..

**Comment by alexitelman** [comment]
There's still a scenario when it gets stuck - if I'm changing something a gradle.build file and clicking "Sync Now" in IntelliJ, it gets stuck. If I disable the RoboVM plugin the sync works fine.

**Comment by badlogic** [comment]
Can you reproduce the getting stuck with a default project?

**Comment by alexitelman** [comment]
For some reason in a new project I don't get the "Gradle files have changed since last project sync. A project sync may be necessary for the IDE to work properly.   Sync Now" notification when I change something in the gradle.build
It's like IntelliJ doesn't recognise the gradle files.
But in Project Settings > Modules I did add Java-Gradle..
BTW, it didn't add it by default when I created the project.

**Comment by alexitelman** [comment]
And now IntelliJ got stuck on a regular run, without changing anything in gradle.build.. only changing some code.
So maybe the upgrade to 2.8 didn't actually help :-(

**Comment by alexitelman** [comment]
No, can't reproduce in default project.

**Comment by alexitelman** [comment]
ready? did you fix something?

**Comment by badlogic** [comment]
Sorry, no progress yet. I'm still trying to reproduce the getting stuckness.

**Comment by badlogic** [comment]
Was able to reproduce this by opening multiple projects and running different run configurations. Each run configuration retains a Config and AppCompiler object. IDEA retains all instantiated run configurations throughout its life, which also means the Config and AppCompiler are retained, leaking memory. Nulling the config and app compiler after use in the run config seems to fix this. Testing.

**Comment by badlogic** [comment]
![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202015-12-16%20at%2012.17.11-1cP1YqKisX.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202015-12-16%20at%2012.17.11-1cP1YqKisX.png)
