### ISSUE TITLE
robovm-rt-1.11.0.jar is duplicated in all IPA`s

### ISSUE THREAD

**Issue by kirillp** [robovm/robovm#1200]
it is present in 2 copies:
robovm-rt-1.11.0.jar and boot/robovm-rt.jar completely binary identical

**Comment by badlogic** [comment]
How do you build the IPA? Maven/Gradle/IDE?

**Comment by kirillp** [comment]
We use maven for build

**Comment by ntherning** [comment]
We already have an issue for this: https://github.com/robovm/robovm-maven-plugin/issues/28. This issue is not prioritized since the extra bytes added by the extra JAR file should be negligible when compared to e.g. your executable.

**Comment by kirillp** [comment]
This is not a few bytes, 
Robovm-rt-1.11.0.jar is about 50k+
