### ISSUE TITLE
CGBitmapContext.create crashing after iOS 9

### ISSUE THREAD

**Issue by rotter** [robovm/robovm#1202]
Hey

My game started crashing on prod after iOS 9 or 9.1 (I cant tell for sure) on the "create" method of CGBitmapContext.

I havent released any updates in months, and that part of the code worked fine until recently, so my only guess is the iOS version change.

Here is the relevant stack trace:

java.lang.NullPointerException
    at org.robovm.rt.bro.ptr.BytePtr.set(BytePtr.java:181)
    at org.robovm.apple.coregraphics.CGBitmapContext.create(CGBitmapContext.java:90)

Im gonna try to somehow bypass/overcome this problem, so if I find more info I will post here.

**Comment by rotter** [comment]
I know nothing about iOS dev (well, thats why I use RoboVM), but I found this:

https://developer.apple.com/library/prerelease/ios/releasenotes/General/iOS90APIDiffs/Objective-C/CoreGraphics.html

Which says the signature of CGBitmapContextCreate method changed on iOS 9. Could that be the reason?

```
From    
CGContextRef CGBitmapContextCreate (
    void *data,
    size_t width,
    size_t height,
    size_t bitsPerComponent,
    size_t bytesPerRow,
    CGColorSpaceRef space,
    CGBitmapInfo bitmapInfo
);

To  
CGContextRef _Nullable CGBitmapContextCreate (
    void * _Nullable data,
    size_t width,
    size_t height,
    size_t bitsPerComponent,
    size_t bytesPerRow,
    CGColorSpaceRef _Nullable space,
    uint32_t bitmapInfo
);
```

**Comment by BlueRiverInteractive** [comment]
Can you show us the code you use to create the `CGBitmapContext`?
BTW with the latest RoboVM you can use `new CGBitmapContext(...);` instead of the `create` method.

**Comment by rotter** [comment]
Hey BRI.

I just tried changing to "new ..." and same error happened. Here is the code:

```
byte[] nullData = null;

CGBitmapContext ctx = new CGBitmapContext(nullData, (long) originalImage.getSize().getWidth(), (long) originalImage.getSize().getHeight(), originalImage.getCGImage().getBitsPerComponent(), 0, originalImage.getCGImage().getColorSpace(), originalImage.getCGImage().getBitmapInfo());
```

Please note that the code was working for over 1 year, no update was submitted, it just started crashing to people who updated to iOS9 (or 9.1 not sure).

The purpose of this part of the code is to rotate an image.

**Comment by BlueRiverInteractive** [comment]
Please remove the first parameter `nullData` from the constructor. You cannot specify a null byte[] data for CGBitmapContext.

**Comment by rotter** [comment]
Thanks BRI. It indeed worked now after removing that parameter.

But that code was working in production for over a year, and that null parameter I got from a sample iOS code back then... so I really dont understand why it started crashing, but well, it's working now :)

Thanks

**Comment by BlueRiverInteractive** [comment]
I'm glad it's working now :)
It could be that the implementations of the create-methods/constructors changed during the update to iOS 9, I'm not 100% sure. Anyway, I think there should be a proper exception thrown when someone passes null data. I will look into it.
