### ISSUE TITLE
Need a way to allocate an AudioBufferList with room for more than one buffer

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#1206]
The Apple docs say that the `AudioBufferList` struct holds a variable number of buffers but when you allocate one now with our bindings there will never be more room than for one. It needs a constructor that looks something like:

``` java
    public AudioBufferList(int bufferCount) {
        super(VM.allocateMemory(AudioBufferList.sizeOf() + Math.max(0, bufferCount - 1) * AudioBuffer.sizeOf()));
        setNumberBuffers(bufferCount);
    }
```

If `bufferCount` is more than 1 an extra `(bufferCount -1)` buffers will be allocated at the end.

And `setBuffers(AudioBuffer[])` should not allow an array longer than the number of buffers allocated.

**Comment by BlueRiverInteractive** [comment]
This has been fixed now.
