### ISSUE TITLE
UIImage to java side binding  memory leak ?

### ISSUE THREAD

**Issue by yujinfu** [robovm/robovm#1211]
Hi, 
 I write a IOSCamera class use oc, and then binding several method in java side. The IOSCamera source is like below:

and then I call "readImage" method from java side , juse readImage 10 times a second without anyother processing,
then set UIImage to UIImageVIew in java side.
but it show me about:
RobovmLauncher[12068] <Warning>: Communications error: <OS_xpc_error: <error: 0x357fc614> { count = 1, contents =
        "XPCErrorDescription" => <string: 0x357fc86c> { length = 22, contents = "Connection interrupted" }
    }>
and  Receive memory warning in Eclipse console, 
is there any wrong in RoboVM UIImage binding or AVFoundation binding.
I have quesion a bug about  AVCaptureVideoDataOutput 's setSampleBufferDelegate
which is public void didOutputSampleBuffer(AVCaptureOutput captureOutput,CMSampleBuffer sampleBuffer,AVCaptureConnection connection)
method only callback for 13 times when I open a camera (back or front) or toggle a camera.
 https://groups.google.com/forum/#!searchin/robovm/13$20times/robovm/yIGI9YgsdPw/C-PUpPWfEwAJ

I don't know what's wrong in it ? if anybody know how to solve it , please help me ,thanks very much.

IOSCamera.h
# import <Foundation/Foundation.h>
# import <AVFoundation/AVFoundation.h>
# import "UIKit/UIKit.h"

@interface IOSCamera : NSObject<AVCaptureVideoDataOutputSampleBufferDelegate>
- (void) openCamera:(int) camera;
- (void) closeCamera;
- (UIImage*) readImage;
- (UIImage *) convertBGRToRGB:(UIImage *)BGRAImage;
  @end

IOSCamera.m
# import "IOSCamera.h"
# import "conversions.hpp"
# include <opencv2/opencv.hpp>
# include <opencv2/highgui/ios.h>
# include <opencv2/nonfree/features2d.hpp>

@interface IOSCamera()
{
    AVCaptureSession \* session;
    AVCaptureVideoDataOutput \* dataOutput;
    AVCaptureDeviceInput \* input;
    UIImage \* image;
    UIImage \* imageRGB;
}

@end

@implementation IOSCamera
- (void)openCamera:(int)camera{
  [self closeCamera];
  AVCaptureDevice \* device;
  if (camera == 0) {
      device = [self deviceWithPosition:AVCaptureDevicePositionBack];
   //   device = [self deviceWithPosition:AVCaptureDevicePositionBack];
  }else if(camera == 1){
      device = [self deviceWithPosition:AVCaptureDevicePositionFront];
  }
  
  session = [[AVCaptureSession alloc] init];
  [session beginConfiguration];
  if ([session canSetSessionPreset:AVCaptureSessionPresetMedium]) {
      [session setSessionPreset:AVCaptureSessionPresetMedium];
  } else if ([session canSetSessionPreset:AVCaptureSessionPresetLow]) {
      [session setSessionPreset:AVCaptureSessionPresetLow];
  } else {
      NSLog(@"[Camera] Error: could not set session preset");
  }
  
  NSError \* error = nil;
  input = [AVCaptureDeviceInput deviceInputWithDevice:device error:&error];
  error = nil;
  [device lockForConfiguration:&error];
  if ([device isFocusModeSupported:AVCaptureFocusModeContinuousAutoFocus]) {
      device.focusMode = AVCaptureFocusModeContinuousAutoFocus;
  }
  /_if ([device isExposureModeSupported:AVCaptureExposureModeAutoExpose]) {
      device.exposureMode = AVCaptureExposureModeAutoExpose;
  }_/
  /_if([device isFlashModeSupported:AVCaptureFlashModeAuto]){
      [device setFlashMode:AVCaptureFlashModeAuto];
  }_/
  /_if([device isWhiteBalanceModeSupported:AVCaptureWhiteBalanceModeAutoWhiteBalance]){
      [device setWhiteBalanceMode:AVCaptureWhiteBalanceModeAutoWhiteBalance];
  }_/
  
  //[device setSubjectAreaChangeMonitoringEnabled:true];
  [device setActiveVideoMinFrameDuration:CMTimeMake(1, 8)];
  [device setActiveVideoMaxFrameDuration:CMTimeMake(1, 8)];
  
  [device unlockForConfiguration];
  
  if ([session canAddInput:input]) {
  
  ```
  [session addInput:input];
  ```
  
  }
  
  NSLog(@"open camera:%d",camera);
  
  dataOutput = [[AVCaptureVideoDataOutput alloc] init];
  dataOutput.videoSettings = [NSDictionary dictionaryWithObject:[NSNumber numberWithUnsignedInt:kCVPixelFormatType_32BGRA]forKey:(id)kCVPixelBufferPixelFormatTypeKey];
  
  [dataOutput setAlwaysDiscardsLateVideoFrames:true];
  if ( [session canAddOutput: dataOutput] ) {
      [session addOutput: dataOutput];
  }
  [[dataOutput connectionWithMediaType:AVMediaTypeVideo] setEnabled:YES];
  
  // set video mirroring for front camera (more intuitive)
  if ([dataOutput connectionWithMediaType:AVMediaTypeVideo].supportsVideoMirroring) {
      if (camera == 1) {
          [dataOutput connectionWithMediaType:AVMediaTypeVideo].videoMirrored = YES;
      } else {
          [dataOutput connectionWithMediaType:AVMediaTypeVideo].videoMirrored = NO;
      }
  }
  
  // set default video orientation
  if ([dataOutput connectionWithMediaType:AVMediaTypeVideo].supportsVideoOrientation) {
      [dataOutput connectionWithMediaType:AVMediaTypeVideo].videoOrientation = AVCaptureVideoOrientationLandscapeRight;
  }
  
  // create a serial dispatch queue used for the sample buffer delegate as well as when a still image is captured
  // a serial dispatch queue must be used to guarantee that video frames will be delivered in order
  // see the header doc for setSampleBufferDelegate:queue: for more information
  dispatch_queue_t queue = dispatch_queue_create("Camera_Queue",DISPATCH_QUEUE_SERIAL);
  [dataOutput setSampleBufferDelegate:self queue:queue];
  [session commitConfiguration];
  [session startRunning];

}
- (void)closeCamera{
  
  if (session != NULL) {
      [session beginConfiguration];
      [session removeInput:input];
      [session removeOutput:dataOutput];
      [session commitConfiguration];
      [session stopRunning];
      session = NULL;
      input = NULL;
      dataOutput = NULL;
  }
  }
- (void)captureOutput:(AVCaptureOutput _)captureOutput didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection{
  @autoreleasepool {
      CVImageBufferRef imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
      /_Lock the image buffer_/
      CVPixelBufferLockBaseAddress(imageBuffer,0);
      /_Get information about the image*/
      uint8_t *baseAddress = (uint8_t *)CVPixelBufferGetBaseAddress(imageBuffer);
      size_t bytesPerRow = CVPixelBufferGetBytesPerRow(imageBuffer);
      size_t width = CVPixelBufferGetWidth(imageBuffer);
      size_t height = CVPixelBufferGetHeight(imageBuffer);
  
  ```
  /*Create a CGImageRef from the CVImageBufferRef*/
  CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
  CGContextRef newContext = CGBitmapContextCreate(baseAddress, width, height, 8, bytesPerRow, colorSpace,  kCGImageAlphaPremultipliedLast | kCGBitmapByteOrder32Big);
  CGImageRef newImage = CGBitmapContextCreateImage(newContext);
  image = [UIImage imageWithCGImage:newImage];
  //NSLog(@"image size: h %zu, w %zu", height, width);
  
  
  
  
  /*We unlock the  image buffer*/
  CVPixelBufferUnlockBaseAddress(imageBuffer,0);
  
  /*We release some components*/
  CGContextRelease(newContext);
  CGColorSpaceRelease(colorSpace);
  
  CGImageRelease(newImage);
  ```
  
  }
  }
- (AVCaptureDevice *) deviceWithPosition:(AVCaptureDevicePosition) position{
  NSArray \* deviceArray = [AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo];
  AVCaptureDevice *device;
  for (device in deviceArray) {
      if (device.position == position) {
          return device;
      }
  }
  return NULL;
  }

-(UIImage*) readImage{

```
return image;
```

}
- (UIImage *) convertBGRToRGB:(UIImage *)BGRAImage
  {
  //转BGR to RGB
  cv::Mat tempMat;
  SGUIImageToMat(BGRAImage, tempMat);
  cv::cvtColor(tempMat, tempMat, CV_BGRA2RGBA);
  imageRGB = SGMatToUIImage(tempMat);
  NSLog(@"width : %d height : %d bitperpixel %d",CGImageGetWidth(imageRGB.CGImage),CGImageGetHeight(imageRGB.CGImage),CGImageGetBitsPerPixel(imageRGB.CGImage));
  return imageRGB;
  }

@end

**Comment by yujinfu** [comment]
Hi, 
I use System.gc() when receive memory warning, but app also crash without anyother message in Eclipse console

2015-12-13 15:50:10.966 RobovmLauncher[19531:2872889] [debug] IOSApplication: iOS version: 8.3
2015-12-13 15:50:10.966 RobovmLauncher[19531:2872889] [debug] IOSApplication: Running in 32-bit mode
2015-12-13 15:50:10.970 RobovmLauncher[19531:2872889] [debug] IOSApplication: scale: 2.6086957
2015-12-13 15:50:10.979 RobovmLauncher[19531:2872889] [debug] IOSApplication: Unscaled View: LandscapeRight 736x414
2015-12-13 15:50:10.980 RobovmLauncher[19531:2872889] [debug] IOSApplication: View: LandscapeRight 1920x1080
2015-12-13 15:50:10.981 RobovmLauncher[19531:2872889] [debug] IOSGraphics: 1920.0x1080.0, 2.6086957
2015-12-13 15:50:11.074 RobovmLauncher[19531:2872889] [debug] IOSGraphics: Display: ppi=401, density=2.50625
2015-12-13 15:50:11.462 RobovmLauncher[19531:2872889] [debug] IOSApplication: created
2015-12-13 15:50:11.478 RobovmLauncher[19531:2872889] systemVersion:8.3
2015-12-13 15:50:11.544 RobovmLauncher[19531:2872889] [debug] IOSApplication: resumed
LOG: ============ start camera
2015-12-13 15:51:01.312 RobovmLauncher[19531:2873142] Communications error: <OS_xpc_error: <error: 0x357fc614> { count = 1, contents =
    "XPCErrorDescription" => <string: 0x357fc86c> { length = 22, contents = "Connection interrupted" }
}>
2015-12-13 15:51:09.563 RobovmLauncher[19531:2872889] Received memory warning.
System.gc()=======call 7.7109375(Gdx.app.getJavaHeap()/1024f/1024f)  7.7109375(Gdx.app.getNativeHeap()/1024f/1024f)
System.gc()=======call 7.2734375  7.2734375
System.gc()=======call 6.4765625  6.4765625
System.gc()=======call 6.4296875  6.4296875
System.gc()=======call 6.4101563  6.4101563
System.gc()=======call 6.3984375  6.3984375

**Comment by yujinfu** [comment]
System.gc()=======call  7.7109375(Gdx.app.getJavaHeap()) 7.7109375 (Gdx.app.getNativeHeap())
anyone know how to solve this problem? please help me ,thanks very much

**Comment by ntherning** [comment]
Please don't cross-post on Google Group and on Github. I will respond on the Google Group. Github Issues are only appropriate once we have established that there's a bug in RoboVM.
