### ISSUE TITLE
IntelliJ plugin fails in v15.0.1

### ISSUE THREAD

**Issue by vicmosin** [robovm/robovm#1220]
I have two versions installed, 14 and 15. 14 works fine.

![bildschirmfoto 2015-12-21 um 16 16 19](https://cloud.githubusercontent.com/assets/612207/11955472/9171b190-a8b2-11e5-91cb-22b2e901163b.png)

**Comment by badlogic** [comment]
You need to setup a JDK, the RoboVM plugin should have asked you to do so. This should be fixed, let me know if the latest version doesn't work for you still.
