### ISSUE TITLE
Site: Some images look distorted

### ISSUE THREAD

**Issue by intrigus** [robovm/robovm#1221]
Some images on the RoboVM-Site look distorted, e.g. The 'free shirt' image.
The screenshot is taken from the [Pricing](https://robovm.com/pricing/) page.

See http://s9.postimg.org/67gh9bb8f/Jq_ZAO.jpg
Useragent: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko (Should be IE 11 on Win7)

**Comment by ntherning** [comment]
Thanks for letting us know! We will look into it.

**Comment by hanslarsson** [comment]
Added a new script that sets the height on sag images. Solution has been tested in ie9 and ie11 on windows 7.
