### ISSUE TITLE
Bug: Parsing minimum version number crashes for single-digit version numbers

### ISSUE THREAD

**Issue by noblemaster** [robovm/robovm#1222]
RoboVM grade build crashes if the "MinimumOSVersion" defined in Info.plist.xm is a single-digit value (e.g. "7"). A StringIndexOutOfBoundsException is thrown. 

Crashing Info.plist.xml:

``` xml
  <key>MinimumOSVersion</key>
  <string>7</string>
```

Working Info.plist.xml:

``` xml
   <key>MinimumOSVersion</key>
   <string>7.0</string>
```

File & Line# in Question:
https://github.com/robovm/robovm/blob/ef091902377c00dc0fb2db87e8d79c8afb5e9010/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java#L353

Suggested fixes:
- Catch "StringIndexOutOfBoundsException" in addition to "NumberFormatException" otherwise the resulting error message is nonsensical (I didn't have a clue what broke because the error message in the try-catch isn't reached because the exception is not a number format exception).
- Allow single-digit numbers for MinimumOSVersion. I think that's supported by iOS anyway.

**Comment by ntherning** [comment]
Looks like at least the iOS simulator can handle single digit numbers. We should make sure it doesn't fail within RoboVM.

**Comment by ntherning** [comment]
Fixed!
