### ISSUE TITLE
RoboVM Plugin keeps resetting the Java language level to 1.8 in IntelliJ

### ISSUE THREAD

**Issue by noblemaster** [robovm/robovm#1224]
The fix implemented in https://github.com/robovm/robovm/issues/1140 keeps resetting the language level across all modules to 1.8. I don't mind the RoboVM-related modules to be at 1.8, but other modules with server code etc. cannot be at 1.8. It's impossible now to change other modules to anything other than 1.8 as it it reset immediately back to 1.8.

Here is the code:
https://github.com/robovm/robovm-idea/commit/bb8f8c2c65b244e5ced24f64518d6d7aa3ff95e1

Suggested Fixes:
- Option A. Can the plugin ONLY set the language level to 1.8 if it is an actual RoboVM project?
- Option B. If the above is not possible: can we have a checkbox for the RoboVM plugin settings to disable resetting all the language levels?

**Comment by badlogic** [comment]
It is hard for us to detect which modules require Java 8 and which don't. Sadly, the Gradle integration in IntelliJ IDEA doesn't load the language level from the Gradle build files. Upon importing a Gradle project with a language level requirement of 8, things would just break, and new users would be confused.

I therefor went with Option B and added a setting that lets you disable this forceful language level setting.

**Comment by noblemaster** [comment]
Thanks :)

**Comment by ItsHarper** [comment]
The latest version of Gradle claims to fix this problem!
https://docs.gradle.org/2.12/release-notes
