### ISSUE TITLE
Crash II on simulator with up-to-date libGDX app

### ISSUE THREAD

**Issue by MikaelMayer** [robovm/robovm#1225]
Happy New Year everybody !!

After updating all versions of LibGDX, Robovm in my gradle project, my XCode, etc,
I am left with a new project which as the same error as in [issue 1166](https://github.com/robovm/robovm/issues/1166).  
The error is that after launching

```
./gradlew launchIPhoneSimulator
```

The initial screen loads, but the menu with the pictures does not show up afterwards, and later the app closes unexpectedly.

![capture d ecran 2016-01-05 23 11 07](https://cloud.githubusercontent.com/assets/3601079/12129258/b321f696-b402-11e5-9c4d-298eae7708db.png)
![capture d ecran 2016-01-05 23 13 19](https://cloud.githubusercontent.com/assets/3601079/12129262/b6f26850-b402-11e5-9ba5-afdd268d2382.png)

Here is the still not working project.
[GraphismGdxMacMinStillNotWorking.sip](https://drive.google.com/file/d/0B0OEZcvpw5vecmV4R2xIbzI1Ync/view?usp=sharing)

The versions I use are the following:

```
org.robovm:robovm-gradle-plugin:1.9.0
gdxVersion = '1.7.2'
roboVMVersion = '1.12.0'
roboVMGradleVersion = '1.12.0'
```

**Comment by ntherning** [comment]
You should use 1.12.0 of the robovm-gradle-plugin. If it still crashes
check in Console (an OSX app to view logs) for a crash log and attach to
the issue.

**Comment by MikaelMayer** [comment]
That made the trick, thank you ! That's wonderful.
After that I just had to launch the app twice (perhaps because of cache issues) as the first time it would complain about "Execution failed for task....", but the second time it uploaded the app and when I launched it on the simulator it worked !
All the best !!!
