### ISSUE TITLE
Need IntelliJ IDEA plugin for RoboVM

### ISSUE THREAD

**Issue by trukhinyuri** [robovm/robovm#136]
Need IntelliJ IDEA plugin for RoboVM

**Comment by voidstarfire** [comment]
I also get Unsupported major.minor version 51.0 [Plugin: org.robovm.intellij] when trying to start the RoboVM plugin, using Java 8.

**Comment by badlogic** [comment]
You might have installed Java 8, but you have not told IDEA to use it. Please see this getting started guide on how to setup IDEA to not use Java 6: http://docs.robovm.com/getting-started/intellij.html

**Comment by voidstarfire** [comment]
Thanks very much, I was using Android Studio and within the info.plist it was set to 1.6+,1.7*. Changes to 1.7+. Everything looks very different. Also breaks the studio Dracula theme.

**Comment by badlogic** [comment]
Could you please file an issue at http://github.com/robovm/robovm-idea
including a detailed description or your problem with screenshots? Thanks!
On Apr 23, 2015 11:31 AM, "voidstarfire" <notifications@github.com> wrote:
>
> Thanks very much, I was using Android Studio and within the info.plist it
was set to 1.6+,1.7*. Changes to 1.7+. Everything looks very different.
Also breaks the studio Dracula theme.
