### ISSUE TITLE
Thread safety on the RoboVM

### ISSUE THREAD

**Issue by hnvn** [robovm/robovm#164]
I'm working in the libgdx. Now, i'm trying to build my game to iOS (use the RoboVM). My game use "SmartFox Java Client API" to connect to the SmartFoxServer (http://smartfoxserver.com/). It work fine on the Desktop and Android, but don't work on iOS. Because, on the iOS, SmartFox Client run in the thread unsafe environment, therefore it can't catch Events is dispatched. How can i fix this?

**Comment by schwips** [comment]
Hi hnvn
Is it possible that you sell me the binding-project? How much would it cost?
Please send your answer at support@sweetware.ch
