### ISSUE TITLE
JavaFX Canvas Node rendering problems

### ISSUE THREAD

**Issue by HanSolo** [robovm/robovm#310]
Using a Canvas Node in JavaFX with robovm (tested with version 0.0.10 on iPad mini retina and iPhone5) leads to rendering problems. The rendering itself is not wrong but sometimes parts of the Canvas Node won't be drawn. It looks like the if drawing the Canvas node will take to long it will skip parts.

**Comment by ntherning** [comment]
Please report this issue to the javafxports project if you are still seeing this.
