### ISSUE TITLE
Crash when building Scala project for the simulator

### ISSUE THREAD

**Issue by Aiybe** [robovm/robovm#313]
Any project with the Scala classes on the classpath fails to build for the simulator with RoboVM 0.0.11. Building for a device works fine, but LLVM always crashes when building the "scala.concurrent.forkjoin.ForkJoinPool" class for iOS x86. I'm using the Gradle plugin, but it seems to happen when building manually, too. Here's the relevant part of the log:

```
07:18:21.788 [DEBUG] [org.gradle.api.Task] Compiling org.robovm.apple.uikit.UIAlertViewDelegate$ObjCProxy (ios x86)
07:18:21.927 [DEBUG] [org.gradle.api.Task] Compiling org.robovm.apple.uikit.UIAlertViewDelegateAdapter (ios x86)
07:18:21.962 [DEBUG] [org.gradle.api.Task] Compiling org.robovm.apple.uikit.UIAlertViewStyle (ios x86)
07:18:36.100 [DEBUG] [org.gradle.api.Task] Compiling scala.concurrent.forkjoin.ForkJoinPool (ios x86)
> Building 95% > :gdx-ios:launchIPhoneSimulator LLVM ERROR: ran out of registers during register allocation
```

If I copy a different compiled class from the forkjoin package in RoboVM's cache and rename it to ForkJoinPool, it compiles fine but, obviously, the linker fails because of unresolved symbols.

**Comment by ntherning** [comment]
I consider this fixed until someone test it and tell me it doesn't. :-)
