### ISSUE TITLE
Loading libraries & using open HTTPS crash

### ISSUE THREAD

**Issue by MrMMatricks** [robovm/robovm#319]
Hello!
The nice folks of blue river interactive send me here to post a bug. I am including one of their bindings in my project (Google Game Services) and after that as soon as I request a HTTPS site in my own code using a HttpURLConnection the app crashes with a EXC_BAD_ACCESS. And they have no idea why. To me it seems like something got linked incorrectly. Since this also happens when i just include the library from them but not use it in my code.

You can download a small complete example for eclipse here: 
 http://www.mrmlabs.at/HTTPSTest.zip

Just the code is here:
http://pastebin.com/9VWsVt2D

The robovm.xml:
http://pastebin.com/5eK821PF

and the error itself from the iphone symbolized:
http://pastebin.com/kgMRdtVr

Thanks

**Comment by ntherning** [comment]
We have fixed the issue with Google Game Services in #883.
