### ISSUE TITLE
Resources inside linked frameworks are not linked

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#346]
When an app links to a third party framework via the frameworkPaths entry in the robovm.xml, the resources are not linked resulting in a crash as soon as the framework gets used.

This can be reproduced by the Tapjoy framework here (or any other framework that has a resources folder): https://github.com/BlueRiverInteractive/robovm-ios-bindings/tree/master/tapjoy

Just using any line of code from the framework (like Tapjoy.requestConnect("","");) results in the app crashing without any error message. A workaround is to explicitly declare the resources folder of the framework as a resource directory in the robovm.xml, like 
```
<resource>
	<directory>libs/Tapjoy.framework/Resources</directory>
</resource>
```

**Comment by ebbybeh** [comment]
Thanks a million BlueRiver! I could not for the life of me figure out how to get Tapjoy to work, but adding the resources did it.

**Comment by badlogic** [comment]
This is now implemented for dynamic frameworks. For static frameworks, we need to copy the resources to the main bundle. In case this overwrites another resource, we should log a warning.

**Comment by badlogic** [comment]
We decided to not copy resources of static frameworks automatically, but instead have the user specify the directories manually in `robovm.xml`. For RoboPods, we can do this in their respective `robovm.xml`, so there's no extra burden on the user. @BlueRiverInteractive could you ensure this is the case?
