### ISSUE TITLE
Support NSUIntegerMax for 32-bit and 64-bit machines

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#387]

**Comment by ntherning** [comment]
Could we do this in bro-gen? Use the expression `Bro.IS_32BIT ? 0xffffffffL : 0xffffffffffffffffL` for `NSUIntegerMax` occurrences? E.g.:

```java
public static final MKDirectionsTransportType Any = new MKDirectionsTransportType(Bro.IS_32BIT ? 0xffffffffL : 0xffffffffffffffffL);
```

**Comment by BlueRiverInteractive** [comment]
I have looked into this but haven't found a way with FFI clang to know if the constant value was `NSUIntegerMax` or not. The cursor accessor `enum_value` / `clang_getEnumConstantDeclValue` just returns the resolved value (which is -1, not sure why) and the constant type is just `NSUInteger`.
Searching `NSUIntegerMax` in all frameworks, I've found that only:
`UICollisionBehaviorModeEverything`, `UIDataDetectorTypeAll` and `UIPopoverArrowDirectionUnknown` 
to use it. `MKDirectionsTransportType.Any` is defined as `0x0FFFFFFF` in my iPhoneOS8.1.sdk.

`NSIntegerMax` is used only for:
`PHCollectionListSubtypeAny` and `PHAssetCollectionSubtypeAny`.

Probably the easiest solution would be to manually set the value `Bro.IS_32BIT ? 0xffffffffL : 0xffffffffffffffffL` for these 5 constants.

**Comment by ntherning** [comment]
According to [Apple's docs](https://developer.apple.com/library/mac/documentation/MapKit/Reference/MKDirectionsRequest_class/index.html#//apple_ref/c/econst/MKDirectionsTransportTypeAny) MKDirectionsTransportTypeAny should be `NSUIntegerMax`. But you are saying that the header file says `0x0FFFFFFF`? Weird!

So, if type is `NSUInteger` and the value is -1 we know it's `NSUIntegerMax`, right?

For `NSIntegerMax` it's trickier. When we run `bro-gen` do we use a 32-bit or 64-bit architecture? I guess it would be possible to detect this if we run in 64-bit mode?  If type is `NSInteger` and value is `0x7fffffffffffffff` it should be `NSIntegerMax`.

**Comment by BlueRiverInteractive** [comment]
I've found that Apple's docs are not always correct ;)

> So, if type is NSUInteger and the value is -1 we know it's NSUIntegerMax, right?

You're absolutely right! I totally forgot the fact that there will never be a negative constant like -1 in an unsigned int enum.
Also changing the target architecture to arm64 made it possible to do the checks for NSIntegerMax correctly!

**Comment by BlueRiverInteractive** [comment]
This should be fixed now.

Just one last question: Before using bro-gen with 64-bit, `UInt32 *` was bound as `MachineSizedUIntPtr`. Now it gets bound as `IntPtr`. Is this correct?

In MacTypes.h it's defined as:
```objc
#if __LP64__
typedef unsigned int                    UInt32;
typedef signed int                      SInt32;
#else
typedef unsigned long                   UInt32;
typedef signed long                     SInt32;
#endif
```

**Comment by ntherning** [comment]
IntPtr would be the correct type yes so what we had before was incorrect.
Weird that they use long on 32-bit and int on 64-bit as long==int on
32-bit! :-)

Is that the only thing that changed when switching to arm64?

**Comment by BlueRiverInteractive** [comment]
Yeah, kinda weird :)

2-3 enum values also changed, for example `NSDataWritingOptions.FileProtectionMask` (was: -268435456, now correct: 4026531840; defined as 0xf0000000).
