### ISSUE TITLE
Follow memory management rules for CoreFoundation and ObjC

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#435]
In ObjC the returned instance has already been retained once so we shouldn't retain it ourselves. In C functions with `Create` or `Copy` in their name return instances which have already been retained and are owned by the caller.

See https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmRules.html#//apple_ref/doc/uid/20000994
See https://developer.apple.com/library/ios/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029

**Comment by BlueRiverInteractive** [comment]
@ntherning Do we need to do anything specific (like a no retain marshaler) for returned NSObjects in ObjC frameworks? Or is everything already handled correctly with the default NSObject marshaler?

**Comment by ntherning** [comment]
We need a `NoRetainMarshaler` for `NSObject`s as well. But it's not as easy as for CFType of objects as we always create a new peer for those. Now we call `retain()` in `NSObject.afterMarshaled()` which is only called once for a peer instance. We should move this `retain()` to the marshaler instead. But there we don't know whether the peer instance has been retained already on the Java side or not. Let me think about this one a bit.

**Comment by ntherning** [comment]
Actually, for ObjC we only need to make sure we don't retain `NSObject`s returned by methods with names starting with `alloc`, `new`, `copy`, or `mutableCopy`. We already cover `NSObject.alloc()`.

Initially I thought we needed to use a `NoRetainMarshaler` for all static factory methods (e.g. `NSMutableArray arrayWithCapacity:`) but such method objects that are `autoreleased` so we do indeed need to retain such objects on the Java side to prevent them from being GCed once the autorelease pool is drained for the current thread. So we're already doing the right thing for such methods.

**Comment by ntherning** [comment]
Ok, we now have a `NSObject.NoRetainMarshaler` which we should use for methods with names starting with `alloc`, `new`, `copy` and `mutableCopy`. @BlueRiverInteractive your turn. :-)
