### ISSUE TITLE
Make sure we use the correct marshaler for Strings in the CocoaTouch bindings

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#438]
We need to be careful when we use String in the C frameworks. The default marshaler for String is a marshaler which expects a null-terminated `char*`, not a `CFString` or `NSString`. I think there are places now where we use `String` incorrectly. Maybe the easiest way to fix this would be to have a global annotations list in the YAML which is added to every generated class?

**Comment by BlueRiverInteractive** [comment]
This should be fixed now with the CocoaUtility class.
