### ISSUE TITLE
Another OutOfMemoryError

### ISSUE THREAD

**Issue by Arcnor** [robovm/robovm#472]
Sorry about the non-descriptive title :)

I'm trying to compile a LibGDX project for iOS, using the `./gradlew --debug launchiPhoneSimulator` command line. Everything starts compiling very fast on the RoboVM side, but after a while it starts going slower. After a few thousand classes, RoboVM dies with an OOME. If I run the project again, it compiles a few more classes and either dies again, or finishes.

Checking the memory usage, it seems to always increase and never decrease. Some leak somewhere?

The project I'm trying to compile is https://github.com/Arcnor/pixel-dungeon-gdx in case it matters (I might be doing something wrong, but I remember this working before).

Also, I've tried with the latest Gradle plugin (robovm-gradle-plugin-alpha-01) as well, with the same results.

Also, sorry if this is not really a RoboVM issue, although I think it might be :).

**Comment by ntherning** [comment]
I just pushed a change which I think could fix this issue. We now use a bounded queue in the thread pool of workers which are used during compilation. This should prevent the compiler thread from queueing up faster than the workers can process the queue. Also, for a simple HelloWorld app I saw the compile time drop by more than 25% which was a nice side effect. :-)

Please retry with the next nightly build and let us know if the problem you experienced is gone.

**Comment by ntherning** [comment]
I think this is fixed now. Will close this issue. Please reopen if you still the same problem once you've been able to try it out.

**Comment by Arcnor** [comment]
Sorry, I haven't had the time to test, I'll do it soon and reopen if I have
the same problem again. Thanks!
