### ISSUE TITLE
Packaging: Need to exclude .java files form distribution

### ISSUE THREAD

**Issue by kirillp** [robovm/robovm#488]
It would be nice to have an option to exclude files to bundle by mask. 

Many public jar files has all .java source bundled in, which leads to many garbage into iOS application package distribution. Neither RoboVM compiler, nor iOS execution needs .java files. 
As an example: having the gwt-user dependency adds several megabytes of useless java sources to iOS package distribution.

The corresponding discussion:

https://groups.google.com/forum/#!msg/robovm/XX45AnTmv5U/KjGEotxUnQUJ

**Comment by ntherning** [comment]
This has now been fixed you can use it like this:

``` xml
<stripArchives>
  <include>com/foo/**/*.class</include>
  <exclude>**/*.java</exclude>
</stripArchives>
```

This will include all `.class` files in the `com.foo` package and exclude all `.java` files. The default for `.class` files is to exclude them. All other files will be included by default. Patterns will be matched in order and the first one matching will be used.

Will be in next [nightly](http://docs.robovm.com/advanced-topics/nightlies.html) and in next release.

**Comment by kirillp** [comment]
can I ignore a list of .jar files at all ? 
I mean skip them from packaging

**Comment by ntherning** [comment]
No that is not currently possible. Are they big even after stripping? Can you use `<stripArchives>` to exclude all resources in those JARs to make them close to 0 bytes? Please give a good motivation why and we might be able to add support for it.

**Comment by kirillp** [comment]
Assume we have 100 maven modules, made by different work groups. We build all that to maven repo and have 100x Name-1.0-SNAPSHOT.jar. 

We don`t need any of them to be packaged to the IPA, so we have a code that builds by RoboVM to the IPA, extract IPA, delete all the *-SNAPSHOT.jar, re-sign and re-package all that again.

The problem is that it is very slow, and if we had a method to completely remove JAR files from processing by mask it would significantly speed up the build.
