### ISSUE TITLE
Implement tree shaking to minimize the number of compiled classes and file size

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#511]
UITouch imports SpriteKit's SKNode for extension methods, meaning that pretty much all of that framework gets pulled in. See https://github.com/robovm/robovm/blob/master/cocoatouch/src/main/java/org/robovm/apple/uikit/UITouch.java#L36

We need to come up with some sort of treeshaking or rethink the way extensions are handled.

**Comment by badlogic** [comment]
Info i gathered a while back. 

Create a standard iOS demo app. Here's the cache & app bundle for a 32-bit sim debug
build: https://gist.github.com/badlogic/1f315ce5bf51ed26c4fe

I also did a `otool -l` on the executable to see the section sizes:
https://gist.github.com/badlogic/fcfd7a30d50dca765f11

The __TEXT segment is 41mb in size. 30mb of that are assigned to
__TEXT:__text, which is our code. Another whooping 6mb are assigned to
__TEXT:__ehframe, which  we don't need at all afaik. And the rest of
the 5MB are assigned to read-only data in __TEXT:__const.

The __DATA segment is only 3.6mb big, i assume that's our read/write
data. Not sure what we generate that's not constant.

The __LINKEDIT segment is something i don't know at all. It accounts
for another 67mb of the executable.

As a first step, i wrote a little silly benchmarking thing to see if SQLite could help us with
the #files in the cache, see https://github.com/badlogic/filecache
which includes a contrived micro benchmark in the tests folder.

The test writes and then read 4000 files, which should account for the
OS file cache as well. Timings for filesystem cache on a very slow HDD:

Writing 4000 files a 20kb took 5.448664 secs
Reading 4000 files a 20kb took 43.945196 secs

Timings for the SQLite based cache:

Writing 4000 files a 20kb took 10.630548 secs
Reading 4000 files a 20kb took 6.544103 secs

Not a SQLite expert, but that's as fast as i could make it. SQLite loses on SSDs. File System cache:

Writing 4000 files a 20kb took 0.607204 secs
Reading 4000 files a 20kb took 0.159842 secs

Timings for SQLite:

Writing 4000 files a 20kb took 4.701722 secs
Reading 4000 files a 20kb took 2.897737 secs

**Comment by badlogic** [comment]
Did a quick release build for 32-bit sim:
https://gist.github.com/badlogic/2746c6ae626d45974dcf

64mb binary. Here are the segments:
https://gist.github.com/badlogic/e15ff518da95fd1312df

The __LINKEDIT section accounts for 46mb.

The Mach-O docs say the __LINKEDIT segment is used by the dynamic
linker. There shouldn't be a need for that segment for an executable.

Stripping the binary brings it down to a manageable 19mb. Here's the
segments after stripping:
https://gist.github.com/badlogic/e8d5f7cce20ada42d9e3

The __LINKEDIT segment has been decimated, while the other segments
stay roughly the same. 

Looked through a release binary with a hex editor. Pretty much all of the __LINKEDIT segment is made up of our super descriptive but also super long method names.

**Comment by BlueRiverInteractive** [comment]
Size of a RoboVM single view application (32-bit + 64-bit) with latest snapshot:
```
exe: 28122192  (~26,8MB)
ipa: 8065760 (~7,7MB)
```

**Comment by ntherning** [comment]
We now have basic support for this. We'll create new issues for tree shaking related problems that come come up.

**Comment by badlogic** [comment]
Disected a stripped HelloWorld binary for x86_64. Extracted text (==code) and data section to separate files, then zipped them:

[26/06/15 17:32:28] Mario Zechner: -rwxr-xr-x   1 badlogic  staff   6.8M Jun 26 17:11 HelloWorld*
-rw-r--r--   1 badlogic  staff   4.8M Jun 26 17:30 code
-rw-r--r--   1 badlogic  staff   1.8M Jun 26 17:30 code.zip
-rw-r--r--   1 badlogic  staff   1.8M Jun 26 17:31 data
-rw-r--r--   1 badlogic  staff   453K Jun 26 17:32 data.zip
[26/06/15 17:32:41] Mario Zechner: text section compresses OK at 60%
[26/06/15 17:32:49] Mario Zechner: data compresses at 76%

Upon further inspection, the code section actually contains a lot of strings. Those should be in the data section.
