### ISSUE TITLE
Bro: Small structs byval fails on x86-64

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#568]
This fails on x86-64:

``` java
    public static void main(String[] args) throws Exception {
        NSString s = new NSString("Hello world");
        System.out.println(s);
    }
```

This ultimately calls the `[NSString getCharacters:range:]` Obj-C method which expects an `NSRange` to be passed by value. We use `{i64, i64} byval` in the generated bitcode but LLVM insists on copying the struct to the stack instead of passing it in registers as expected. Looking at what `clang` does for small structures it actually decomposes the struct into separate arguments in the call. We probably need to do something similar. Or alternatively embed libclang and generate snippets of C code when compiling `@Bridge` and `@Callback` methods. Then `clang` would handle all the pass by value quirks of each platform we support.

**Comment by mcolombo** [comment]
Hi,
Im still getting this error when starting the game in the simulator compiling it for x86-64.
Im using:
gdxVersion = '1.5.4-SNAPSHOT'
roboVMVersion = '1.0.0-SNAPSHOT'

Am i missing something here?
Thanks in advance Niklas.

Error is:
Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString getCharacters:range:]: Range or index out of bounds' *** First throw call stack:

(
	0   CoreFoundation                      0x000000010d7c8f35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010e053bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010d7c8e6d +[NSException raise:format:] + 205
	3   Chinchon                            0x00000001069ffc28 [J]org.robovm.apple.foundation.NSString.getCharacters(JLorg/robovm/objc/Selector;JLorg/robovm/apple/foundation/NSRange;)V + 195
	4   Chinchon                            0x00000001069ffcd3 [j]org.robovm.apple.foundation.NSString.getCharacters(JLorg/robovm/objc/Selector;JLorg/robovm/apple/foundation/NSRange;)V[clinit] + 77
	5   Chinchon                            0x0000000106a04ffc [J]org.robovm.apple.foundation.NSString$AsStringMarshaler.toObject(Ljava/lang/Class;JJ)Ljava/lang/String; + 203
	6   Chinchon                            0x0000000106a0504f [j]org.robovm.apple.foundation.NSString$AsStringMarshaler.toObject(Ljava/lang/Class;JJ)Ljava/lang/String;[clinit] + 52
	7   Chinchon                            0x00000001069d9081 [J]org.robovm.apple.foundation.NSObject.$m$description(Lorg/robovm/apple/foundation/NSObject;Lorg/robovm/objc/Selector;)Ljava/lang/String; + 197
	8   Chinchon                            0x00000001069d3e51 [J]org.robovm.apple.foundation.NSObject.description()Ljava/lang/String; + 76
	9   Chinchon                            0x00000001069d37c9 [J]org.robovm.apple.foundation.NSObject.toString()Ljava/lang/String; + 17
	10  Chinchon                            0x00000001066c64fe [J]java.lang.StringBuilder.append(Ljava/lang/Object;)Ljava/lang/StringBuilder; + 37
	11  Chinchon                            0x00000001065b81f1 [J]com.blyts.chinchon.IOSLauncher.setupInterstitial()V + 189
	12  Chinchon                            0x00000001065b8121 [J]com.blyts.chinchon.IOSLauncher.createApplication()Lcom/badlogic/gdx/backends/iosrobovm/IOSApplication; + 286
	13  Chinchon                            0x000000010649cfee [J]com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.didFinishLaunching(Lorg/robovm/apple/uikit/UIApplication;Lorg/robovm/apple/uikit/UIApplicationLaunchOptions;)Z + 56
	14  Chinchon                            0x0000000106b549ae [J]org.robovm.apple.uikit.UIApplicationDelegate$ObjCProxy.$cb$application$didFinishLaunchingWithOptions$(Lorg/robovm/apple/uikit/UIApplicationDelegate;Lorg/robovm/objc/Selector;Lorg/robovm/apple/uikit/UIApplication;Lorg/robovm/apple/uikit/UIApplicationLaunchOptions;)Z + 25
	15  Chinchon                            0x0000000106b54a88 [j]org.robovm.apple.uikit.UIApplicationDelegate$ObjCProxy.$cb$application$didFinishLaunchingWithOptions$(Lorg/robovm/apple/uikit/UIApplicationDelegate;Lorg/robovm/objc/Selector;Lorg/robovm/apple/uikit/UIApplication;Lorg/robovm/apple/uikit/UIApplicationLaunchOptions;)Z[callback] + 216
	16  UIKit                               0x000000010a2a4475 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 234
	17  UIKit                               0x000000010a2a4fbc -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2463
	18  UIKit                               0x000000010a2a7d2c -[UIApplication _runWithMainScene:transitionContext:completion:] + 1350
	19  UIKit                               0x000000010a2a6bf2 -[UIApplication workspaceDidEndTransaction:] + 179
	20  FrontBoardServices                  0x000000010ef322a3 __31-[FBSSerialQueue performAsync:]_block_invoke + 16
	21  CoreFoundation                      0x000000010d6fe53c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	22  CoreFoundation                      0x000000010d6f4285 __CFRunLoopDoBlocks + 341
	23  CoreFoundation                      0x000000010d6f4045 __CFRunLoopRun + 2389
	24  CoreFoundation                      0x000000010d6f3486 CFRunLoopRunSpecific + 470
	25  UIKit                               0x000000010a2a6669 -[UIApplication _run] + 413
	26  UIKit                               0x000000010a2a9420 UIApplicationMain + 1282
	27  Chinchon                            0x0000000106b417fe [J]org.robovm.apple.uikit.UIApplication.main(ILorg/robovm/rt/bro/ptr/BytePtr$BytePtrPtr;Ljava/lang/String;Ljava/lang/String;)I + 195
	28  Chinchon                            0x0000000106b40c15 [J]org.robovm.apple.uikit.UIApplication.main([Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Class;)V + 292
	29  Chinchon                            0x0000000106b40c68 [j]org.robovm.apple.uikit.UIApplication.main([Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Class;)V[clinit] + 68
	30  Chinchon                            0x00000001065b84c2 [J]com.blyts.chinchon.IOSLauncher.main([Ljava/lang/String;)V + 74
	31  Chinchon                            0x0000000106dc33de _call0 + 142
	32  Chinchon                            0x0000000106db8714 callVoidMethod + 104
	33  Chinchon                            0x0000000106dbb13c rvmCallVoidClassMethodA + 274
	34  Chinchon                            0x0000000106dbb213 rvmCallVoidClassMethod + 134
	35  Chinchon                            0x0000000106db323c rvmRun + 520
	36  Chinchon                            0x0000000106da9603 main + 291
	37  libdyld.dylib                       0x000000010dced145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ntherning** [comment]
I think it could be due to Gradle's caching of snapshot dependencies. Please try to force Gradle to download all dependencies or delete the Gradle cache as described here: http://stackoverflow.com/questions/13565082/how-can-i-force-gradle-to-redownload-dependencies

**Comment by mcolombo** [comment]
Hi Niklas,
Tried what you said (deleted cache folder and downloaded all gradle files again) but the problem persists...
Any other ideas?

Thanks anyway!
