### ISSUE TITLE
Strip doesn't support regex for `*lookup?` in exported_symbols file

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#584]
Getting this when compiling for iOS ARM in debug mode:
```
xcrun strip -s /var/folders/x5/833s8nbn1953zc403mr8sj800000gn/T/robovm7364663612963958203.tmp/exported_symbols /tmp/AttachTest/IOSDev/AttachTestIOSDev
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: symbols names listed in: /var/folders/x5/833s8nbn1953zc403mr8sj800000gn/T/robovm7364663612963958203.tmp/exported_symbols not in: /private/tmp/AttachTest/IOSDev/AttachTestIOSDev
_*lookup?
```

We add "*lookup?" as an exported symbol in `AbstractTarget#build()`, line 125 for any build irrespective of platform. However, only the iOS device build gets stripped, provoking this error.

The regex doesn't seem to match our `[lookup]` methods. The man page of strip doesn't say if regex are supported for symbols in the symbol file.

**Comment by ntherning** [comment]
Looked into this and it seems it's as simple as just running `strip -x`. That removes all local symbols. Everything that was exported during linking will be preserved. Will do some more tests...
