### ISSUE TITLE
Removing global symbols from a final linked no longer supported

### ISSUE THREAD

**Issue by titovmaxim** [robovm/robovm#623]
Since last weeks I've got the following message during builds:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: removing global symbols from a final linked no longer supported.  Use -exported_symbols_list at link time when building

Not sure if it important / relevant...

**Comment by rotter** [comment]
Yeah, I'm getting that error also.

[ERROR] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: removing global symbols from a final linked no longer supported.  Use -exported_symbols_list at link time when building: /my/app/path

But it seems to build OK, not sure.

**Comment by ntherning** [comment]
This should be fixed with #584.
