### ISSUE TITLE
robovm-1.0.0-beta-01: UnsatisfiedLinkError updateLastError during compile of HelloWorld

### ISSUE THREAD

**Issue by xranby** [robovm/robovm#661]
os: ubuntu 14.04 LTS

./robovm-1.0.0-beta-01/bin/robovm -verbose -cp classes/ HelloWorld
Compiling classes using 4 threads
Compiling HelloWorld (linux x86_64 release)
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:288)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:229)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:279)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:322)
	at org.robovm.compiler.AppCompiler.main(AppCompiler.java:568)
Caused by: java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Unknown.java:139)
	at turboactivate.TurboActivateNative.<clinit>(Unknown.java:1082)
	at turboactivate.r.e(Unknown.java:890)
	at com.robovm.lm.LicenseManager.<clinit>(Unknown.java:49)
	at com.robovm.debug.compiler.DebugInfoPlugin.beforeClass(Unknown.java:188)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:662)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:280)
	... 4 more
robovm: java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native

It appears the bundled JNA in robovm-1.0.0-beta-01 manage to loads the Ubuntu system installed JNA help library
/usr/lib/jni/libjnidispatch.so version 3.2.7
And this version require the updateLastError method for class com.sun.jna.Native

A workaround is to un-install the Ubuntu libjna-java package.

The proper fix is to patch the LimeLM TurboActivate license binarys used by robovm.

**Comment by ntherning** [comment]
Can you please try to patch the `robovm` script and add `-Djna.debug_load.jna=true` to the `java` command line and let us know what the output looks like?

Then add `-Djna.nosys=true` and let us know if that resolves the issue. If it does we will make sure to set this system property programatically.

**Comment by xranby** [comment]
Output using -Djna.debug_load.jna=true

./robovm-1.0.0-beta-01/bin/robovm -verbose -cp classes/ HelloWorld
A new version of RoboVM is available. Current version: 1.0.0-beta-01. New version: 1.2.0.
Compiling classes using 4 threads
Compiling java.lang.Short (linux x86_64 release)
Trying (via loadLibrary) jnidispatch
Found jnidispatch on system path
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:288)
...


Output using -Djna.debug_load.jna=true -Djna.nosys=true

./robovm-1.0.0-beta-01/bin/robovm -verbose -cp classes/ HelloWorld
Compiling classes using 4 threads
Compiling java.util.Arrays (linux x86_64 release)
Looking in classpath from sun.misc.Launcher$AppClassLoader@72766b42 for /com/sun/jna/linux-x86-64/libjnidispatch.so
Found library resource at jar:file:/home/xranby/robovm-test/robovm-1.0.0-beta-01/lib/robovm-dist-compiler.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
Trying /tmp/jna--751189186/jna1449809066638589112.tmp
Found jnidispatch at /tmp/jna--751189186/jna1449809066638589112.tmp
Line numbers in stack traces will not be available in this build: The RoboVM debugger has not been licensed for this machine. Please see http://www.robovm.com/buy for licensing options.
Compiling java.util.Arrays$ArrayList (linux x86_64 release)
...
Building executable /tmp/robovm6246889340229690014.tmp/HelloWorld
g++ -o /tmp/robovm6246889340229690014.tmp/HelloWorld -m64 @/tmp/robovm6246889340229690014.tmp/objects -L /home/xranby/robovm-test/robovm-1.0.0-beta-01/lib/vm/linux/x86_64 -Wl,-rpath=$ORIGIN -Wl,--gc-sections -lrobovm-bc -Wl,--whole-archive -lrobovm-rt -Wl,--no-whole-archive -lrobovm-core -lgc -lpthread -ldl -lm -lrt
Linked 1278 classes in 17,56 seconds
Installing executable to ./HelloWorld
Creating stripped archive file ./HelloWorld/lib/boot/robovm-rt.jar
Creating stripped archive file ./HelloWorld/lib/classes0.jar
$ ./HelloWorld/HelloWorld 
Hello world!

Yes by adding -Djna.nosys=true resolves this issue.

**Comment by ntherning** [comment]
Awesome, tack!

**Comment by ntherning** [comment]
This has been fixed now and will appear in the next nightly.
