### ISSUE TITLE
AppCompiler OutOfMemory exception

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#674]
This is more a question than a bug. 
When I compile less than 2000 classes I get no problem. Because it uses multiple threads many classes get compiled per second and it runs very fast. However when it gets to more than 2000 classes it is getting terribly slow. CPU usage of Eclipse goes way beyond 100% (according to activity monitor of OSX) and memory increases steadily. At this time only 1-2 classes get compiled per thread per second, whereas before they could do 10 or more. I don't know that much of compilers, but it seems that every compiled class gets immediately stored to file, so why is it that memory usage increases with every compiled class (thus leading to OutOfMemory exception every now and then)?

You should be able to reproduce this by freshly compiling all of CocoaTouch at once. If not, then it's just my MacBook. Typically my MacBook gets into an unusable state after 2-3 times compiling that many classes. I have to restart it to be fast and responsive again (restarting Eclipse doesn't help).

**Comment by ntherning** [comment]
I just pushed a change which I think could fix this issue. We now use a bounded queue in the thread pool of workers which are used during compilation. This should prevent the compiler thread from queueing up faster than the workers can process the queue. Also, for a simple HelloWorld app I saw the compile time drop by more than 25% which was a nice side effect. :-)

Please retry with the next nightly build and let us know if the problem you experienced is gone.

**Comment by BlueRiverInteractive** [comment]
Wow, that's like FTL drive now :)

Unfortunately there is some other error now #745
