### ISSUE TITLE
ABPerson - ClassCastException at line 301

### ISSUE THREAD

**Issue by hamzahrmalik** [robovm/robovm#675]
In the method public List<ABPersonPhoneNumber> getPhoneNumbers()
I get error:
org.robovm.apple.corefoundation.CFType cannot be cast to org.robovm.apple.addressbook.ABMultiValue
at org.robovm.apple.addressbook.ABPerson.getPhoneNumbers(ABPerson.java)

Having looked at the code, it seems that the cast to ABMultiValue on line 302 is causing the error

**Comment by BlueRiverInteractive** [comment]
This should be fixed now.
