### ISSUE TITLE
Bind CoreAudioKit

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#678]

**Comment by BlueRiverInteractive** [comment]
Have to postpone this as it depends on the AudioUnit framework, which we haven't bound yet.

**Comment by ntherning** [comment]
How much work would it be to finish AudioUnit and this you think?

**Comment by BlueRiverInteractive** [comment]
Lucky I have already started working on AudioUnit in the last days :)
It should be finished very soon.
