### ISSUE TITLE
Boolean property naming

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#684]
I've noticed that there are many obj-c properties that start with `has`, `allows`, `can`, `should` and several other verbs.
Most of them are named by prefixing `is` making up some redundant word combinations like `isAllowsTransforming`, `isShouldPerform`, `isHasChildren`. The setters, however, sound more reasonable: `setAllowsTransforming`, `setShouldPerform`, `setHasChildren`.

What would be the ideal Java getter for this? Omitting the `is` prefix (`allowsTransforming`, `shouldPerform`, `hasChildren`), leaving as-is, or something else?

**Comment by badlogic** [comment]
Omit is in getters i'd say.

**Comment by ntherning** [comment]
Omit :+1:

**Comment by BlueRiverInteractive** [comment]
Ok great, I'll go for that!

Von meinem iPhone gesendet
