### ISSUE TITLE
Create IPA with 32-bit and 64-bit slices

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#690]
We need to be able to create IPAs with both 32-bit and 64-bit slices. The user should be able to select the architectures to be included. We need to run the compiler separately for each arch and then use lipo to combine the executable into a single binary before we sign and create the IPA.

**Comment by titovmaxim** [comment]
@ntherning. Could you share your plans to implement 32&64 bit IPA? I thing the publishing will be impossible without this feature in few days.

**Comment by Darkyenus** [comment]
@titovmaxim I believe that it is already in, as of [beta 03](http://blog.robovm.org/2015/01/robovm-100-beta-3-is-here.html)

**Comment by titovmaxim** [comment]
@Darkyenus thanks a lot! I found that fat 32/64 IPA could be created by command line (non-eclipse user):
gradle -Probovm.ipaArchs=thumbv7:arm64 createIPA

Is it possible to achieve the same effect through some property of robovm.xml? Like:
<arch>thumbv7:arm64</arch>
or something like this? So to get the fat IPA bot both architectures?
