### ISSUE TITLE
Eclipse update site is broken

### ISSUE THREAD

**Issue by monospacesoftware** [robovm/robovm#695]
http://download.robovm.org/eclipse/

404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: eclipse/index.html
RequestId: A9914A358829DF88
HostId: u0xtVPDog8OPAzLCbC4zsd+C59kXg2SMrrIsjXDCwK0TuJ60AwPpBTrUnHl62g9AqgWvGvQCSyo=

**Comment by ntherning** [comment]
It's not broken, just not browsable. You need to input this URL into Eclipse -> Help -> Install New Software. Eclipse will know what to do with it.

**Comment by monospacesoftware** [comment]
Thanks, I apologize - my Eclipse install was partially to blame.  It couldn't make socket connections due to being on a mapped drive, apparently.
