### ISSUE TITLE
Make sure classes like NSPathUtilities use correct marshalers

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#696]
`NSPathUtilities` is a class we've come up with ourselves which gather a bunch of related C functions from `Foundation`. Since this class inherits from `Object` it doesn't get the `NSString` and `NSArray.AsListMarshaler` marshalers which some of its methods rely on. E.g. `getHomeDirectory()` returns garbage since the builtin `String` marshaler which assumes zero terminated C strings is used.

We should need to go over all such classes in the bindings and make sure they have correct marshalers. Another idea would be to have them extend from a common class or implement a special interface which defines the necessary marshalers.

**Comment by BlueRiverInteractive** [comment]
A special interface seems a good way to do this. We can use bro-gen's `protocols` key for classes to implement that directly in the yaml files.
I think we will need two common interfaces, one for obj-c frameworks (NSString) and one for c frameworks (CFString). 

I'm not sure about good names, what do you think about CommonObjCMarshalers, ObjCMarshaling, FoundationMarshaling/CoreFoundationMarshaling, FoundationUtility?

**Comment by BlueRiverInteractive** [comment]
Hmm I just thought about the fact that CFString is toll-free bridged to NSString. Would there actually be any deficit in using the NSString marshaler for CoreFoundation classes with CFString or is it better to use different marshalers?

**Comment by ntherning** [comment]
I think we should use NSString as much as possible. Looking at Xamarin I believe they keep the CoreFoundation bindings to a minimum and use the ObjC version of the toll-free bridged classes as much as possible.

**Comment by ntherning** [comment]
Another one which is using the wrong marshaler for Strings: UIActivityType.

**Comment by BlueRiverInteractive** [comment]
The class `CocoaUtility` will now be used as super class for all these custom classes. It utilizes the `NSString.AsStringMarshaler` and `NSArray.AsListMarshaler`.
