### ISSUE TITLE
Selector wrapping too restrictive

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#701]
CocoaTouch has a few classes that allow listening for certain events via selector + object registration, especially UIKit. Currently we have tried to Java-fy it by creating a listener interfaces that wraps around the selector + object registration and hides the selector and object from the user. 
This is sometimes an unnecessary overhead (see https://groups.google.com/forum/#!topic/robovm/f_jQ04dUFVI) and it would be good to be able to use the original selector+object without having to extend the class. 
I propose to make the selector + object registration method and properties public again.

**Comment by BlueRiverInteractive** [comment]
The classes that hide the selector and target/object are 

```
CADisplayLink.java
GKSession.java
MPRemoteCommand.java
UIBarButtonItem.java
UIControl.java
UIGestureRecognizer.java
UIMenuItem.java
UIVideo.java
```

**Comment by ntherning** [comment]
+1 we'll expose both and let the user decide
