### ISSUE TITLE
iPhone-6-Plus Simulator is launching instead of iPhone-6 

### ISSUE THREAD

**Issue by titovmaxim** [robovm/robovm#702]
Just notices a strange Run-in-simulator bug in latest nightly. When I try to run iPhone-6 simulator, the simulator for iPhone-6-Plus is started. All other variants are working good at the same time (iPhone-4s, 5s, 6-Plus, iPad, etc.). I use robovm.device.name in gradle.properties with following values:
# iPhone-4s
# iPhone-5
# iPhone-5s
# iPhone-6
# iPhone-6-Plus
# iPad-2
# iPad-Retina
# iPad-Air
# Resizable-iPhone
# Resizable-iPad

Only iPhone-6 make troubles.

**Comment by ntherning** [comment]
Thanks for the report. It's a bug in the latest code. We now do a substring
match and iPhone-6-plus comes before iPhone-6 in the list returned by
ios-sim so the 6-plus will be matched. We need to be smarter.

Unfortunately beta 3 has just been tagged so this won't  be fixed until beta
4.
