### ISSUE TITLE
App crashes on simulator 64Bit using iPad retina, iPad 2, iPhone 4S and iPhone 5. 

### ISSUE THREAD

**Issue by Asafmo** [robovm/robovm#703]
1/15/15 1:27:21 PM: [ERROR] Session could not be started: Error Domain=NSPOSIXErrorDomain Code=3 "Unable to run app in Simulator" UserInfo=0x7f89f175bfd0 {NSUnderlyingError=0x7f89f150c2e0 "Failed to lookup the process ID of com.mybrand.brand after successful launch.  Perhaps it crashed after launch.", NSLocalizedFailureReason=An error was encountered while running (Domain = NSPOSIXErrorDomain, Code = 3), NSLocalizedDescription=Unable to run app in Simulator}

**Comment by ntherning** [comment]
That error I've seen when trying to launch in 64-bit mode on a simulated
device which only supports 32-bit. Exactly which device do you select in
the drop down? Can you please post the ios-sim command that RoboVM runs to
launch your app? You should have it in the RoboVM Console in Eclipse or on
the command line if you invoke RoboVM in verbose mode.

Here's a list of the device types and the archs they support:

Niklas-MacBookPro:robovm niklas$ ./bin/ios-sim showdevicetypes
com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-2, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.Resizable-iPhone, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.Resizable-iPad, 8.1, (x86_64 i386)

So the iPad-Retina is 32-bit only (i386). You need the iPad-Air which
supports 64-bit too (x86_64).

**Comment by Asafmo** [comment]
I'm not sure what are the ios-sim command

**Comment by ntherning** [comment]
Again, you must launch your app in a 64-bit capable simulated device. iPad Retina, iPad 2, iPhone 4S and iPhone 5 are all 32-bit only. You need to launch a iPhone-5s, iPhone-6, iPhone-6-Plus or iPad-Air if you want to test your app in 64-bit mode. There's is currently a bug which makes it impossible to select iPhone-6. That will just launch in iPhone-6-Plus instead. But the other ones should work.

**Comment by Asafmo** [comment]
Ok.

**Comment by rotter** [comment]
Just commenting here to add relevance to this issue, because I just spent hours struggling trying to test my game in 64 bits, only to find in this post that the problem was that the device I was choosing doesnt support 64 bits.

Shouldn't RoboVM plugin change the name of the devices (that appears on the Run Configurations menu) adding the supported archs? For example "iPhone 5 i386 only",  "iPhone 6 x86_64 i386".

Just to add search relevance, the error I was getting was:
"program specified by service does not contain one of the requested architectures: (some garbage)"

**Comment by davidpelayo** [comment]
thanks @ntherning, it was that the issue which happened to me.
