### ISSUE TITLE
Fine-Grained GC Control?

### ISSUE THREAD

**Issue by omer4d** [robovm/robovm#705]
It seems like a significant number of RoboVM users are game devs, and they have to resort to manual object pooling to avoid GC pauses. This approach is error-prone and requires lots of boilerplate code. The situation is especially bad for people trying to implement interactive apps using functional languages that target the JVM, since they generate a lot of garbage (by immutable data structures).

If I understand correctly, RoboVM uses the Boehm GC, which can do incremental garbage collection and even provides a function to do a small fraction of the object-marking work (which is called repeatedly by higher-level routines). Would it be possible to expose this function and allow users to fine-tune when and how garbage-collection is performed? In the case of a game, it would be viable to distribute the garbage collection work over many frames (or even vary the amount of work done based on spare frame time/importance of maintaining fluidity).

I have no prior experience with the inner workings of RoboVM, but if it's viable at all, I'd be willing to give it a shot myself (given some pointers in the right direction).

**Comment by ntherning** [comment]
I'm afraid we're not going to do anything like this.
