### ISSUE TITLE
Cannot launch iPhone-5s simulator in Eclipse

### ISSUE THREAD

**Issue by lkeepdigging** [robovm/robovm#709]
I used https://github.com/robovm/robovm-gradle-plugin instructions and set gradle.properties:

robovm.device.name=iPhone-5s

[I tried editing the top level version as well as ios dir, but made no difference and I don't think there's any typo since I copied and paste from the URL above.]

And then I refreshed (F5) all related projects and then right menu Gradle -> Refresh all and then cleaned all related projects (menu Projects -> Clean).  Finally, I right menu Run -> Simulator iPhone and it still launches iPhone 4s.

Is there some other settings I should change?  .cache to clean?

I'm using beta3 of robovm, Eclipse plugin is:

  RoboVM for Eclipse	1.0.0.201501141135	org.robovm.eclipse.feature.feature.group	Trillian Mobile AB

The messages for robovm console [last few lines before launching]:

1/18/15 7:50:41 PM: [DEBUG] Copying resource /Users/lkeepdigging/Desktop/Dev/Apps/testapp/ios/data/iTunesArtwork@2x.png to /Users/lkeepdigging/Documents/workspace/.metadata/.plugins/org.robovm.eclipse.ui/build/testapp-ios/testapp-ios (2)/ios/x86/IOSLauncher.app
1/18/15 7:50:41 PM: [DEBUG] Installing Info.plist to /Users/lkeepdigging/Documents/workspace/.metadata/.plugins/org.robovm.eclipse.ui/build/testapp-ios/testapp-ios (2)/ios/x86/IOSLauncher.app
1/18/15 7:50:41 PM: [DEBUG] xcrun dsymutil -o "/Users/lkeepdigging/Documents/workspace/.metadata/.plugins/org.robovm.eclipse.ui/build/testapp-ios/testapp-ios (2)/ios/x86/IOSLauncher.app.dSYM" "/Users/lkeepdigging/Documents/workspace/.metadata/.plugins/org.robovm.eclipse.ui/build/testapp-ios/testapp-ios (2)/ios/x86/IOSLauncher.app/IOSLauncher"
1/18/15 7:50:43 PM: [DEBUG] /Users/lkeepdigging/Documents/workspace/.metadata/.plugins/org.robovm.eclipse.ui/robovm-1.0.0-beta-03/bin/ios-sim launch "/Users/lkeepdigging/Documents/workspace/.metadata/.plugins/org.robovm.eclipse.ui/build/testapp-ios/testapp-ios (2)/ios/x86/IOSLauncher.app" --timeout 90 --unbuffered --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 8.1" --stdout /var/folders/j6/ydrx2c257jjbwj5tx7bw8v100000gn/T/robovm-stdout-738561314614418260.fifo --stderr /var/folders/j6/ydrx2c257jjbwj5tx7bw8v100000gn/T/robovm-stderr-6725434821697061599.fifo --args -rvm:log=warn
1/18/15 7:50:43 PM: [ INFO] Launch done

(Using the command line "../gradlew -Probovm.arch=x86_64 -Probovm.device.name=iPhone-5s launchIPhoneSimulator" works correctly, however.)

And I'm using libgdx 1.5.0.

And I'm running on MacBook Pro 2014 Retina [16GB RAM, 256GB HDD] with Mac 10.10 (Yosemite).
Thanks!

**Comment by ntherning** [comment]
You are launching using "Run as" in eclipse which has nothing to do with
gradle. You need to open " Run configurations" in eclipse's menu, locate
your launch configuration under "iOS Simulator" and change the device type
there.

**Comment by lkeepdigging** [comment]
Thanks, that did the trick.  Would be nice if someone would update the README....
