### ISSUE TITLE
No @Marshaler found for return type of @Callback method

### ISSUE THREAD

**Issue by Endos** [robovm/robovm#710]
I just updated to the last snapshot version and when I try to make a package with the "Package for App Store/Ad-Hoc Distibution..." option it raises the following error:

Packaging failed. Check the RoboVM console for more information.
No @Marshaler found for return type of @Callback method <org.robovm.apple.foundation.NSBundle: java.lang.Class $cb$principalClass(org.robovm.apple.foundation.NSBundle,org.robovm.objc.Selector)

It doesn't matter if I select 32 bit, 64 bit or all. It works fine with the run on the "iOS device app" option, the problem only raises on the packaging option.

**Comment by BlueRiverInteractive** [comment]
We already added ObjCClass to Class<?> marshaling with the last beta version. Could you try to clear your robovm cache? Also if you are using Gradle, please note that it is still necessary that you update the RoboVM Eclipse plugin to the latest snapshot version too.

**Comment by Endos** [comment]
Yes, I'm using Gradle, but I already have the last RoboVM Eclipse snapshot plugin installed. I tried again after deleting the cache folder in $HOME/.robovm but the same error happens. It stops when it try to compile the org.robovm.apple.foundation.NSBundle class.

**Comment by ntherning** [comment]
Could be due to Gradle's caching of snapshot dependencies. Please try to force Gradle to download all dependencies or delete the Gradle cache as described here: http://stackoverflow.com/questions/13565082/how-can-i-force-gradle-to-redownload-dependencies.

**Comment by Endos** [comment]
Thanks ntherning, yesterday I was able to solve the problem by deleting the Gradle cache and going back to the beta 3 version. Now it works.
