### ISSUE TITLE
UIKit causes App to crash  

### ISSUE THREAD

**Issue by Asafmo** [robovm/robovm#711]
So I made several test and I'm 95% sure that something is wrong with the UIKit in the new beta-03.

** I think it's happening when two UI elements are being used and the didBecomeActive() method is overriden I tried it with those two and it crashed:

1. Open app -> Open share panel -> use IAP.
2. Open app -> Open activity view controller -> Open share panel -> Repeat 2 times

The app crashes with the following message:
"The app crashed: Terminated due to signal 6. Check the device logs in Xcode (Window->Devices) for more info."

I added an Symbolicated crash log to to google group.
https://groups.google.com/forum/#!topic/robovm/Kgl1bhSVJjU

**Comment by BlueRiverInteractive** [comment]
Is this still an issue with the latest snapshot versions of RoboVM?

**Comment by ntherning** [comment]
We will close this now. Please retest your code with the latest RoboVM and reopen if you still see this issue. Also attach a device crash log with symbols if you reopen this issue.
