### ISSUE TITLE
Http requests failing in distribution.

### ISSUE THREAD

**Issue by cachucan** [robovm/robovm#712]
Hello,
I'm currently using libGDX and RoboVM to make Http requests. Everything works great in development, however when building to distribution, the HttpResponseListener fails silently, giving no success, failure, or cancelled response. To do a direct RoboVM smoke test, I use the HttpURLConnection to connect to the web. I am able to recreate the issue, as the connection returns data in development, but fails when built for distribution.

<code>
		URL url;
		try {
			url = new URL("http://www.android.com/");
			HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();
			InputStream in = new BufferedInputStream(urlConnection.getInputStream());
		    Gdx.app.log("isogame", ""+in.read());
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
</code>

In development, this will return a valid result, however when built for distribution, the application will exit with status 1.

<code>
<Error>: (UIKitApplication:net.jbgaming.beastbound[0xce79]) Exited with code: 1
Jan 19 17:10:37  <Warning>: Application 'UIKitApplication:net.jbgaming.beastbound[0xce79]' exited abnormally with exit status 1
</code>

Everything was working great last time I sent a distribution build out (12-31-14). I update regularly to the robovm-eclipse plugin nightlies and snapshots. I've also tried uninstalling and reinstalling RoboVM with the same results repeatedly.

Here is my build.gradle:
<code>
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.13+'
        classpath 'org.robovm:robovm-gradle-plugin:1.0.0-beta-03'
    }
}

allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

    version = '1.0'
    ext {
        appName = 'taphero'
        gdxVersion = '1.5.4-SNAPSHOT'
        roboVMVersion = '1.0.0-SNAPSHOT'
    }

    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
    }
}

project(":desktop") {
    apply plugin: "java"

    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    }
}

project(":android") {
    apply plugin: "android"

    configurations { natives }

    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86"
        compile fileTree(dir: '../libs', include: '*.jar')
    }
}

project(":ios") {
    apply plugin: "java"
    apply plugin: "robovm"

    configurations { natives }

    dependencies {
        compile project(":core")
        compile "org.robovm:robovm-rt:${roboVMVersion}"
        compile "org.robovm:robovm-cocoatouch:${roboVMVersion}"
        compile "com.badlogicgames.gdx:gdx-backend-robovm:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
    }
}

project(":core") {
    apply plugin: "java"

    dependencies {
        compile "com.badlogicgames.gdx:gdx:$gdxVersion"
        compile fileTree(dir: 'libs', include: '*.jar')
    }
}

tasks.eclipse.doLast {
    delete ".project"
}
</code>

Thanks.

**Comment by cachucan** [comment]
This morning I resolved the issue by switching my buildscript classpath 'org.robovm:robovm-gradle-plugin:1.0.0-beta-03' to classpath 'org.robovm:robovm-gradle-plugin:1.0.0-beta-01'. Seems like something is broken in beta-03.

**Comment by ldthai** [comment]
i have same problem :(

**Comment by bradfail** [comment]
I have the problem as well, http requests work when using launchIOSDevice but when using createIPA no network connections work

**Comment by BlueRiverInteractive** [comment]
This is probably the same as #715 and should have been fixed now. Please retry with the latest snapshot version.

**Comment by cachucan** [comment]
This issue is resolved for me as far as I can tell, as I started using beta-03 again and most updated RoboVM-Eclipse plugin. Thanks for your support.

**Comment by AmazingDreams** [comment]
Confirmed this works for LibGDX 1.5.4-SNAPSHOT, RoboVM-1.0.0-SNAPSHOT and the nightly build of the Eclipse plugin. Though only works for thumbv7-only releases (or devices using the thumbv7 binary of a combined build). Which means that Apple won't accept the IPA into the app store as they now enforce both thumbv7 and arm64 builds to be included.

**Comment by ntherning** [comment]
@AmazingDreams The ARM64 problems with HTTPS was fixed in #739. Please try with the latest nightly.
