### ISSUE TITLE
java.lang.ClassCastException with CGBitmapContext

### ISSUE THREAD

**Issue by lordofdest** [robovm/robovm#728]
```
import org.robovm.apple.coregraphics.CGBitmapContext;
import org.robovm.apple.coregraphics.CGBitmapInfo;
import org.robovm.apple.coregraphics.CGColorSpace;
import org.robovm.apple.coregraphics.CGImageAlphaInfo;

public class Sample
{
    public abstract class Context<GC> {
        public void drawInContext(GC context)
        {
            System.out.println("Context::draw");
        }

        public abstract GC gc();
    }

    public class BitmapContext extends Context<CGBitmapContext> {
        CGBitmapContext nativeContext;

        public BitmapContext()
        {
            nativeContext = CGBitmapContext.create(10, 10, 8, 0, CGColorSpace.createDeviceRGB(), new CGBitmapInfo(CGImageAlphaInfo.PremultipliedFirst.value()));
        }

        @Override
        public void drawInContext(CGBitmapContext context) {
            System.out.println("BitmapContext::draw");
        }

        @Override
        public CGBitmapContext gc() {
            return nativeContext;
        }
    }

    public class Client {
        Context bitmapContext;

        public Client() {
            bitmapContext = new BitmapContext();
        }

        public void doSomethings() {
            bitmapContext.drawInContext(bitmapContext.gc());
        }
    }

    public Sample() {
        System.out.println("BitmapContext class: " + bitmapContext.getClass().getGenericSuperclass().toString());
        System.out.println("BitmapContext class: " + bitmapContext.gc().getClass().toString());
        new Client().doSomethings();
    }
}
```

Message in console:
[DEBUG] BitmapContext class: com.sample.Sample$Context"org.robovm.apple.coregraphics.CGBitmapContext"
[DEBUG] BitmapContext class: class org.robovm.apple.coregraphics.CGContext
[ERROR] java.lang.ClassCastException: org.robovm.apple.coregraphics.CGContext cannot be cast to org.robovm.apple.coregraphics.CGBitmapContext

Affected versions:
robovm-1.0.0-beta3.
robovm-1.0.0-SNAPSHOT.

Additional info:
PlayN framework also affected by this issue.

**Comment by ntherning** [comment]
Thanks for the report. Do you have a stack trace for us? Get a beta license key by clicking the link on www.robovm.com and filling out the form if you don't have one already. Then clear your cache (`rm -rf ~/.robovm/cache/`) and rerun your test app and you should get line numbers in stack traces.

My guess is that it is this code in `CFType.Marshaler` that is the problem:

```java
static CFType toObject(Class<? extends CFType> cls, long handle, long flags, boolean retain) {
    if (handle == 0) {
        return null;
    }
    long typeId = getTypeID(handle);
    Class<? extends CFType> cfTypeClass = allCFTypeClasses.get(typeId);
    if (cfTypeClass != null) {
        cls = cfTypeClass;
    }
    CFType o = (CFType) NativeObject.Marshaler.toObject(cls, handle, flags);
    if (retain) {
        retain(handle);
    }
    return o;
}
```

We should not override `cls` if it's a subclass of the `cfTypeClass`. This (I guess) causes the `CGBitmapContext.create()` method to actually return a `CGContext` which is the superclass of `CGBitmapContext`.

**Comment by BlueRiverInteractive** [comment]
I cannot reproduce that ClassCastException. I've also checked what types get passed into the `CFType.Marshaler` and both `cls` and `cfTypeClass` are `org.robovm.apple.coregraphics.CGBitmapContext`.

**Comment by lordofdest** [comment]
CNR on latest SNAPSHOT.
