### ISSUE TITLE
Java Abstract Base Class methods compile in eclipse seem to disappear from concrete subclasses at runtime

### ISSUE THREAD

**Issue by mpedrosa** [robovm/robovm#729]
In my application, I have an abstract base class that provides some generic services which then get extended and added to by a concrete subclass.

At runtime, when the subclass tries to access its abstract super-class methods, I get an exception saying the methods don't exist and the app crashes.

This seems to happen on device and on the simulator, but is intermittent.  Sometimes RoboVM seems to get stuck in this problem, then it goes away.

Interestingly, making the base class non abstract seems to solve this problem, but this is not always viable.

Also Interestingly, classes compiled using this pattern externally and included from a jar into the project don't seem to exhibit the same problem.

Here's a simple example of what I mean:

public abstract class A {

    public void doIt(){
        // does something
    }
}

public class B extends A {

    public void doItSomeMore(){
        // does something else
    }

}

public void main( ){

    B b = new B();

   b.doIt();  // --> causes runtime exception : cannot fine member doIt()

}

**Comment by ntherning** [comment]
I'd be very surprised if we didn't handle this correctly. We use an extensive test suite (written by IBM for their drlvm JVM) that tests for the expected JVM behavior including things like this. You probably have some problem with your classpath that maybe causes an old version of A to be used or something. I just tried this:

```java
public abstract class A {
    public void doIt() {
        System.out.println("In A.doIt()");
    }
}
```

```java
public class B extends A {
    public void doItSomeMore() {
        System.out.println("In B.doItSomeMore()");
    }
}
```

```java
public class Main {
    public static void main(String[] args) {
        B b = new B();
        b.doIt();
        b.doItSomeMore();
    }
}
```

It prints out 

```
In A.doIt()
In B.doItSomeMore()
```

Both when running in Oracle's JVM and in RoboVM.

If you can reproduce this issue than please wrap it up as an Eclipse project that I can run and see what happens.

**Comment by mpedrosa** [comment]
I'm as surprised as you!  I'll check to see that I'm using oracle's JVM and not the old apple one (which is possible).

In the meantime, any hints on clearing out any hidden compiled class caches that RoboVM may be using?  If the problem is some stale class as you suggest, maybe I can just clear it out?  Doing a clean from eclipse doesn't seem to do the trick.

Oh the other wrinkle, in case it may be relevant, is that the abstract base class exists in one project and then is made concrete in another.

If I can get this to reproduce in a simple project  I'll provide it for you to inspect.

**Comment by ntherning** [comment]
I'm going to close this issue now. If you can reproduce then please reopen and provide a test case.
