### ISSUE TITLE
New projects should include placeholder icons and splash screens

### ISSUE THREAD

**Issue by mpedrosa** [robovm/robovm#730]
This is a feature request.  Everyone is going to want to have splash screens and icons for all supported devices, why not have empty placeholders generated as part of a new RoboVM project?

**Comment by ntherning** [comment]
Yes, we should have this. Will add it to the 1.0 milestone.

**Comment by BlueRiverInteractive** [comment]
I think a black background with the white RoboVM logo centered would look good. The same for the app icon but without text. What do you think?

Do we have the logo as vector somewhere? I could setup the various icons and launch images and add it to the Eclipse plugin project wizard. Also using tinypng.com to reduce the filesize to a minimum.

**Comment by ntherning** [comment]
+1. I'll send you the logo shortly.

**Comment by BlueRiverInteractive** [comment]
New app icons and launch images have been added to the sample apps: https://github.com/robovm/robovm-samples/commit/9eefc4ab291b3ae4c4fccc93353746b9eea7a496

**Comment by badlogic** [comment]
Awesome! Towards a polished platform :)

**Comment by BlueRiverInteractive** [comment]
The new icons indeed look really cool :)
