### ISSUE TITLE
CoreGraphics bindings broken in latest build

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#741]
I've updated to the latest master version which contains commits for changes to the bindings. After clearing the cache and recompiling the BatteryStatusApp i get the following when compiling the `org.robovm.apple.coregraphics.CGDataProvider` class:

```
An internal error occurred during: "Launching BatteryStatus device".
@Marshaler org.robovm.apple.corefoundation.CFType$NoRetainMarshaler specified for return type of @Bridge method <org.robovm.apple.coregraphics.CGDataProvider: org.robovm.apple.foundation.NSData getData()> can not be used to marshal org.robovm.apple.foundation.NSData
```

@BlueRiverInteractive could you take a look at this?

**Comment by BlueRiverInteractive** [comment]
Totally missed that one. Thanks!
