### ISSUE TITLE
Compiler fails to compile all classes

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#745]
With the latest nightly the RoboVM class compiler is now ultra fast but misses several classes to compile. For example it compiles VoidBlock1, VoidBlock3, VoidBlock4 but skips VoidBlock2. After the compiler finishes it tries to link all classes but fails because of VoidBlock2 missing. Had to restart the compiler 4 times to make a simple test app start.

These are examples of the errors that I get after the compiler finished without compiling all classes:
```
ld: file not found: /Users/Haslinger/.robovm/cache/ios/thumbv7/release/Users/Haslinger/development/.metadata/.plugins/org.robovm.eclipse.ui/robovm-1.0.0-SNAPSHOT/lib/robovm-rt.jar/java/nio/channels/AsynchronousCloseException.class.o
ld: file not found: /Users/Haslinger/.robovm/cache/ios/thumbv7/release/Users/Haslinger/development/.metadata/.plugins/org.robovm.eclipse.ui/robovm-1.0.0-SNAPSHOT/lib/robovm-rt.jar/dalvik/system/BlockGuard$1.class.o
ld: file not found: /Users/Haslinger/.robovm/cache/ios/thumbv7/release/Users/Haslinger/development/.metadata/.plugins/org.robovm.eclipse.ui/robovm-1.0.0-SNAPSHOT/lib/robovm-cocoatouch.jar/org/robovm/apple/coreanimation/CALayerDelegate.class.o
```

**Comment by ntherning** [comment]
Are you running from the command line, using the Eclipse plugin or Maven/Gradle?

**Comment by BlueRiverInteractive** [comment]
Eclipse

Von meinem iPhone gesendet

**Comment by ntherning** [comment]
Ok. I am able to reproduce it.

**Comment by ntherning** [comment]
I believe this is fixed now. A new build is currently running. Please try with the next nightly and close this if it works better now.

**Comment by BlueRiverInteractive** [comment]
Works as expected now. Thanks!
