### ISSUE TITLE
Use toll-free bridged Foundation object in place of CoreFoundation objects wherever possible

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#750]
We should take a look at all C frameworks again and be sure to replace toll-free bridged CF objects.

The following list shows most of the toll-free bridged CF classes and their Foundation counterpart:

CoreFoundation | Foundation
---------------------|-----------------
CFArray | NSArray
CFAttributedString | NSAttributedString
CFCalendar | NSCalendar
CFCharacterSet | NSCharacterSet
CFData | NSData
CFDate | NSDate
CFDictionary | NSDictionary
CFError | NSError
CFLocale | NSLocale
CFMutableArray | NSMutableArray
CFMutableAttributedString | NSMutableAttributedString
CFMutableCharacterSet | NSMutableCharacterSet
CFMutableData | NSMutableData
CFMutableDictionary | NSMutableDictionary
CFMutableSet | NSMutableSet
CFMutableString | NSMutableString
CFNumber | NSNumber
CFReadStream | NSInputStream
CFRunLoopTimer | NSTimer
CFSet | NSSet
CFString | NSString
CFTimeZone | NSTimeZone
CFURL | NSURL
CFWriteStream | NSOutputStream

**Comment by ntherning** [comment]
I see that we now use `String` instead of `CFString` in a lot of places which is really nice! Just need to make sure we use the correct marshaler (`NSString.AsStrinMarshaler`). Do we?
