### ISSUE TITLE
Use clang to generate @Bridge/@Callback methods

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#754]
This should make sure once and for all that we pass and return structs by value according to all the ABIs we support. Should fix #742.

**Comment by kirillp** [comment]
I made  a brief unprofessional view on the change  and have a question:

as far as I get you create a local variable on the stack via alloca and then invoke the method and copy the result to a heap object. It is possible to invoke the method directly with the pointer to heap object avoiding the unnecessary copy ?

**Comment by ntherning** [comment]
Yes, you are right about that. The way we do it now matches what we had before. The stack allocation won't make much difference but preventing the copying could make a difference. I will open another issue for that optimization.
