### ISSUE TITLE
Code using completion blocks and dispatch queues shows occasional crash or erratic behaviour

### ISSUE THREAD

**Issue by mpr90** [robovm/robovm#757]
In a [test application](https://groups.google.com/group/robovm/attach/7f2875fd8212249a/twiosreverseauthexample-clean.tar.gz?part=0.1&authuser=0) that makes use of both completion blocks for iOS callbacks and dispatch queues, get two types of problems:
1. Application crashes when completion block is called
2. Runnable called on a dispatch queue never executes

The test application that is a port of [this](https://github.com/seancook/TWReverseAuthExample) to Java/RoboVM which performs a reverse OAuth with a Twitter account previously set up in iOS. The app will need an application key from Twitter to function. Get one by going to https://apps.twitter.com/. Take the Consumer Key and Consumer Secret from Twitter and put them in the TWSignedRequest.java (at the end of the file).

The problems can be reproduced by repeatedly clicking the "Authorize Twitter" button, selecting a Twitter account, and clicking OK in the resulting dialogue that presents the OAuth keys. 

Sometimes, the indeterminate progress spinner will spin forever and you don't get the resulting dialogue, meaning that the block of code below from line 51 of TWAPIManager.java didn't run.

```java
    DispatchQueue.getGlobalQueue(DispatchQueue.PRIORITY_DEFAULT, 0).async(new Runnable() {
      @Override
      public void run() {
        try {
          if (TWUtils.DEBUG) System.out.println("TWAPIManager: Step 1: bg block, result on global Q: " + result);
```

Other times, I have been able to get the application to crash (excerpt of crash log below) by performing the same sequence, often as many as 20 times before the problem occurs.

```
Thread 13 name:  Dispatch queue: NSOperationQueue 0x14f134c0 :: NSOperation 0x14f1dbf0
Thread 13 Crashed:
0   libsystem_kernel.dylib          0x39a2bdfc __pthread_kill + 8
1   libsystem_pthread.dylib         0x39aabd0e pthread_kill + 58
2   libsystem_c.dylib               0x399cb934 abort + 72
3   twiosreverseauth                0x00902dc6 rvmAbort + 58
4   twiosreverseauth                0x0090963c rvmLockObject + 20
5   twiosreverseauth                0x008fc31c _bcMonitorEnter + 24
6   twiosreverseauth                0x008df318 [J]org.robovm.objc.ObjCObject.toObjCObject(Ljava/lang/Class;JZ)Lorg/robovm/objc/ObjCObject; (/ObjCObject.java:258)
7   twiosreverseauth                0x008df210 [J]org.robovm.objc.ObjCObject.toObjCObject(Ljava/lang/Class;J)Lorg/robovm/objc/ObjCObject; (/ObjCObject.java:246)
8   twiosreverseauth                0x008df24a [j]org.robovm.objc.ObjCObject.toObjCObject(Ljava/lang/Class;J)Lorg/robovm/objc/ObjCObject;[clinit] + 50
9   twiosreverseauth                0x005e9c08 [J]org.robovm.apple.foundation.NSObject$Marshaler.toObject(Ljava/lang/Class;JJ)Lorg/robovm/apple/foundation/NSObject; + 16
10  twiosreverseauth                0x005e9c58 [j]org.robovm.apple.foundation.NSObject$Marshaler.toObject(Ljava/lang/Class;JJ)Lorg/robovm/apple/foundation/NSObject;[clinit] + 64
11  twiosreverseauth                0x00629d36 [j]org.robovm.apple.foundation.NSURLConnection$$BlockMarshaler0.invoked(Lorg/robovm/objc/ObjCBlock;Lorg/robovm/apple/foundation/NSURLResponse;Lorg/robovm/apple/foundation/NSData;Lorg/robovm/apple/foundation/NSError;)V[callback] + 102
12  CFNetwork                       0x2b3430be __67+[NSURLConnection sendAsynchronousRequest:queue:completionHandler:]_block_invoke_2 + 142
13  Foundation                      0x2c57a0fa __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 6
14  Foundation                      0x2c4e4fc0 -[NSBlockOperation main] + 144
15  Foundation                      0x2c4d7840 -[__NSOperationInternal _start:] + 764
16  Foundation                      0x2c57ca52 __NSOQSchedule_f + 182
17  libdispatch.dylib               0x399355d4 _dispatch_queue_drain$VARIANT$mp + 944
18  libdispatch.dylib               0x399350a4 _dispatch_queue_invoke$VARIANT$mp + 80
19  libdispatch.dylib               0x399370d0 _dispatch_root_queue_drain + 328
20  libdispatch.dylib               0x399381f6 _dispatch_worker_thread3 + 102
21  libsystem_pthread.dylib         0x39aa8e22 _pthread_wqthread + 666
22  libsystem_pthread.dylib         0x39aa8b74 start_wqthread + 4
```
Note: Testing a reproduction was done with both robovm-beta-03 and robovm-nightly-1.0.0.201501281459, using iPad 3rd generation with iOS 8.1.2

**Comment by mpr90** [comment]
Could be that this is caused by the same problems descried in #817 and #818? Sounds awfully similar...

**Comment by ntherning** [comment]
@mpr90 Does indeed look similar to #817 (and perhaps #818). The #817 we have pushed a fix for. Please [try the latest nightly build](http://docs.robovm.com/user/latest/#nightly-builds) and let us know if your issue is still there or not.

**Comment by mpr90** [comment]
I ran the same test with 1.0.0.201503060129 and was unable to get the problem to reproduce. Since it was a little elusive to reproduce with this test case, I'll tentatively say "good news" and "thanks!" and keep watching to see if the problem truly has gone.
