### ISSUE TITLE
RxJava concurrency crash

### ISSUE THREAD

**Issue by rapropos** [robovm/robovm#766]
RxJava is crashing consistently on device for me. I believe I have isolated the problem to the case where multiple producers and consumers are present, which causes use of an internal rx class that uses sun.misc.Unsafe operations when available. Please see the testbench project at https://github.com/rapropos/roboretro for details. Alternately comment out the calls to `register1()` and `register2()` to see the working and crashing cases. A symbolicated crash log is included in the file "symbocrash.txt".

I hope this is sufficient information. I don't have a lot of experience writing these issue reports, so please let me know if anything else is needed. Also, thank you for all your work on RoboVM.

**Comment by ntherning** [comment]
I just pushed a fix for a very similar issue in #987. Please try with the next nightly build (20150520) and let us know if your issue is fixed. See http://docs.robovm.com/advanced-topics/nightlies.html for instructions on how to use nightly builds.

**Comment by ntherning** [comment]
This has been fixed now in the latest nightlies.
