### ISSUE TITLE
Running app on simulator the second time fails

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#771]
Create a simple IOSDemo project in Eclipse, then start it, kill it in Eclipse, start it again. You'll see an error like this:

```
2/12/15 2:29:38 PM: [ERROR] Session could not be started: Error Domain=LaunchServicesError Code=0 "Unable to run app in Simulator" UserInfo=0x7f89b231e5b0 {Error=PackagePatchFailed, ErrorDescription=Could not hardlink copy /Users/badlogic/Library/Developer/CoreSimulator/Devices/936A40C1-3CB4-4139-9264-00784DCB75C6/data/Containers/Bundle/Application/6F6CAD49-57A7-4784-8E5C-ECC8C8286A01/IOSLauncher.app to /Users/badlogic/Library/Developer/CoreSimulator/Devices/936A40C1-3CB4-4139-9264-00784DCB75C6/data/Library/Caches/com.apple.mobile.installd.staging/temp.77mtZA/extracted/Payload/IOSLauncher.app with manifest /Users/badlogic/Library/Developer/CoreSimulator/Devices/936A40C1-3CB4-4139-9264-00784DCB75C6/data/Library/Caches/com.apple.mobile.installd.staging/temp.77mtZA/extracted/com.apple.deltainstallcommands.com.badlogic.invaders.IOSLauncher, NSLocalizedFailureReason=An error was encountered while running (Domain = LaunchServicesError, Code = 0), NSUnderlyingError=0x7f89b2202d60 "The operation couldn’t be completed. (LaunchServicesError error 0.)", NSLocalizedDescription=Unable to run app in Simulator}

```

**Comment by badlogic** [comment]
Seems like this is something that's going to be fixed in the next XCode release: http://stackoverflow.com/a/28144405/729460

**Comment by ntherning** [comment]
Dug into this a bit and compared the simulator logs of a [successful relaunch of an app from Xcode](https://gist.github.com/ntherning/2a00174382fc4dabb38b) with a [failed relaunch of a RoboVM app](https://gist.github.com/ntherning/63785ed29fba30d9c65f) (the HelloWorld sample). The logs start to differ from these lines:

```
Feb 21 09:34:15 Niklas-MacBookPro.local installd[23298]: 0x110f41000 writeDictToFile: ==== Successfully wrote Manifest cache to /Users/niklas/Library/Developer/CoreSimulator/Devices/E016D674-55BB-4FD0-ABA9-A4573FB44E54/data/Library/Caches/com.apple.mobile.installd.staging/temp.HlrtuU/extracted/ManifestCache.plist
Feb 21 09:34:15 Niklas-MacBookPro.local installd[23298]: 0x10efa7000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundlePatch ID=org.robovm.yada.Yada; Version=1, ShortVersion=1.0>
Feb 21 09:34:15 Niklas-MacBookPro.local installd[23298]: 0x10efa7000 -[MIInstallableBundlePatch applyPatchWithError:]: Attempting patch update of org.robovm.yada.Yada from 1 (1.0) to 1 (1.0)
```

```
Feb 21 09:38:07 Niklas-MacBookPro.local installd[24212]: 0xb0115000 writeDictToFile: ==== Successfully wrote Manifest cache to /Users/niklas/Library/Developer/CoreSimulator/Devices/25321885-9CE5-4231-86DD-AAD81862BCF8/data/Library/Caches/com.apple.mobile.installd.staging/temp.m0dMkl/extracted/ManifestCache.plist
Feb 21 09:38:07 Niklas-MacBookPro.local installd[24212]: 0xb0197000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundlePatch ID=org.robovm.samples.helloworld; Version=1, ShortVersion=(null)>
Feb 21 09:38:07 Niklas-MacBookPro.local installd[24212]: 0xb0197000 -[MIInstallableBundlePatch applyPatchWithError:]: Attempting patch update of org.robovm.samples.helloworld from 1 ((null)) to 1 ((null))
Feb 21 09:38:07 Niklas-MacBookPro.local installd[24212]: 0xb0197000 validate_stream: Got manifest for version "1 1.0", but expected version "1 "
Feb 21 09:38:07 Niklas-MacBookPro.local installd[24212]: 0xb0197000 open_delta_manifest: Invalid manifest file at /Users/niklas/Library/Developer/CoreSimulator/Devices/25321885-9CE5-4231-86DD-AAD81862BCF8/data/Library/Caches/com.apple.mobile.installd.staging/temp.m0dMkl/extracted/com.apple.deltainstallcommands.org.robovm.samples.helloworld
Feb 21 09:38:07 Niklas-MacBookPro.local installd[24212]: 0xb0197000 hardlink_copy_hierarchy: Failed to open manifest /Users/niklas/Library/Developer/CoreSimulator/Devices/25321885-9CE5-4231-86DD-AAD81862BCF8/data/Library/Caches/com.apple.mobile.installd.staging/temp.m0dMkl/extracted/com.apple.deltainstallcommands.org.robovm.samples.helloworld
Feb 21 09:38:07 Niklas-MacBookPro.local installd[24212]: 0xb0197000 -[MIInstallableBundlePatch applyPatchWithError:]: 82: Could not hardlink copy /Users/niklas/Library/Developer/CoreSimulator/Devices/25321885-9CE5-4231-86DD-AAD81862BCF8/data/Containers/Bundle/Application/8EE69ABC-22CF-4351-B356-BA049172F13E/HelloWorld.app to /Users/niklas/Library/Developer/CoreSimulator/Devices/25321885-9CE5-4231-86DD-AAD81862BCF8/data/Library/Caches/com.apple.mobile.installd.staging/temp.m0dMkl/extracted/Payload/HelloWorld.app with manifest /Users/niklas/Library/Developer/CoreSimulator/Devices/25321885-9CE5-4231-86DD-AAD81862BCF8/data/Library/Caches/com.apple.mobile.installd.staging/temp.m0dMkl/extracted/com.apple.deltainstallcommands.org.robovm.samples.helloworld
```

Both apps have `CFBundleVersion=1` and `CFBundleShortVersionString=1.0` but for some reason the log says `ShortVersion=(null)` for our app while it says `ShortVersion=1.0` for the Xcode app. Maybe there's something up with our default `Info.plist.xml` file?

**Comment by ntherning** [comment]
So if I change the `Info.plist.xml` file in the HelloWorld sample and move the `CFBundleShortVersionString` and `CFBundleVersion` to the top the problem goes away. I suspect that there's something about the binary plist files we generate and some bug in `installd` that gets triggered in some situation depending on the order of the keys. `plutil` and Finder displays the keys and values of the `Info.plist` we generate without any problem so there must be some problem in `installd`. Here's a diff of a good (left) and bad (right) `Info.plist` for HelloWorld that we generate:

![screen shot 2015-02-21 at 11 11 41](https://cloud.githubusercontent.com/assets/135765/6313711/2007551e-b9bb-11e4-991e-ae0e5dd061ff.png)

**Comment by ntherning** [comment]
As long as `CFBundleShortVersionString` and `CFBundleVersion` comes before the `UIDeviceFamily` it works. Xcode doesn't preserve the order of the keys in the Info.plist file like `com.dd.plist` does but rather orders them alphabetically so it's less likely that those version keys will end up after some other key which makes `installd` bug out. Will attempt a workaround which makes sure that the version keys are always at the top.

**Comment by cbeams** [comment]
@ntherning I'm seeing this issue against 1.0.0-beta-04 when running the `HelloWorld` sample via grade at the command line and from within IDEA using the IDEA RoboVM plugin. Great to see it was fixed just ahead of my first running into it :)

I'd like to try out the fix, but after a brief look through your docs, I don't know if or where you're publishing snapshot builds. Are there any, or shall I build from source?

P.S. RoboVM looks fantastic. Excited to explore further.

**Comment by cbeams** [comment]
> I don't know if or where you're publishing snapshots

Never mind. I see now that you're [publishing snapshots to OSO](https://oss.sonatype.org/content/repositories/snapshots/org/robovm). However, given that the timestamp on [`robovm-compiler`'s latest snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/robovm/robovm-compiler/) is about 24 hours old, it looks like publication happens nightly as opposed to continuously?

**Comment by cbeams** [comment]
@ntherning I've built from source and can confirm the fix works, i.e. I no longer see the "Unable to run app in Simulator" error when running as an iOS Application within IDEA.

I'm also now able to launch the simulator from from grade at command line without the error, but only if I pass the `-Probovm.sdk.version={x.y} -Probovm.device.name={name}` properties.

For example, if I simply run `gradle launchIPhoneSimulator`:
```
$ gradle launchIPhoneSimulator
:launchIPhoneSimulator
Session could not be started: Error Domain=LaunchServicesError Code=0 "Unable to run app in Simulator" UserInfo=0x7fcf1162a470 {Error=PackagePatchFailed, ErrorDescription=Could not hardlink copy /Users/cbeams/Library/Developer/CoreSimulator/Devices/F66D6DE7-EACC-41AF-8283-2FA76F314F7A/data/Containers/Bundle/Application/5AD7BF30-8B2B-4046-8A4C-5AE546C4463A/HelloWorld.app to /Users/cbeams/Library/Developer/CoreSimulator/Devices/F66D6DE7-EACC-41AF-8283-2FA76F314F7A/data/Library/Caches/com.apple.mobile.installd.staging/temp.Vmk4iU/extracted/Payload/HelloWorld.app with manifest /Users/cbeams/Library/Developer/CoreSimulator/Devices/F66D6DE7-EACC-41AF-8283-2FA76F314F7A/data/Library/Caches/com.apple.mobile.installd.staging/temp.Vmk4iU/extracted/com.apple.deltainstallcommands.org.robovm.samples.helloworld, NSLocalizedFailureReason=An error was encountered while running (Domain = LaunchServicesError, Code = 0), NSUnderlyingError=0x7fcf1151fd30 "The operation couldn’t be completed. (LaunchServicesError error 0.)", NSLocalizedDescription=Unable to run app in Simulator}
```

And running with the properties mentioned:
```
cbeams@vix:~/Desktop/vault12/etc/robovm-samples/HelloWorld[master]
$ gradle launchIPhoneSimulator -Probovm.sdk.version=8.1 -Probovm.device.name=iPhone-5
:launchIPhoneSimulator

[... simulator comes up; I switch to that window and kill it; the build completes ...]

BUILD SUCCESSFUL

Total time: 23.404 secs
```

**Comment by ntherning** [comment]
My guess is that the default simulator (probably iPhone4s) which you get when not specifying `-Probovm.device.name=...` still has a bad install of the app. Try "Reset content and settings.." in that simulator and then retry the launch and let us know what happens.

**Comment by cbeams** [comment]
That was indeed the problem. Works perfectly now. Thanks.
