### ISSUE TITLE
NSPathUtilities global var serialization/marshalling (e.g. NSPathUtilities.getHomeDirectory())

### ISSUE THREAD

**Issue by mhilbrunner** [robovm/robovm#776]
Hi,

trying to get the values of global variables via the utility methods in [NSPathUtilities.java](https://github.com/robovm/robovm/blob/master/cocoatouch/src/main/java/org/robovm/apple/foundation/NSPathUtilities.java) seems to return dubious return values for me.

E.g. `NSPathUtilities.getHomeDirectory()` returns (as String) "`M�8`" on iOS 8.1, using the latest RoboVM snapshot.

I was trying to get the available disk space, translating things like this for use in Java:
https://github.com/andrealufino/ALSystemUtilities/blob/develop/ALSystemUtilities/ALSystemUtilities/ALDisk/ALDisk.m

But `getAttributesOfFileSystemAtPath(NSPathUtilities.getHomeDirectory())` then of course fails with `Cocoa Error 260`, because it cannot find the path specified.

So a minimal test case would look like this:
```java
public long testGetSize() {
    System.out.println("HOME: " + NSPathUtilities.getHomeDirectory());
    return NSFileManager.getDefaultManager()
           .getAttributesOfFileSystemAtPath(NSPathUtilities.getHomeDirectory())
           .getSize();
}
```

As a workaround, I used `.getAttributesOfFileSystemAtPath(".")` instead, which works for my use case, but it seems like the above should work. Am I missing something?

**Comment by mhilbrunner** [comment]
Turns out it works fine on the same device when I ran from another developer machine. Weir.d

The above now outputs correctly:
`HOME: /var/mobile/Containers/Data/Application/06EEADC9-C20D-4563-A520-BA8A41D5116`

I'll reopen if I can reproduce. Keeping the workaround around for now (heh).

**Comment by BlueRiverInteractive** [comment]
`NSPathUtilities.getHomeDirectory()` is working fine for me on the latest snapshot versions.
It could be that you had some outdated cached files. The old `NSPathUtilities` class was extending from `Object` but the new, fixed class extends from `CocoaUtility`. Just clear `~/.robovm/cache` and rerun your sample.

**Comment by mhilbrunner** [comment]
You're right, works now. Thanks. :)
