### ISSUE TITLE
Use ram disk for cache/tmpdir if there is one available

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#786]
The compile/link times on HDDs could be better. We need to optimize this but in the meantime we could add support for using a RAM disk for the cache and tmpdir. We would tell the user to create a RAM disk using a command like this:

```
SIZE=4096 ; diskutil erasevolume HFS+ 'RoboVM RAM Disk' `hdiutil attach -nomount ram://$((SIZE * 2048))`
```

This creates a 4GB (4096 MB) large RAM disk with the name `RoboVM RAM Disk` and mounts it at `/Volumes/RoboVM RAM Disk`.

We would then in `Config.build()` issue a `mount` command to find any RAM disks with `robovm` in their names, remove the ones we cannot write to, order them by remaining disk space (using `java.nio.file.FileStore.getUsableSpace ()`) and pick the one with most space remaining.

Once we have a RAM disk we can write to we make sure there is a `cache/` and `tmp/` folder on it and we change the `Config.cacheDir` and `Config.tmpDir` to be symbolic links poinint at `cache/` and `tmp/` on the RAM disk.

We should log a notice that we are using the RAM disk for cache and tmpdir. Also, if the space remaining is below some suitable number (like 200 MB?) we should warn the user that the RAM disk has to be cleaned. Or clean it ourselves by deleting everything in `tmp/` and going through all the files in the cache dir and delete the least recently accessed files until there's at least XXX MB left on the disk.

**Comment by badlogic** [comment]
If possible,  the user could try turning on transparent compression on the
RAM disk.

**Comment by ntherning** [comment]
Is there such a thing on HFS+? The only info I found suggested that it had to be done file by file and even that you had to store the file first uncompressed and then flip some switch using a command line tool to have the OS compress it.

**Comment by badlogic** [comment]
You are right, it seems that won't work. I looked into Fuse, that seems to
be very simple to use:
https://github.com/EtiennePerot/fuse-jna/blob/master/src/main/java/net/fusejna/examples/MemoryFS.java

These bindings are slow though, there's another set of Java bindings as
well as bindings for Python etc. Could of course also just do C :)

**Comment by ashleyj** [comment]
I wonder if also [http://ccache.samba.org/](ccache) would help here, especially with the base java classes
