### ISSUE TITLE
OSStatus should be bound as integer wrapping type

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#793]
Currently OSStatus in C frameworks is bound as int or as some custom enum. This is rather chaotic and unsave because there could be a status code that is not in the enum, thus an exception is thrown.

My suggestion is to create a OSStatus class that simply wraps an integer value. The method getStatusCode() gives back the integer code. The method equals() can be used to compare it to an int, another OSStatusCode, or a ValuedEnum. This way we can also keep the status codes enums.

**Comment by BlueRiverInteractive** [comment]
@ntherning This should probably go into 1.0 as it will change the return type of many functions. Any comment?

**Comment by ntherning** [comment]
I approve. Go for it! :-)

**Comment by BlueRiverInteractive** [comment]
Alright!
