### ISSUE TITLE
HFS+ compress object files when using a RAM disk for the cache

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#805]
When using a RAM disk for the cache we need to do whatever we can to preserve disk space. HFS+ has support for compressed files which are decompressed transparently. The source code of [afsctool](https://github.com/jrk/afsctool/blob/master/afsctool.c) gives some pointers on how to compress files. Also found [this](http://wiki.sleuthkit.org/index.php?title=HFS) which gives some details on how the compression is done. The compression is based on zlib so maybe we could even do most of the work in Java and in memory before we touch the disk? Or we could include the `afsctool` tool and invoke that for every (object) file if we are running on a RAM disk.

We need to investigate how much it costs to compress files in terms of CPU. If it slows down the compilation too much we can't do it of course.

Also, we should also consider doing this if the cache is on an HDD as smaller files mean less access to the HDD.

**Comment by badlogic** [comment]
See #811, that uses compression regardless of whether we have a RAM disk or not. Does not exhibit noticeable negative impact on the compile times (1-2 seconds tops for a 130 second compile).

**Comment by badlogic** [comment]
Updated #811 to use libarchive, which is BSD licensed and even a bit faster. The accompanying hfscompressor project can be found at http://github.com/badlogic/hfscompressor. This needs to be moved to the RoboVM organization, for which i do not have permissions.
