### ISSUE TITLE
Only warn about no RAM disk being available if running off an HDD

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#807]
By invoking `diskutil info -plist <device>` and passing `FileStore.name()` we get a plist with a key, `SolidState`, which is `true` if the disk is an SSD. In that case we should not attempt to mount a RAM disk and not log the warning. Should only be done on OSX of course.

**Comment by badlogic** [comment]
We don't mount the ram disk ourselves. The user indicates whether she wants to use a RAM disk by mounting it under the `/Volumes/RoboVM Ram Disk` mount point. Given this, do you think the check is necessary?

**Comment by badlogic** [comment]
See 28886bf8ff9289cfba3d126b17268779e861aa8c, i think that's a good compromising without us having to spawn another process.

**Comment by ntherning** [comment]
What I had in mind was rather to notify the user when running off an HDD that it is known to be slow and mounting a RAM disk can help. Something like `WARN - RoboVM has detected that you are running on a slow HDD. Please consider mounting a RAM disk. See http://www.robovm.com/... for more info`. Without something like this most HDD users will never learn that there's a workaround for the slowness and they might give up on RoboVM.
