### ISSUE TITLE
Strip device executables in debug mode

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#815]

**Comment by ntherning** [comment]
Also in release mode I believe. Stripping release builds shaves off a lot from the executable. E.g.:

before
```
-rwxr-xr-x  1 niklas  staff  56822884 27 Feb 08:58 HelloWorld
```
after
```
-rwxr-xr-x  1 niklas  staff  16374160 27 Feb 11:17 HelloWorld
```

**Comment by badlogic** [comment]
Did some testing, ContractR, 32-bit device, in both release and debug mode. I measure the time between dsym generation and "Launch done". I purge the disk cache via `sudo purge` before each run, for each build i do 3 runs and average. All measurements are taken on my rMBP with SSD.

Build | Time
--- | ---
debug, stripped | 12 secs
debug | 10 secs
release, stripped | 8 secs
release | 6 secs

We get smaller executables, but startup time is slower.

**Comment by ntherning** [comment]
Ok. We need some figures on an HDD as well. But for now we can say that we shouldn't do this.

BTW, I wonder whether the device makes a difference? Is it slower to upload to a slow device?

**Comment by ntherning** [comment]
So conclusion is we don't do this.

**Comment by badlogic** [comment]
well, there is a slight decrease on hdds, but an increase for ssds. We
could special case for hdds. That's only treating the symptoms though.

**Comment by ntherning** [comment]
Not worth the effort.
