### ISSUE TITLE
Crash when signing into Google Play Game Services with robovm 1.0.0-beta-04

### ISSUE THREAD

**Issue by NaN8** [robovm/robovm#820]
I used LibDX 1.5.3 and robovm 1.0.0-beta-03 with google play service and everthing works. When I updated my robovm to 1.0.0-beta-04 and libgdx to 1.5.4 , I now get the following crash after signing-in to google play : [org.robovm.bindings.playservices.PlayServicesManager finishedWithAuth:error:]: unrecognized selector sent to instance 0x168161902015-02-21 00:08:23.886 2DMX-iosrobovm[2143:81972] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[org.robovm.bindings.playservices.PlayServicesManager finishedWithAuth:error:]: unrecognized selector sent to instance 0x16816190'

I have been struggling for a day to understand what is wrong... with no chance to find a solution

**Comment by mhilbrunner** [comment]
'Unrecognized selector sent to instance' means the method you tried to call ('finishedWithAuth:error:') does not exist on that instance (at '0x16816190') of the object ('..PlayServicesManager').

Probably it does not exist anymore at all, either because
1.) the binding is missing
or
2.) it waa renamed / has another signature now

**Comment by badlogic** [comment]
Do you have a project with which we can reproduce the issue?

**Comment by NaN8** [comment]
Thank you all for your help. My error! I had to classes instances extending GPPSignInDelegate, one was not used but probably the wrong finishWithAuth (with PlayServicesManager not fully setup) was called with the new Robovm version.

**Comment by badlogic** [comment]
Cool, thanks for reporting back :)
