### ISSUE TITLE
Crash in ExpatAttributes on 64-bit

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#827]
Probably a pointer which is passed around in an `int`. See https://groups.google.com/d/msg/robovm/vzb_Cnbdheo/HBdIjJQUQRMJ for a crash log.

I found one bad pointer in `ExpatParser.java`. Don't know if this fixes the issue though:

```diff
diff --git a/rt/libcore/luni/src/main/java/org/apache/harmony/xml/ExpatParser.java b/rt/libcore/luni/src/main/java/org/apache/harmony/xml/ExpatParser.java
index db6f4ef..fa6308e 100644
--- a/rt/libcore/luni/src/main/java/org/apache/harmony/xml/ExpatParser.java
+++ b/rt/libcore/luni/src/main/java/org/apache/harmony/xml/ExpatParser.java
@@ -48,7 +48,7 @@ class ExpatParser {

     private boolean inStartElement = false;
     private int attributeCount = -1;
-    private int attributePointer = 0;
+    private long attributePointer = 0;

     private final Locator locator = new ExpatLocator();

@@ -129,7 +129,7 @@ class ExpatParser {
      * @param attributeCount number of attributes
      */
     /*package*/ void startElement(String uri, String localName, String qName,
-            int attributePointer, int attributeCount) throws SAXException {
+            long attributePointer, int attributeCount) throws SAXException {
         ContentHandler contentHandler = xmlReader.contentHandler;
         if (contentHandler == null) {
             return;
@@ -772,7 +772,7 @@ class ExpatParser {

         @Override
         void startElement(String uri, String localName, String qName,
-                int attributePointer, int attributeCount) throws SAXException {
+                long attributePointer, int attributeCount) throws SAXException {
             /*
              * Skip topmost element generated by our workaround in
              * {@link #handleExternalEntity}.
```

**Comment by ebbybeh** [comment]
Hello,

I am getting an error related to this issue as mentioned here: https://groups.google.com/forum/#!topic/robovm/vzb_Cnbdheo

The files are attached to the latest post.

**Comment by badlogic** [comment]
Thanks, i overlooked that list post. 

I was able to reproduce the issue and will look into it. As a side note: libGDX has internationalization support, there's no need to do your own. libGDX also come with a lightweight, fast XML parser. See the libGDX wiki for more information.

**Comment by badlogic** [comment]
`ExpatParser` has a static initializer that calls into a native JNI method. That method looks up and caches instance method handle. For some reason, the JNI `GetMethodID` function fails to find the `startElement`. It's definitely there though:

![http://sht.tl/8VJYBn](http://sht.tl/8VJYBn)

**Comment by badlogic** [comment]
The `ExpatParser#startElement` method has a pointer as an argument. That's an int in our version, which is bad on 64-bit.

**Comment by ebbybeh** [comment]
I'll try using the libgdx xmlparser and see how things go. I had ported my game to Libgdx from AndEngine about a year and a half ago. I assumed some things were similar and parsing XMLs was one of them.

**Comment by ebbybeh** [comment]
Is this fix available in the latest roboVM nightlies?

**Comment by badlogic** [comment]
yes

**Comment by ebbybeh** [comment]
I updated to the latest nightlies and received the following error:
java.lang.NoSuchMethodError: startElement
		at org.apache.harmony.xml.ExpatParser.staticInitialize(Native Method)
		at org.apache.harmony.xml.ExpatParser.<clinit>(ExpatParser.java:576)
		at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:314)
		at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
		at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
		at javax.xml.parsers.SAXParser.parse(SAXParser.java:187)
		at ilmfinity.evocreo.language.LanguageLoader.loadLanguage(LanguageLoader.java:61)
