### ISSUE TITLE
libgdx game crash

### ISSUE THREAD

**Issue by postpunkpl** [robovm/robovm#842]
Hello,

I have strange crash with:

gdxVersion = '1.5.4'
roboVMVersion = '1.0.0-beta-04'

Game running on real Ipad air with newest iOS version.

Any sugesstions? :)

robovm console in eclipse shows:

10.03.15 16:38:49: [ERROR] AppLauncher failed with an exception:
10.03.15 16:38:49: [ERROR] java.lang.RuntimeException: The app crashed: Terminated due to signal 11. Check the device logs in Xcode (Window->Devices) for more info.
10.03.15 16:38:49: [ERROR] 	at org.robovm.libimobiledevice.util.AppLauncher.pipeStdOut(AppLauncher.java:829)
10.03.15 16:38:49: [ERROR] 	at org.robovm.libimobiledevice.util.AppLauncher.launchInternal(AppLauncher.java:734)
10.03.15 16:38:49: [ERROR] 	at org.robovm.libimobiledevice.util.AppLauncher.launch(AppLauncher.java:1052)
10.03.15 16:38:49: [ERROR] 	at org.robovm.compiler.target.ios.AppLauncherProcess$1.run(AppLauncherProcess.java:67)

and my crash log from xcode shows:

Incident Identifier: F71EA42D-F9AD-43C8-8E23-DF5AE8F04BFA
CrashReporter Key:   c056ad78d35ed0add306624c37fff60e0a8ccf37
Hardware Model:      iPad4,1
Process:             IOSLauncher [1215]
Path:                /private/var/mobile/Containers/Bundle/Application/9727B091-7CAF-486C-A0F8-AE7F98475084/IOSLauncher.app/IOSLauncher
Identifier:          com.postpunkpl.IOSLauncher
Version:             1 (1.0)
Code Type:           ARM (Native)
Parent Process:      debugserver [1214]

Date/Time:           2015-03-10 16:38:50.265 +0100
Launch Time:         2015-03-10 16:21:10.091 +0100
OS Version:          iOS 8.1.3 (12B466)
Report Version:      105

Exception Type:  EXC_CRASH (SIGSEGV)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  1

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_platform.dylib      	0x36da4b7b 0x36da3000 + 7035
1   libGLProgrammability.dylib    	0x2b7433d5 0x2b69a000 + 693205
2   libGLProgrammability.dylib    	0x2b75afff 0x2b69a000 + 790527
3   GLEngine                      	0x2b5ec0a1 0x2b564000 + 557217
4   GLEngine                      	0x2b59bc31 0x2b564000 + 228401
5   IOSLauncher                   	0x003ccdbd 0xdf000 + 3071421
6   IOSLauncher                   	0x0041efe9 0xdf000 + 3407849
7   IOSLauncher                   	0x0041ee9b 0xdf000 + 3407515
8   IOSLauncher                   	0x0041edad 0xdf000 + 3407277
9   IOSLauncher                   	0x0041c263 0xdf000 + 3396195
10  IOSLauncher                   	0x0041b4b7 0xdf000 + 3392695
11  IOSLauncher                   	0x00420a5f 0xdf000 + 3414623
12  IOSLauncher                   	0x0042098b 0xdf000 + 3414411
13  IOSLauncher                   	0x004c5865 0xdf000 + 4089957
14  IOSLauncher                   	0x004c8dd1 0xdf000 + 4103633
15  IOSLauncher                   	0x004c848f 0xdf000 + 4101263
16  IOSLauncher                   	0x0045aef3 0xdf000 + 3653363
17  IOSLauncher                   	0x0045ad3d 0xdf000 + 3652925
18  IOSLauncher                   	0x0045d54b 0xdf000 + 3663179
19  IOSLauncher                   	0x004cd697 0xdf000 + 4122263
20  IOSLauncher                   	0x004cffdf 0xdf000 + 4132831
21  IOSLauncher                   	0x003be1bd 0xdf000 + 3011005
22  IOSLauncher                   	0x003ce703 0xdf000 + 3077891
23  IOSLauncher                   	0x003cebd7 0xdf000 + 3079127
24  IOSLauncher                   	0x00a17217 0xdf000 + 9667095
25  IOSLauncher                   	0x00a172b9 0xdf000 + 9667257
26  IOSLauncher                   	0x00a23661 0xdf000 + 9717345
27  GLKit                         	0x29ac17e7 0x29aa2000 + 128999
28  GLKit                         	0x29ac28f3 0x29aa2000 + 133363
29  QuartzCore                    	0x2bb937ff 0x2bb39000 + 370687
30  QuartzCore                    	0x2bb93667 0x2bb39000 + 370279
31  IOMobileFramebuffer           	0x30412829 0x3040d000 + 22569
32  IOKit                         	0x29b854df 0x29b81000 + 17631
33  CoreFoundation                	0x28c150a3 0x28b59000 + 770211
34  CoreFoundation                	0x28c25571 0x28b59000 + 836977
35  CoreFoundation                	0x28c2550b 0x28b59000 + 836875
36  CoreFoundation                	0x28c23b0d 0x28b59000 + 830221
37  CoreFoundation                	0x28b713bd 0x28b59000 + 99261
38  CoreFoundation                	0x28b711cf 0x28b59000 + 98767
39  GraphicsServices              	0x2ff060a5 0x2fefd000 + 37029
40  UIKit                         	0x2c17f7ad 0x2c111000 + 452525
41  IOSLauncher                   	0x0089c9c3 0xdf000 + 8116675
42  IOSLauncher                   	0x0089bf11 0xdf000 + 8113937
43  IOSLauncher                   	0x0089bf4f 0xdf000 + 8113999
44  IOSLauncher                   	0x004c41ef 0xdf000 + 4084207
45  IOSLauncher                   	0x00a88961 0xdf000 + 10131809
46  IOSLauncher                   	0x00a814e3 0xdf000 + 10101987
47  IOSLauncher                   	0x00a8315f 0xdf000 + 10109279
48  IOSLauncher                   	0x00a831b9 0xdf000 + 10109369
49  IOSLauncher                   	0x00a7d45f 0xdf000 + 10085471
50  IOSLauncher                   	0x00a75a79 0xdf000 + 10054265
51  IOSLauncher                   	0x002cf5c4 0xdf000 + 2033092

Thread 1 Crashed:
0   libsystem_kernel.dylib        	0x36d2db38 0x36d19000 + 84792
1   libsystem_pthread.dylib       	0x36daa3f5 0x36da8000 + 9205
2   libsystem_pthread.dylib       	0x36dab2d9 0x36da8000 + 13017
3   IOSLauncher                   	0x00a9c14d 0xdf000 + 10211661
4   IOSLauncher                   	0x00a95b71 0xdf000 + 10185585
5   IOSLauncher                   	0x00a9acb3 0xdf000 + 10206387
6   libsystem_pthread.dylib       	0x36daae91 0x36da8000 + 11921
7   libsystem_pthread.dylib       	0x36daae03 0x36da8000 + 11779
8   libsystem_pthread.dylib       	0x36da8b8c 0x36da8000 + 2956

Thread 2:
0   libsystem_kernel.dylib        	0x36d1a4f0 0x36d19000 + 5360
1   libsystem_kernel.dylib        	0x36d1a2e5 0x36d19000 + 4837
2   libsystem_kernel.dylib        	0x36d29df3 0x36d19000 + 69107
3   IOSLauncher                   	0x00a774b7 0xdf000 + 10060983
4   IOSLauncher                   	0x00a9ab37 0xdf000 + 10206007
5   IOSLauncher                   	0x00a98649 0xdf000 + 10196553
6   IOSLauncher                   	0x00a9bc55 0xdf000 + 10210389
7   libsystem_pthread.dylib       	0x36daae91 0x36da8000 + 11921
8   libsystem_pthread.dylib       	0x36daae03 0x36da8000 + 11779
9   libsystem_pthread.dylib       	0x36da8b8c 0x36da8000 + 2956

Thread 3 name:  Dispatch queue: com.apple.libdispatch-manager
Thread 3:
0   libsystem_kernel.dylib        	0x36d1a2a0 0x36d19000 + 4768
1   libdispatch.dylib             	0x36c539fd 0x36c46000 + 55805
2   libdispatch.dylib             	0x36c4920f 0x36c46000 + 12815

Thread 4:
0   libsystem_kernel.dylib        	0x36d2db38 0x36d19000 + 84792
1   libsystem_pthread.dylib       	0x36daa3f5 0x36da8000 + 9205
2   libsystem_pthread.dylib       	0x36dab2d9 0x36da8000 + 13017
3   IOSLauncher                   	0x00a84425 0xdf000 + 10114085
4   IOSLauncher                   	0x00a841dd 0xdf000 + 10113501
5   IOSLauncher                   	0x000e4b9b 0xdf000 + 23451
6   IOSLauncher                   	0x0050f6f9 0xdf000 + 4392697
7   IOSLauncher                   	0x0050f6ad 0xdf000 + 4392621
8   IOSLauncher                   	0x005057dd 0xdf000 + 4351965
9   IOSLauncher                   	0x0052258b 0xdf000 + 4470155
10  IOSLauncher                   	0x00a88961 0xdf000 + 10131809
11  IOSLauncher                   	0x00a814e3 0xdf000 + 10101987
12  IOSLauncher                   	0x00a812b3 0xdf000 + 10101427
13  IOSLauncher                   	0x00a88141 0xdf000 + 10129729
14  IOSLauncher                   	0x00a9ab37 0xdf000 + 10206007
15  IOSLauncher                   	0x00a98649 0xdf000 + 10196553
16  IOSLauncher                   	0x00a9bc55 0xdf000 + 10210389
17  libsystem_pthread.dylib       	0x36daae91 0x36da8000 + 11921
18  libsystem_pthread.dylib       	0x36daae03 0x36da8000 + 11779
19  libsystem_pthread.dylib       	0x36da8b8c 0x36da8000 + 2956

Thread 5:
0   libsystem_kernel.dylib        	0x36d2db38 0x36d19000 + 84792
1   libsystem_pthread.dylib       	0x36daa3f5 0x36da8000 + 9205
2   libsystem_pthread.dylib       	0x36dab2d9 0x36da8000 + 13017
3   IOSLauncher                   	0x00a84425 0xdf000 + 10114085
4   IOSLauncher                   	0x00a841dd 0xdf000 + 10113501
5   IOSLauncher                   	0x000e4b9b 0xdf000 + 23451
6   IOSLauncher                   	0x0050f6f9 0xdf000 + 4392697
7   IOSLauncher                   	0x0050f6cd 0xdf000 + 4392653
8   IOSLauncher                   	0x0052a45b 0xdf000 + 4502619
9   IOSLauncher                   	0x0052a5d5 0xdf000 + 4502997
10  IOSLauncher                   	0x0052a3ab 0xdf000 + 4502443
11  IOSLauncher                   	0x00504ec7 0xdf000 + 4349639
12  IOSLauncher                   	0x0052258b 0xdf000 + 4470155
13  IOSLauncher                   	0x00a88961 0xdf000 + 10131809
14  IOSLauncher                   	0x00a814e3 0xdf000 + 10101987
15  IOSLauncher                   	0x00a812b3 0xdf000 + 10101427
16  IOSLauncher                   	0x00a88141 0xdf000 + 10129729
17  IOSLauncher                   	0x00a9ab37 0xdf000 + 10206007
18  IOSLauncher                   	0x00a98649 0xdf000 + 10196553
19  IOSLauncher                   	0x00a9bc55 0xdf000 + 10210389
20  libsystem_pthread.dylib       	0x36daae91 0x36da8000 + 11921
21  libsystem_pthread.dylib       	0x36daae03 0x36da8000 + 11779
22  libsystem_pthread.dylib       	0x36da8b8c 0x36da8000 + 2956

Thread 6:
0   libsystem_kernel.dylib        	0x36d2db38 0x36d19000 + 84792
1   libsystem_pthread.dylib       	0x36daa3f5 0x36da8000 + 9205
2   libsystem_pthread.dylib       	0x36dab2d9 0x36da8000 + 13017
3   IOSLauncher                   	0x00a84425 0xdf000 + 10114085
4   IOSLauncher                   	0x00a841dd 0xdf000 + 10113501
5   IOSLauncher                   	0x000e4b9b 0xdf000 + 23451
6   IOSLauncher                   	0x0050f6f9 0xdf000 + 4392697
7   IOSLauncher                   	0x0050f6ad 0xdf000 + 4392621
8   IOSLauncher                   	0x0050536d 0xdf000 + 4350829
9   IOSLauncher                   	0x0050523b 0xdf000 + 4350523
10  IOSLauncher                   	0x0052258b 0xdf000 + 4470155
11  IOSLauncher                   	0x00a88961 0xdf000 + 10131809
12  IOSLauncher                   	0x00a814e3 0xdf000 + 10101987
13  IOSLauncher                   	0x00a812b3 0xdf000 + 10101427
14  IOSLauncher                   	0x00a88141 0xdf000 + 10129729
15  IOSLauncher                   	0x00a9ab37 0xdf000 + 10206007
16  IOSLauncher                   	0x00a98649 0xdf000 + 10196553
17  IOSLauncher                   	0x00a9bc55 0xdf000 + 10210389
18  libsystem_pthread.dylib       	0x36daae91 0x36da8000 + 11921
19  libsystem_pthread.dylib       	0x36daae03 0x36da8000 + 11779
20  libsystem_pthread.dylib       	0x36da8b8c 0x36da8000 + 2956

Thread 7 name:  AVAudioSession Notify Thread
Thread 7:
0   libsystem_kernel.dylib        	0x36d1a4f0 0x36d19000 + 5360
1   libsystem_kernel.dylib        	0x36d1a2e5 0x36d19000 + 4837
2   CoreFoundation                	0x28c25317 0x28b59000 + 836375
3   CoreFoundation                	0x28c238bd 0x28b59000 + 829629
4   CoreFoundation                	0x28b713bd 0x28b59000 + 99261
5   CoreFoundation                	0x28b711cf 0x28b59000 + 98767
6   libAVFAudio.dylib             	0x2787b3eb 0x27862000 + 103403
7   libAVFAudio.dylib             	0x2786d909 0x27862000 + 47369
8   libsystem_pthread.dylib       	0x36daae91 0x36da8000 + 11921
9   libsystem_pthread.dylib       	0x36daae03 0x36da8000 + 11779
10  libsystem_pthread.dylib       	0x36da8b8c 0x36da8000 + 2956

Thread 8 name:  AURemoteIO::IOThread
Thread 8:
0   libsystem_kernel.dylib        	0x36d1a4f0 0x36d19000 + 5360
1   libsystem_kernel.dylib        	0x36d1a2e5 0x36d19000 + 4837
2   AudioToolbox                  	0x283d999b 0x282cc000 + 1104283
3   AudioToolbox                  	0x283dd095 0x282cc000 + 1118357
4   AudioToolbox                  	0x283119e3 0x282cc000 + 285155
5   libsystem_pthread.dylib       	0x36daae91 0x36da8000 + 11921
6   libsystem_pthread.dylib       	0x36daae03 0x36da8000 + 11779
7   libsystem_pthread.dylib       	0x36da8b8c 0x36da8000 + 2956

Thread 9:
0   libsystem_malloc.dylib        	0x36d54d9f 0x36d54000 + 3487
1   libsystem_malloc.dylib        	0x36d5847f 0x36d54000 + 17535
2   libsystem_blocks.dylib        	0x36c82929 0x36c82000 + 2345
3   libdispatch.dylib             	0x36c47759 0x36c46000 + 5977
4   libdispatch.dylib             	0x36c48875 0x36c46000 + 10357
5   UIKit                         	0x2c4aeca5 0x2c111000 + 3792037
6   CoreMotion                    	0x2945ceb7 0x29435000 + 163511
7   CoreMotion                    	0x2947293f 0x29435000 + 252223
8   CoreMotion                    	0x29470f3d 0x29435000 + 245565
9   CoreMotion                    	0x29473b1d 0x29435000 + 256797
10  IOKit                         	0x29b9e4f9 0x29b81000 + 120057
11  CoreFoundation                	0x28c150a3 0x28b59000 + 770211
12  CoreFoundation                	0x28c25571 0x28b59000 + 836977
13  CoreFoundation                	0x28c2550b 0x28b59000 + 836875
14  CoreFoundation                	0x28c23b0d 0x28b59000 + 830221
15  CoreFoundation                	0x28b713bd 0x28b59000 + 99261
16  CoreFoundation                	0x28bba0e7 0x28b59000 + 397543
17  CoreMotion                    	0x29474e9b 0x29435000 + 261787
18  libsystem_pthread.dylib       	0x36daae91 0x36da8000 + 11921
19  libsystem_pthread.dylib       	0x36daae03 0x36da8000 + 11779
20  libsystem_pthread.dylib       	0x36da8b8c 0x36da8000 + 2956

Thread 10:
0   libsystem_kernel.dylib        	0x36d2db38 0x36d19000 + 84792
1   libsystem_pthread.dylib       	0x36daa3f5 0x36da8000 + 9205
2   libsystem_pthread.dylib       	0x36dab2d9 0x36da8000 + 13017
3   IOSLauncher                   	0x00a84425 0xdf000 + 10114085
4   IOSLauncher                   	0x00a841dd 0xdf000 + 10113501
5   IOSLauncher                   	0x000e4b9b 0xdf000 + 23451
6   IOSLauncher                   	0x0050f6f9 0xdf000 + 4392697
7   IOSLauncher                   	0x00523381 0xdf000 + 4473729
8   IOSLauncher                   	0x00a757fb 0xdf000 + 10053627
9   IOSLauncher                   	0x0060ad41 0xdf000 + 5422401
10  IOSLauncher                   	0x0060ad7b 0xdf000 + 5422459
11  IOSLauncher                   	0x0060a239 0xdf000 + 5419577
12  IOSLauncher                   	0x005fd613 0xdf000 + 5367315
13  IOSLauncher                   	0x00603e5d 0xdf000 + 5394013
14  IOSLauncher                   	0x00603f3b 0xdf000 + 5394235
15  IOSLauncher                   	0x00605b5d 0xdf000 + 5401437
16  IOSLauncher                   	0x0052258b 0xdf000 + 4470155
17  IOSLauncher                   	0x00a88961 0xdf000 + 10131809
18  IOSLauncher                   	0x00a814e3 0xdf000 + 10101987
19  IOSLauncher                   	0x00a812b3 0xdf000 + 10101427
20  IOSLauncher                   	0x00a88141 0xdf000 + 10129729
21  IOSLauncher                   	0x00a9ab37 0xdf000 + 10206007
22  IOSLauncher                   	0x00a98649 0xdf000 + 10196553
23  IOSLauncher                   	0x00a9bc55 0xdf000 + 10210389
24  libsystem_pthread.dylib       	0x36daae91 0x36da8000 + 11921
25  libsystem_pthread.dylib       	0x36daae03 0x36da8000 + 11779
26  libsystem_pthread.dylib       	0x36da8b8c 0x36da8000 + 2956

Thread 11:
0   libsystem_kernel.dylib        	0x36d2db38 0x36d19000 + 84792
1   libsystem_pthread.dylib       	0x36daa3f5 0x36da8000 + 9205
2   libsystem_pthread.dylib       	0x36dab319 0x36da8000 + 13081
3   IOSLauncher                   	0x00a843f9 0xdf000 + 10114041
4   IOSLauncher                   	0x00a841dd 0xdf000 + 10113501
5   IOSLauncher                   	0x000e4b9b 0xdf000 + 23451
6   IOSLauncher                   	0x0050f6f9 0xdf000 + 4392697
7   IOSLauncher                   	0x0050f6cd 0xdf000 + 4392653
8   IOSLauncher                   	0x004bcec9 0xdf000 + 4054729
9   IOSLauncher                   	0x0052258b 0xdf000 + 4470155
10  IOSLauncher                   	0x00a88961 0xdf000 + 10131809
11  IOSLauncher                   	0x00a814e3 0xdf000 + 10101987
12  IOSLauncher                   	0x00a812b3 0xdf000 + 10101427
13  IOSLauncher                   	0x00a88141 0xdf000 + 10129729
14  IOSLauncher                   	0x00a9ab37 0xdf000 + 10206007
15  IOSLauncher                   	0x00a98649 0xdf000 + 10196553
16  IOSLauncher                   	0x00a9bc55 0xdf000 + 10210389
17  libsystem_pthread.dylib       	0x36daae91 0x36da8000 + 11921
18  libsystem_pthread.dylib       	0x36daae03 0x36da8000 + 11779
19  libsystem_pthread.dylib       	0x36da8b8c 0x36da8000 + 2956

Thread 1 crashed with ARM Thread State (32-bit):
    r0: 0x00000104    r1: 0x00000000      r2: 0x0002bc01      r3: 0x0002bc00
    r4: 0x00000000    r5: 0x00000000      r6: 0x00000000      r7: 0x04a97f60
    r8: 0x0151f990    r9: 0x00000000     r10: 0x0151f9d8     r11: 0x00000001
    ip: 0x00000131    sp: 0x04a97ee8      lr: 0x36daa3f9      pc: 0x36d2db38
  cpsr: 0x60000010

**Comment by badlogic** [comment]
Please [symbolicate your crash log](https://github.com/robovm/robovm/wiki/Symbolicate-a-crash-reports) and try the new 1.0.0 release! I'll update libGDX to use 1.0.0 this weekend and do a release.

**Comment by muddycrow** [comment]
I'm unable to symbolicate my crash log and entering the first command returns nothing, any further tips to decipher what the crash log does? Thanks

following the link ..
    https://github.com/robovm/robovm/wiki/Symbolicate-a-crash-reports
and using the command returns nothing
    find `xcode-select -print-path` -name symbolicatecrash -type f

**Comment by ashleyj** [comment]
I think the binary has been moved. Doco probably needs updating too

Try this:

$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

$ find /Applications/Xcode.app/Contents -name symbolicatecrash -type f
/Applications/Xcode.app/Contents/SharedFrameworks/DTDeviceKitBase.framework/Versions/A/Resources/symbolicatecrash

**Comment by ntherning** [comment]
Please try with the just released RoboVM 1.1.0. Symbolication should now be a lot easier since we copy the dSYM to a folder which is indexed by Spotlight. Just open Xcode, go to Window -> Devices. Click your device and click "View device logs". The log should be symbolicated automatically. Then paste it here.

**Comment by ntherning** [comment]
Closing this now since we haven't heard back from OP. If the problem still persists please post on the Google Group first and we'll try to help out there.
