### ISSUE TITLE
Increase in total app size from app store encryption

### ISSUE THREAD

**Issue by ericnondahl** [robovm/robovm#843]
We recently submitted an update for our RoboVM+libGDX game to the iOS app store. They sent us an email that said "The app binary listed below was 79.3 MB when you submitted it, but will be 128.3 MB once processed for the App Store."

This puts us over the cell network download limit. From limited research this is from the iOS app store encrypting the binary after you upload. From the Apple help site: 

"When your app is approved for the App Store, it is encrypted with DRM and recompressed. The encryption and DRM will increase the file size. The exact size of the increase varies, but can be significant if the binary contains a large proportion of contiguous zeros. The final size for your app after the encryption has been added cannot be determined or guaranteed in advance."

We have a variety of assets included in our libGDX + RoboVM game:
* App Icon PNGs
* Font PNGs
* PVRTC compressed TextureAtlases of main game art and UI
* mp3 sound effects
* third-party static libraries like the Facebook SDK and their content

I'm not sure if this is something that RoboVM is causing or could improve upon. If there was some way to reduce this compression overhead, it might be nice though.

**Comment by ebbybeh** [comment]
I have the same issue. Apple's processing adds another 50MB to the app.

**Comment by ntherning** [comment]
Did you get below the limit after we optimized executable file sizes? There's not much we can do about this but to try to optimize executable file sizes. So I think we should close this and use separate issues for the specific optimizations we wanna do.

**Comment by ericnondahl** [comment]
Yes, the recent optimizations and some of our own reorganization have brought us under the cell limit. Thanks!
