### ISSUE TITLE
Don't throw UnsupportedOperationException when overridden methods in adapter classes call super

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#848]
The `bro-gen` generated adapter classes throw `UnsupportedOperationException` when the `@NotImplemented` methods are called. If such a method is overridden it is important not to call `super.xxx()` to avoid that exception to be thrown. But Eclipse and probably other IDE's insert a `super.xxx()` call for you by default when overriding a method.

We have a few options:
* Just remove the `throw UnsupportedOperationException()` and let the super method finish without doing anything.
* Check in the super method via reflection if the method has been overridden and if it has do nothing otherwise throw `UnsupportedOperationException`.
* Always log a warning (even if overridden) but don't throw.
* Log a warning if not overridden (check via reflection) and return.

I don't think we should do the reflection check. It's probably best to just let the call proceed and return a default value if the method returns something.

**Comment by BlueRiverInteractive** [comment]
+1 no exception thrown, return default value.

@ntherning I can do the necessary changes, if you give an ok.
