### ISSUE TITLE
Review validation of @IBOutlet annotated methods

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#856]
I think the current code is incorrect in refusing non-native methods to be `@IBOutlet` annotated. I think it should be the other way around.

**Comment by BlueRiverInteractive** [comment]
I would say both ways are valid.

```Java
// This way requires you to also have a setter.
private UIButton startButton;

@IBOutlet
private UIButton getStartButton() {
   return startButton;
}

@IBOutlet
private void setStartButton(UIButton startButton) {
  this.startButton = startButton;
}
```

```Java
// This way is more compact (no setter needed)

@IBOutlet
private native UIButton getStartButton();
```

**Comment by ntherning** [comment]
I'm afraid I don't see how the native option would work. There needs to be a storage for that UIButton somewhere. Should we generate the field automatically in the `ObjCMemberPlugin`?

**Comment by ntherning** [comment]
Will change the check for now to only allow non-native.

**Comment by ntherning** [comment]
We allow both for now. :-)

**Comment by BlueRiverInteractive** [comment]
I get the problem. I first thought that the UIButton would be somehow stored on the obj-c side via the `@property`. I guess this will be easier when we can have a native field as outlet.

```Java
@IBOutlet
private native UIButton startButton;
```

**Comment by badlogic** [comment]
There's no such thing as a native field in Java. But we could annotate such
fields.
