### ISSUE TITLE
CoreVideo : CVPixelBuffer Could not initialize

### ISSUE THREAD

**Issue by dzungpv** [robovm/robovm#860]
I have ask on Google group but i post here if someone can fix it.  https://groups.google.com/forum/#!topic/robovm/67gdAsinW_o
```
java.lang.NoClassDefFoundError: Could not initialize class org.robovm.apple.corevideo.CVPixelBuffer
	at com.testcamera.MyViewController.didOutputSampleBuffer(MyViewController.java:173)
	at org.robovm.apple.avfoundation.AVCaptureVideoDataOutputSampleBufferDelegate$ObjCProxy.$cb$captureOutput$didOutputSampleBuffer$fromConnection$(Unknown Source)
Unhandled exception (probably in a @Callback method called from native code): java/lang/NoClassDefFoundError
```
The code i use to produce the issue:

 ```
//cvimgRefT is CVImageBuffer
CVPixelBuffer cvimgRef = cvimgRefT.as(CVPixelBuffer.class);
```

Or 
```
CVPixelBufferAttributes cvpxattr = new CVPixelBufferAttributes();
CVPixelBuffer cvimgRef = CVPixelBuffer.create(CFAllocator.getDefault(), 50, 50, CVPixelFormatType._32RGBA, cvpxattr);
```
More note that if i setup CVPixelBufferAttributes like this will show other error:

```
CVPixelBufferAttributes cvpxattr = new CVPixelBufferAttributes();	    
cvpxattr.setCompatibleWithCGBitmapContext(true);
cvpxattr.setCompatibleWithCGBitmapContext(true);
```
Error:

```
java.lang.UnsupportedOperationException: CFDictionary is immutable. Use CFMutableDictionary instead!
	at org.robovm.apple.corefoundation.CFDictionary.put(CFDictionary.java:256)
	at org.robovm.apple.corevideo.CVPixelBufferAttributes.set(CVPixelBufferAttributes.java:108)
	at org.robovm.apple.corevideo.CVPixelBufferAttributes.setCompatibleWithCGBitmapContext(CVPixelBufferAttributes.java:263)
```

**Comment by BlueRiverInteractive** [comment]
To solve the first issue we can add a method `getPixelBuffer()` to `CMSampleBuffer` that calls the native `CMSampleBufferGetImageBuffer` but returns a `CVPixelBuffer` instead of a `CVImageBuffer`. 

The second issue may be related to #837. `CVPixelBufferAttributes` extends from `CVBufferAttributes`, which extends from the abstract class `CFDictionaryWrapper`. That class has a `CFDictionary` field. The constructor uses `CFMutableDictionary.create();` which returns a `CFMutableDictionary`. Don't know why but it seems that _sometimes_ the extending classes think that it's a `CFDictionary` instead of a `CFMutableDictionary`.

BTW Maybe we should also modify the dictionary marshalers to marshal `CFMutableDictionary` directly instead of `CFDictionary`. Could prevent similar errors in the future.

**Comment by dzungpv** [comment]
I have try this before but it not work. I will test again with latest nightly.

**Comment by dzungpv** [comment]
@BlueRiverInteractive I use latest nightly with your new  getPixelBuffer() but still the same error:
```
java.lang.NoClassDefFoundError: Could not initialize class org.robovm.apple.corevideo.CVPixelBuffer
	at org.robovm.rt.VM.allocateObject(Native Method)
	at org.robovm.rt.bro.NativeObject$Marshaler.toObject(NativeObject.java)
	at org.robovm.apple.corefoundation.CFType$Marshaler.toObject(CFType.java)
	at org.robovm.apple.corefoundation.CFType$Marshaler.toObject(CFType.java)
	at org.robovm.apple.coremedia.CMSampleBuffer.getPixelBuffer(Native Method)
	at com.test.camera.MyViewController.didOutputSampleBuffer(MyViewController.java)
	at org.robovm.apple.avfoundation.AVCaptureVideoDataOutputSampleBufferDelegate$ObjCProxy.$cb$captureOutput$didOutputSampleBuffer$fromConnection$(Unknown Source)
Unhandled exception (probably in a @Callback method called from native code): java/lang/NoClassDefFoundError
```

I see one guy fix this problem from long address but i don't how he do:  https://groups.google.com/forum/#!topic/robovm/eyood7qNi6U

**Comment by ntherning** [comment]
Is this still an issue?

**Comment by dzungpv** [comment]
I gave up and then use Object C instead.
I have send you sample project on Google Group longtime ago. And I not yet test with latest robovm.
https://groups.google.com/forum/#!msg/robovm/67gdAsinW_o/ZAjsirqy6GMJ

**Comment by tomfisher** [comment]
I got another issue related with this:

```
        CVPixelBufferAttributes bufferAttributes = new CVPixelBufferAttributes();
        bufferAttributes.setCompatibleWithCGImage(true);
        bufferAttributes.setCompatibleWithCGBitmapContext(true);
        CVPixelBuffer buffer = CVPixelBuffer.create(width, height, CVPixelFormatType._32ABGR, bufferAttributes);

```

The buffer is always null regardless of what parameter combination is used.  I am using RoboVM 1.11.0

**Comment by BlueRiverInteractive** [comment]
CVPixelBuffer only supports a very limited set of pixel formats. 32ABGR is not one of them. You can use 32ARGB instead. 

You could normally get this information by the returned CVReturn enum. However we did swallow that enum and return CVPixelBuffer instead. 
I have added a new `CVException` type now that will be thrown when a CVReturn error is returned natively. This should make it much easier now to correctly setup the attributes of a CVPixelBuffer.
