### ISSUE TITLE
Add OSStatusException

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#890]
Apple's C frameworks functions typically return an OSStatus type to indicate success (noErr = 0) or error. Therefore, if a function returns some value, the return type is passed byref as a parameter.
In Java we are not used to passing pointers around, therefore we bind these method to return the result value instead of a OSStatus type (and don't have a pointer parameter). 
This however has the implication that we don't get the OSStatus value and don't know if there was an error.

Possible solution would be to add an OSStatusException type. We just throw that exception in case there was an error (i.e. the value is not 0) and the user can get the error code from the exception via a simple getStatus() method.

**Comment by BlueRiverInteractive** [comment]
Two examples:

```Java
public boolean isPlaying() throws OSStatusException {
    BooleanPtr ptr = new BooleanPtr();
    OSStatus status = isPlaying0(ptr);
    OSStatusException.throwIfNecessary(status); // throws if OSStatus value != 0
    return ptr.get();
}
@Bridge(symbol="MusicPlayerIsPlaying", optional=true)
protected native OSStatus isPlaying0(BooleanPtr outIsPlaying);
```

```Java
public void stop() throws OSStatusException {
    OSStatus status = stop0();
    OSStatusException.throwIfNecessary(status);
}
@Bridge(symbol="MusicPlayerStop", optional=true)
public native OSStatus stop0();
```

We should also agree on a visibility and naming scheme for all native OSStatus returning C-functions in apple's frameworks.
I would propose to make them `protected` and append a `0` to distinguish between "Java-fied" and native methods.

**Comment by badlogic** [comment]
I like it. I assume OSStatusExcption is checked?

**Comment by badlogic** [comment]
As discussed via Skype: it may make sense to add TLS instances of XXPtr for these method wrappers to reduce the pressure on the GC. Especially for APIs like audio, where methods are called at high frequency, a TLS lookup may be preferable to allocating thousands of small objects in a short amount of time.

**Comment by ntherning** [comment]
+1 for TLS. One thing one has to be cautious about is when using a TLS ptr instance when calling a native function which may call back into Java. Could cause problems if the Java callback uses the same TLS. Maybe use something similar to a pool but just reuse that last one put back into the pool to optimize for the common use case?

**Comment by badlogic** [comment]
+1 for TLS pool. See libgdx for a working pool class.
