### ISSUE TITLE
java.lang.IllegalStateException: Found LocalVariables do not refer to a variable with the same name

### ISSUE THREAD

**Issue by iitsoftware** [robovm/robovm#920]
RoboVM throws this exception when compiling a dom4j class. I try to attach a sample IntelliJ project.

**Comment by badlogic** [comment]
Could you also post the full stack trace? Thanks!

**Comment by iitsoftware** [comment]
The Intellij test project can be downloaded here: https://www.dropbox.com/s/kgqlfjnosvj9i2l/localvarissuedomj4.zip?dl=0

**Comment by iitsoftware** [comment]
The full stack trace:

[DEBUG] Compiling org.dom4j.rule.Pattern (ios x86 release)
[DEBUG] Compiling org.dom4j.tree.AbstractElement (ios x86 release)
[ERROR] Couldn't compile app
java.lang.IllegalStateException: Found LocalVariables do not refer to a variable with the same name: [LocalVariable [name=parent, index=2, startUnit=$stack0 = l2, endUnit=null, descriptor=Lorg/dom4j/Element;], LocalVariable [name=list, index=2, startUnit=$stack0 = l2, endUnit=$stack0 = l2, descriptor=Ljava/util/List;]]
	at soot.toolkits.scalar.LocalSplitter.findLocalVariables(LocalSplitter.java:297)
	at soot.toolkits.scalar.LocalSplitter.mergeWebs(LocalSplitter.java:265)
	at soot.toolkits.scalar.LocalSplitter.internalTransform(LocalSplitter.java:185)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:97)
	at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:57)
	at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:89)
	at soot.Pack.apply(Pack.java:117)
	at soot.coffi.CoffiMethodSource.getBody(CoffiMethodSource.java:115)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:87)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:321)
	at org.robovm.compiler.plugin.lambda.LambdaPlugin.transformMethod(LambdaPlugin.java:99)
	at org.robovm.compiler.plugin.lambda.LambdaPlugin.beforeClass(LambdaPlugin.java:85)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:672)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:285)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:242)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:331)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:375)
	at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)

**Comment by badlogic** [comment]
Offending class/method is `org.dom4j.tree.AbstractElement#getNamespaceForPrexis`. @iitsoftware could you tell us which version of dom4j you are using? The `MANIFEST.MF` in the jar says 1.1, but i don't fully trust that :)

**Comment by badlogic** [comment]
Bytecode:

```
 // access flags 0x1
  public getNamespaceForPrefix(Ljava/lang/String;)Lorg/dom4j/Namespace;
   L0
    LINENUMBER 1083 L0
    ALOAD 1
    IFNONNULL L1
   L2
    LINENUMBER 1084 L2
    LDC ""
    ASTORE 1
   L1
    LINENUMBER 1086 L1
    ALOAD 1
    ALOAD 0
    INVOKEVIRTUAL org/dom4j/tree/AbstractElement.getNamespacePrefix ()Ljava/lang/String;
    INVOKEVIRTUAL java/lang/String.equals (Ljava/lang/Object;)Z
    IFEQ L3
   L4
    LINENUMBER 1087 L4
    ALOAD 0
    INVOKEVIRTUAL org/dom4j/tree/AbstractElement.getNamespace ()Lorg/dom4j/Namespace;
    ARETURN
   L3
    LINENUMBER 1089 L3
    ALOAD 1
    LDC "xml"
    INVOKEVIRTUAL java/lang/String.equals (Ljava/lang/Object;)Z
    IFEQ L5
   L6
    LINENUMBER 1090 L6
    GETSTATIC org/dom4j/Namespace.XML_NAMESPACE : Lorg/dom4j/Namespace;
    ARETURN
   L5
    LINENUMBER 1093 L5
    ALOAD 0
    INVOKEVIRTUAL org/dom4j/tree/AbstractBranch.contentList ()Ljava/util/List;
    ASTORE 2
   L7
    LINENUMBER 1094 L7
    ALOAD 2
    INVOKEINTERFACE java/util/List.size ()I
    ISTORE 3
   L8
    LINENUMBER 1095 L8
    ICONST_0
    ISTORE 4
   L9
    GOTO L10
   L11
    LINENUMBER 1096 L11
    ALOAD 2
    ILOAD 4
    INVOKEINTERFACE java/util/List.get (I)Ljava/lang/Object;
    ASTORE 5
   L12
    LINENUMBER 1097 L12
    ALOAD 5
    INSTANCEOF org/dom4j/Namespace
    IFEQ L13
   L14
    LINENUMBER 1098 L14
    ALOAD 5
    CHECKCAST org/dom4j/Namespace
    ASTORE 6
   L15
    LINENUMBER 1099 L15
    ALOAD 1
    ALOAD 6
    INVOKEVIRTUAL org/dom4j/Namespace.getPrefix ()Ljava/lang/String;
    INVOKEVIRTUAL java/lang/String.equals (Ljava/lang/Object;)Z
    IFEQ L13
   L16
    LINENUMBER 1100 L16
    ALOAD 6
    ARETURN
   L13
    LINENUMBER 1095 L13
    IINC 4 1
   L10
    ILOAD 4
    ILOAD 3
    IF_ICMPLT L11
   L17
    LINENUMBER 1105 L17
    ALOAD 0
    INVOKEVIRTUAL org/dom4j/tree/AbstractNode.getParent ()Lorg/dom4j/Element;
    ASTORE 2
   L18
    LINENUMBER 1106 L18
    ALOAD 2
    IFNULL L19
   L20
    LINENUMBER 1107 L20
    ALOAD 2
    ALOAD 1
    INVOKEINTERFACE org/dom4j/Element.getNamespaceForPrefix (Ljava/lang/String;)Lorg/dom4j/Namespace;
    ASTORE 3
   L21
    LINENUMBER 1108 L21
    ALOAD 3
    IFNULL L19
   L22
    LINENUMBER 1109 L22
    ALOAD 3
    ARETURN
   L19
    LINENUMBER 1112 L19
    ALOAD 1
    IFNULL L23
    ALOAD 1
    INVOKEVIRTUAL java/lang/String.length ()I
    IFGT L24
   L23
    LINENUMBER 1113 L23
    GETSTATIC org/dom4j/Namespace.NO_NAMESPACE : Lorg/dom4j/Namespace;
    ARETURN
   L24
    LINENUMBER 1115 L24
    ACONST_NULL
    ARETURN
   L25
    LOCALVARIABLE this Lorg/dom4j/tree/AbstractElement; L0 L25 0
    LOCALVARIABLE prefix Ljava/lang/String; L0 L25 1
    LOCALVARIABLE list Ljava/util/List; L7 L18 2
    LOCALVARIABLE size I L8 L21 3
    LOCALVARIABLE i I L9 L25 4
    LOCALVARIABLE object Ljava/lang/Object; L12 L10 5
    LOCALVARIABLE namespace Lorg/dom4j/Namespace; L15 L13 6
    LOCALVARIABLE parent Lorg/dom4j/Element; L18 L25 2
    LOCALVARIABLE answer Lorg/dom4j/Namespace; L21 L19 3
    LOCALVARIABLE size I L23 L25 3
    MAXSTACK = 2
    MAXLOCALS = 7
```

`list` and `parent` share the same stack slot and overlap in usage (L18). That's weird.

**Comment by iitsoftware** [comment]
It is the version from the manifest. It’s quite old but we can’t change it…

-- 
Andreas Mueller
IIT Software GmbH, Bremen/Germany
http://www.swiftmq.com



> Am 21.04.2015 um 17:35 schrieb Mario Zechner <notifications@github.com>:
> 
> Offending class/method is org.dom4j.tree.AbstractElement#getNamespaceForPrexis. @iitsoftware could you tell us which version of dom4j you are using? The MANIFEST.MF in the jar says 1.1, but i don't fully trust that :)
> 
> —
> Reply to this email directly or view it on GitHub.
> 




IIT Software GmbH
Fahrenheitstr. 13, D28359 Bremen, Germany
Tel: +49 421 330 46 088, Fax: +49 421 330 46 090
Amtsgericht Bremen, HRB 18624, Geschaeftsfuehrer: Andreas Mueller
Steuernummer: 460/118/06404 VAT: DE199945912

**Comment by badlogic** [comment]
That's fine, i just needed the version to lookup the corresponding Java source. Looks like that's not available anywhere anymore :)

**Comment by iitsoftware** [comment]
No problem, I have the sources ;-)

https://www.dropbox.com/s/rsjgwioz62pg6ce/dom4j-1.1-source.zip?dl=0

Andreas Mueller
IIT Software GmbH, Bremen/Germany
http://www.swiftmq.com

> Am 21.04.2015 um 17:47 schrieb Mario Zechner <notifications@github.com>:
> 
> That's fine, i just needed the version to lookup the corresponding Java source. Looks like that's not available anywhere anymore :)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 





IIT Software GmbH
Fahrenheitstr. 13, D28359 Bremen, Germany
Tel: +49 421 330 46 088, Fax: +49 421 330 46 090
Amtsgericht Bremen, HRB 18624, Geschaeftsfuehrer: Andreas Mueller
Steuernummer: 460/118/06404 VAT: DE199945912

**Comment by ntherning** [comment]
Just a thought, does recompiling the class with a modern Java compiler change anything? Eclipse vs `javac`? We've seen problems before with JARs compiled with very old `javac` versions. Those problems were related to JSRs being used though (lucene). Don't see any JSRs in this code.

**Comment by iitsoftware** [comment]
I think you're right with 1.1. This is just too old. I've downloaded dom4j-1.6 and that seems to work.
