### ISSUE TITLE
String split taking a really long time

### ISSUE THREAD

**Issue by dulceangustia** [robovm/robovm#932]
I'm using **libGDX 1.5.5 with RoboVM 1.0.0** and I have an issue while reading an internal text file and getting the lines to String's.

    String[] lines = Gdx.files.internal("split.txt").readString("UTF-8").split("[\\r\\n]+");

The problem here is the split method which takes around 5 seconds to process it in a real iPhone 5 device. On a iPhone 6 simulator it takes around 2 seconds, what is still a very long time given in Android (real device) and desktop (both Windows and Mac) it only takes a few milliseconds. 

The file that I'm using contains 3476 lines and weighs 330 KB, not big deal as you can see. 

I've performed the same test with a different file (test data, download it here: http://pastebin.com/Cc6Yqz7k) with **3500 lines and 112 KB**, and it also takes **1-2 seconds in iPhone 6 simulator** and **4-5 seconds in a real iPhone 5 device**.

.

**Comment by badlogic** [comment]
Did you test a release or debug build?

**Comment by dulceangustia** [comment]
Debug.

**Comment by badlogic** [comment]
Could you try a release build and report back the timings?

Debug builds instrument the code and disable LLVM optimizations. This will
slow down execution. The difference should not be that huge though. Might
be a degenerate case in the regex code.

**Comment by dulceangustia** [comment]
This might be a stupid question but... how do I try a release build?

I have the development and distribution signing identities and the dev, adhoc and appstore provisioning profiles, but it seems that I can only run the dev-dev configuration. I tried installing the game with the distribution signing identity and the adhoc prov. profile (what I think is a *release build*) and I got a ApplicationVerificationFailed exception when I tried to install it through IDEA. I guess it is because I can not install my game through IDEA/gradle with this configuration. Am I right?

In case I'm wrong, could you please tell me how I should proceed? Thanks and sorry fot the offtopic... U_U

**Comment by badlogic** [comment]
Using IDEA, you can either run your app in release or debug mode. There are
two separate buttons in the toolbar for that, right to the combo box that
let's you select the run configuration.

If you run via the first button (looks like a green play button) you build
in release mode.

If you run via the second button (looks like a bug) you build in debug mode.

If you run via Gradle on the command line (e.g. gradlew
lauchIPhoneSimulator), release is the default.

**Comment by badlogic** [comment]
One more thing: if you want run in debug mode, you'll need a valid (trial)
license. Otherwise your app will be build in release mode even if you hit
the debug button.

**Comment by dulceangustia** [comment]
OK, now I realize that it was a stupid question and that I lied to you... sorry... xD. I thought that you were referring to a development version of the app according to the iOS stuff.

So, I've trying the release version all the time.

**Comment by badlogic** [comment]
Could you create a tiny sample project for us that reproduces the issue?
Then it's easier for us to pinpoint the performance issue. Thanks!

**Comment by dulceangustia** [comment]
Here you have the simple example: http://pastebin.com/5vwkxgLY, using the text file from above (http://pastebin.com/Cc6Yqz7k).

Results in **real iPhone 5 device**:
* GOT FILE HANDLE IN 0
* READ STRING IN 12
* **SPLIT STRING IN 2125**

Results in **iPhone 6 simulation**:
* GOT FILE HANDLE IN 0
* READ STRING IN 2
* **SPLIT STRING IN 690**

This seems faster, but I think it's still a lot of time, specially when compared with **desktop** for example:
* GOT FILE HANDLE IN 0
* READ STRING IN 5
* **SPLIT STRING IN 14**

**Comment by dulceangustia** [comment]
Btw, what's the purpose of the Splitter class? https://github.com/robovm/robovm/blob/master/rt/libcore/luni/src/main/java/java/util/regex/Splitter.java

Can be related to this issue? What's the parameter *re*?

**Comment by dulceangustia** [comment]
String[] lines = Gdx.files.internal("split.txt").readString("UTF-8").split("\n");

This is working fine, so it is clearly an issue with regex.

**Comment by ntherning** [comment]
Did investigate this a bit using this small program:

```java
final int ITERATIONS = 100;

String s = FileUtils.readFileToString(new File("split_lines.txt"));
long start = System.currentTimeMillis();
for (int i = 0; i < ITERATIONS; i++) {
    s.split("[\\r\\n]+");
}
System.out.format("Avg time using String.split(): %.4f s\n", (System.currentTimeMillis() - start) / 1000.0 / ITERATIONS);

Pattern pattern = Pattern.compile("[\\r\\n]+");
start = System.currentTimeMillis();
for (int i = 0; i < ITERATIONS; i++) {
    pattern.split(s);
}
System.out.format("Avg time using Pattern.split(): %.4f s\n", (System.currentTimeMillis() - start) / 1000.0 / ITERATIONS);

NSRegularExpression regex = new NSRegularExpression("[\\r\\n]+", NSRegularExpressionOptions.None);
start = System.currentTimeMillis();
for (int i = 0; i < ITERATIONS; i++) {
    regex.getMatches(s, NSMatchingOptions.None, new NSRange(0, s.length()));
}
System.out.format("Avg time using NSRegularExpression: %.4f s\n", (System.currentTimeMillis() - start) / 1000.0 / ITERATIONS);
```

With HotSpot on OS X I got these figures for the first 2 tests (the last test which uses `NSRegularExpression` is RoboVM specific):
```
Avg time using String.split(): 0.0032 s
Avg time using Pattern.split(): 0.0021 s
```

Now the same program compiled using RoboVM running on OS X:
```
Avg time using String.split(): 0.3962 s
Avg time using Pattern.split(): 0.2915 s
Avg time using NSRegularExpression: 0.0027 s
```

Upping the initial heap size (from the default 4MB to 16MB) gives slightly better numbers for the builtin regex tests:
```
Avg time using String.split(): 0.1572 s
Avg time using Pattern.split(): 0.1586 s
Avg time using NSRegularExpression: 0.0026 s
```

As can be seen the native regex using `NSRegularExpression` is as performant as Oracle's JVM. IIUC the native `NSRegularExpression` is based on ICU which we also use under the hood for `Pattern` and `String.split()`. We should look into whether we build ICU properly. Maybe there are optimizations we don't turn on?

Also increasing the initial heap size makes a difference. We already have an issue for upping the default: #865.

**Comment by ntherning** [comment]
Adding to that. Just ran the same program but linked with the debug libs of the native RoboVM libs and 16MB initial heap and I see no difference compared to the release VM libs used in the previous tests:

```
Avg time using String.split(): 0.1619 s
Avg time using Pattern.split(): 0.1642 s
Avg time using NSRegularExpression: 0.0023 s
```

Could definitely be something with the way we build ICU.

**Comment by ntherning** [comment]
Found the culprit: #956. Will fix this by simply not making a copy of the char array in the JNI `GetStringChars()` function.

**Comment by ntherning** [comment]
Timings after the JNI fix:

```
Avg time using String.split(): 0.0024 s
Avg time using Pattern.split(): 0.0021 s
Avg time using NSRegularExpression: 0.0023 s
```

Pretty ok now I would say. :-)
