### ISSUE TITLE
IntelliJ plugin generates wrong xcode class names

### ISSUE THREAD

**Issue by iitsoftware** [robovm/robovm#942]
I'm using RoboVM 1.1 with IntelliJ 14. I have multiple views in mx xcode code project and wanted to generate the corresponding view controller classes in IDEA. It seems RoboVM generates wrong ObjC class names:

[DEBUG] Created file: /Users/am/Development/explorer-ios/build/classes/main/com/swiftmq/admin/ios/explorer/LogController.class
[DEBUG] Modified file: /Users/am/Development/explorer-ios/build/classes/main/com/swiftmq/admin/ios/explorer/LogController.class
[DEBUG] Added file /Users/am/Development/explorer-ios/robovm-build/xcode/.ib/com.swiftmq.admin.ios.explorer/LogController.h to Xcode project explorer-ios
[DEBUG] Added file /Users/am/Development/explorer-ios/robovm-build/xcode/.ib/com.swiftmq.admin.ios.explorer/LogController.m to Xcode project explorer-ios

The header file in xcode:

@interface j_com_swiftmq_admin_ios_explorer_LogController : UIViewController

**Comment by badlogic** [comment]
Three possible reasons:

1. You didn't add a @CustomClass annotation
2. You didn't enable automatic project compilation on save
3. There is indeed a bug in the plugin

Head over to our docs to see how both things are done:
http://docs.robovm.com/getting-started/intellij.html

Please report back if this works for you!

**Comment by iitsoftware** [comment]
> Am 24.04.2015 um 16:38 schrieb Mario Zechner <notifications@github.com>:
> 
> Three possible reasons:
> 
> 1. You didn't add a @CustomClass annotation

Excatly that. Works now. Sorry for this issue.

-- 
Andreas Mueller
IIT Software GmbH, Bremen/Germany
http://www.swiftmq.com





IIT Software GmbH
Fahrenheitstr. 13, D28359 Bremen, Germany
Tel: +49 421 330 46 088, Fax: +49 421 330 46 090
Amtsgericht Bremen, HRB 18624, Geschaeftsfuehrer: Andreas Mueller
Steuernummer: 460/118/06404 VAT: DE199945912

**Comment by badlogic** [comment]
No problem! Closing this then.
