### ISSUE TITLE
UIApplicationDelegateAdapter.didReceiveMemoryWarning: 10 GC calls

### ISSUE THREAD

**Issue by magicgoose** [robovm/robovm#945]
Is there a reason for this code in `void didReceiveMemoryWarning(UIApplication application)`?:
([link](https://github.com/robovm/robovm/blob/47c6b1d64ac58f665571e049f1dae65b1dddf3fc/cocoatouch/src/main/java/org/robovm/apple/uikit/UIApplicationDelegateAdapter.java#L74))

    public void didReceiveMemoryWarning(UIApplication application) {
        for (int i = 0; i < 10; i++) {
            System.gc();
        }
    }

Because, if the GC is triggered after 1st call, then other 9 are useless, right?
And if it's not triggered, why would it trigger in any of the immediately following calls?
Looks like it's not helping in best case and wasting ~9x more resources than needed in worst case. Or there's some reason behind this? I think, this code deserves a comment. :)

**Comment by ntherning** [comment]
The GC doesn't start to give memory back to the OS until after a few calls. That's why the method looks like this. We will add a comment as you suggested.

**Comment by BlueRiverInteractive** [comment]
Added comment about what we do in `didReceiveMemoryWarning`.
