### ISSUE TITLE
How do I override `dealloc` in UIViewController subclasses?

### ISSUE THREAD

**Issue by magicgoose** [robovm/robovm#947]
I was looking for the pair method of `viewDidLoad`, found that it's deprecated and that I should use `dealloc` for undoing stuff done in `viewDidLoad` (link: http://stackoverflow.com/a/12603549/1418097). But how to override it? Seems like there's no such method.  
I'm guessing that the correct thing to do is to override `void doDispose()` method. Am I right?

**Comment by ntherning** [comment]
`doDispose()` would be a good place.

Please don't use the GitHub issues as a support forum. We have a Google Group you should use instead  : https://groups.google.com/group/robovm.

**Comment by magicgoose** [comment]
OK!
