### ISSUE TITLE
App crashes on start up after upgrade to 1.1.0  

### ISSUE THREAD

**Issue by mickmuzac** [robovm/robovm#949]
My game has been crashing immediately upon start up consistently since I upgraded to RoboVM 1.1.0. If I downgrade back down to 1.0.1, it does not crash. 

Here's the log I get after the crash:

```
Apr 24 14:24:52 My-iPhone kernel[0] <Notice>: xpcproxy[671] Container: /private/var/mobile/Containers/Data/Application/7665EFF1-9883-4546-B8CA-DD3F33B24F56 (sandbox)
Apr 24 14:24:52 My-iPhone locationd[64] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Apr 24 14:24:52 My-iPhone com.apple.xpc.launchd[1] (UIKitApplication:com.impressflow.libgdxgame[0x105d][671]) <Warning>: Service exited with abnormal code: 1
Apr 24 14:24:52 My-iPhone SpringBoard[43] <Warning>: Application 'UIKitApplication:com.impressflow.libgdxgame[0x105d]' exited voluntarily.
Apr 24 14:24:52 My-iPhone SpringBoard[43] <Warning>: Unable to deliver -[UIRemoteApplication showTopMostMiniAlertWithSynchronizationPort:] message to port 0: (ipc/send) invalid destination port
Apr 24 14:24:52 My-iPhone locationd[64] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Apr 24 14:24:52 My-iPhone kernel[0] <Notice>: xpcproxy[672] Container: /private/var/mobile/Containers/Data/Application/7665EFF1-9883-4546-B8CA-DD3F33B24F56 (sandbox)
Apr 24 14:24:53 My-iPhone com.apple.xpc.launchd[1] (UIKitApplication:com.impressflow.libgdxgame[0xc2f6][672]) <Warning>: Service exited with abnormal code: 1
Apr 24 14:24:53 My-iPhone SpringBoard[43] <Warning>: Application 'UIKitApplication:com.impressflow.libgdxgame[0xc2f6]' exited voluntarily.
Apr 24 14:24:53 My-iPhone SpringBoard[43] <Warning>: Unable to deliver -[UIRemoteApplication showTopMostMiniAlertWithSynchronizationPort:] message to port 0: (ipc/send) invalid destination port
```

The code compiles correctly with no errors. Judging by the limited output I'm receiving from the console, the app isn't reaching any of my application level code. I'm running:

XCode 6.3.1
iOS 8.3 (iPhone 5)
'com.android.tools.build:gradle:0.10+' Gradle plugin

More information can be found in this forum post:
http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=19137

Please let me know if you'd like more information.

**Comment by badlogic** [comment]
Could you detail your update process? What did you change in the Gradle
file? Did you update your IDE plugin? Does it work when launching from the
command line?

**Comment by mickmuzac** [comment]
I feel dumb.

I updated RoboVM via Gradle and I updated the version referenced by 'org.robovm:robovm-gradle-plugin'. But I didn't update the Gradle plugin in Eclipse.

This whole time, I thought updating the version of 'org.robovm:robovm-gradle-plugin' in my build.gradle file was enough to satisfy having to update the Gradle plugin.

I'll go ahead and close this.
