### ISSUE TITLE
@IBOutletCollection-annotated methods are called before object initialization

### ISSUE THREAD

**Issue by magicgoose** [robovm/robovm#951]
I have a class (which extends UIViewController), and it has a couple of instance variables. They are initialized in the declaration. Like the following:

    private UIButton[] row1 = new UIButton[3];
    private UIButton[] row2 = new UIButton[3];

And I have the method which is supposed to be called by iOS when loading storyboard, like this:

    @IBOutletCollection
    private void setButtons(NSArray<UIButton> buttons) {
        Assert.equals(6, buttons.size());
        for (int i = 0; i < 6; i++) {
            (i < 3 ? row1 : row2)[i % 3] = buttons.get(i);
        }
    }

AFAIK in Java it's not possible to call a method on uninitialized object. But when `setButtons` is called, these instance variables are `null`. How is that possible? And is it possible to fix?

**Comment by magicgoose** [comment]
Update: seems like constructors and/or initialization block are never called. (simply as that)

**Comment by badlogic** [comment]
There's already an issue for that on the tracker. As a work around you can
initialize your instance fields in viewDidLoad() of your controller.

**Comment by BlueRiverInteractive** [comment]
Related issue: https://github.com/robovm/robovm/issues/894

**Comment by ntherning** [comment]
Closing this as a duplicate of #894
