### ISSUE TITLE
"File name too long" during compile phase

### ISSUE THREAD

**Issue by jimmydivvy** [robovm/robovm#955]
I've created a library using Scala and Argonaut. It compiles and runs correctly on native Java and Android, however when running through the RoboVM compiler I get the following error

    Caused by: java.io.FileNotFoundException:   /Users/james/.robovm/cache/ios/x86/release/Users/james/.gradle/caches/modules-2/files-2.1/io.argonaut/argonaut_2.11/6.0.4/372a4ecf2e42f3517afd534e2f27b624643d8d67/argonaut_2.11-6.0.4.jar/argonaut/GeneratedDecodeJsons$$anonfun$Tuple10DecodeJson$1$$anonfun$apply$53$$anonfun$apply$54$$anonfun$apply$55$$anonfun$apply$56$$anonfun$apply$57$$anonfun$apply$58$$anonfun$apply$59$$anonfun$apply$60$$anonfun$apply$61$$anonfun$apply$62$$anonfun$apply$63.class.info (File name too long)
	at org.robovm.compiler.clazz.Clazz.saveClazzInfo(Clazz.java:107)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:848)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:285)

Looks like some of the anonymous classes generated by Scala are throwing out a class cache?

**I've created a stripped down example to replicate this in a repository here:**

    https://github.com/jimmydivvy/robovmbug_example

The fine print:
   - Mac OSX Yosemite, Brand spanking new OS install
   - Java 8, Scala 2.11.6
   - RoboVM 1.1
   - Project was created using IntelliJ.

**Comment by ntherning** [comment]
The file name `GeneratedDecodeJsons$$anonfun$Tuple10DecodeJson$1$$anonfun$apply$53$$anonfun$apply$54$$anonfun$apply$55$$anonfun$apply$56$$anonfun$apply$57$$anonfun$apply$58$$anonfun$apply$59$$anonfun$apply$60$$anonfun$apply$61$$anonfun$apply$62$$anonfun$apply$63.class.info` is 259 characters which exceeds the OS X limit of 255 characters. We need a way to clip such file names without risking name collisions. Maybe clip and append a SHA1 hash of the complete file name? Should be very unlikely to cause collisions when the complete file name is different.

**Comment by jimmydivvy** [comment]
You should be able to use the SHA1 hash of the filename quite safely - keep in mind git uses SHA1 hashes for every object inside every commit and doesn't have an issue with collisions.

http://www.quora.com/What-is-the-probability-that-two-two-commits-of-different-git-repositories-have-exact-same-SHA-hash

**Comment by ntherning** [comment]
Do you know if this has been reported to the Scala people? I would say that it's a bug in their code. The same kind of problem should hit anyone who tries to build Argonaut on OS X from source. The Scala compiler will generate that class file and try to store it on disk which should fail because of the long file name.

Anyways, I will try to implement the workaround in RoboVM to make this work.

**Comment by jimmydivvy** [comment]
The same code compiles correctly on OS X as a native Java application as well as an Android application. I'm not sure where the bug actually lies, but it's only being tripped up when compiled with RoboVM. I'll have another look to double check if I can replicate it without RoboVM and report to the Scala team as well if that's the case.
