### ISSUE TITLE
IntelliJ plugin possible memory leak

### ISSUE THREAD

**Issue by stefanli** [robovm/robovm#971]
After running with the RoboVM plugin for a couple of hours IntelliJ starts using a gigantic amount of memory (30+ gigs) and needs to be restarted. This doesn't happen without the plugin so I'm assuming the problem lies with RoboVM. 
![screen shot 2015-05-05 at 8 31 49 pm](https://cloud.githubusercontent.com/assets/124695/7487160/978317f6-f366-11e4-9c0c-3304ad7439a1.png)

**Comment by ntherning** [comment]
Moved to robovm/robovm-idea#55
