### ISSUE TITLE
Aggressive TreeShaking shouldn't strip used global value methods of LazyGlobalValues.

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#991]
For example `NSLocaleComponent` is a GlobalValueEnumeration<NSString> which relies on LazyGlobalValues. The static class `NSLocaleComponent.Values` has all the `@GlobalValue` annotated getter-methods. These methods get stripped because they are not directly referenced anywhere. The `LazyGlobalValue` of each `NSLocaleComponent` uses reflection to access these getter-methods.

The aggressive treeshaker should understand the LazyGlobalValue class and if a `LazyGlobalValue` is referenced somewhere it should also keep the `@GlobalValue` annotated getter-method that belongs to it.

**Comment by ntherning** [comment]
You can now add `@StronglyLinked` on the class level to these classes and no methods in them will ever be stripped even in `aggressive` tree shaking mode. Probably should do that from `bro-gen`, right?
